force-app/main/default/objects/Trip_Report__c/Trip_Report__c.object-meta.xml
<CustomObject>
    <label>Trip Report</label>
    <nameField>
        <label>Trip Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Report__c/fields/Account_Visited__c.field-meta.xml
<CustomField>
    <fullName>Account_Visited__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Visited</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trip Reports</relationshipLabel>
    <relationshipName>Trip_Reports2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Date_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Visit__c</fullName>
    <label>Date of Visit</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/listContVisitedTest.cls
@isTest (seeAllData=false)
private class listContVisitedTest {

    public static account tAccount;
    public static contact tContact;
    public static Trip_Report__c tTrip;
    private static list<contact> tconts;
    
    public static ID objId;
    
    static void init() {
        tAccount = new account (Name='Test Account');
        insert tAccount;
        system.debug(tAccount);

        tconts = new List<Contact>();
        for (Integer i = 0; i < 101; i++) {
            tconts.add(new contact (AccountID=tAccount.ID,FirstName='Test - '+i.format(),
                                    LastName='Contact'+i.format()));
        }
        insert tconts;

        tTrip = new Trip_Report__c(Account_Visited__c=tAccount.ID, Date_of_Visit__c=system.today());
        insert tTrip;
		system.debug(tTrip);
        objId = tTrip.ID;
        system.debug(objId);
    }
    
    public static testMethod void testContVisited () {
        init();
        Test.startTest();
		
        listContVisited cVisit = new listContVisited();
        cVisit.objId = objId;
        cVisit.getlistContVisited();

        system.debug(cVisit);
        
        Test.stopTest();
        
    }
}