force-app/main/default/objects/Trip_Report__c/Trip_Report__c.object-meta.xml
<CustomObject>
    <label>Trip Report</label>
    <nameField>
        <label>Trip Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Report__c/fields/Account_Visited__c.field-meta.xml
<CustomField>
    <fullName>Account_Visited__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Visited</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trip Reports</relationshipLabel>
    <relationshipName>Trip_Reports2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataFactoryTest.cls
/***********************************************************************************************************************************
Developer :Suyati
Name      : TestDataFactoryTest
Associated Apex Class:TestDataFactory
Date      : October 2019   
************************************************************************************************************************************/ 
@isTest
public class TestDataFactoryTest {
    /***********************************************************************************************************************************
Method Name  : createAccountTest
Method Tested  : createAccount() 
************************************************************************************************************************************/   
    static testMethod void createAccountTest() {
        test.startTest();
        Account TestAccount = TestDataFactory.createAccount();
        test.stopTest();
        List<Account> QueryAccount = [select id,name from account  where  id=:TestAccount.id];
        system.assertEquals(true , QueryAccount.size()>0);
    }
    /***********************************************************************************************************************************
Method Name  : createTripReportTest
Method Tested  : createTripReport(String) 
************************************************************************************************************************************/   
    static testMethod void createTripReportTest() {
        test.startTest();
        Account TestAccount = TestDataFactory.createAccount();
        Trip_Report__c TestTripReport=TestDataFactory.createTripReport(TestAccount.id);
        test.stopTest();
        Trip_Report__c TripReport = [select id,Account_Visited__c,Account_Visited__r.name from Trip_Report__c where Account_Visited__c = :TestAccount.id];
        Account queryAccount=[select id, name from Account];
        system.assertEquals(queryAccount.name , TripReport.Account_Visited__r.name);
    }
}