force-app/main/default/objects/Fleet__c/Fleet__c.object-meta.xml
<CustomObject>
    <label>Fleet</label>
    <nameField>
        <label>Fleet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Fleet__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <label>Date Booked</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fleet__c/fields/Length_GILLIG__c.field-meta.xml
<CustomField>
    <fullName>Length_GILLIG__c</fullName>
    <label>Length (GILLIG)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fleet__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>DIESEL</fullName>
            </value>
            <value>
                <fullName>ELECTRIC</fullName>
            </value>
            <value>
                <fullName>HYBRID ALLISON</fullName>
            </value>
            <value>
                <fullName>HYBRID BAE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fleet__c/fields/Year_Booked__c.field-meta.xml
<CustomField>
    <fullName>Year_Booked__c</fullName>
    <formula>IF(RecordType.Name = &apos;Competitor&apos;, text(YEAR( Competitor_Date_Delivered__c )), text(YEAR(Sales_Order__r.Start_Date__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fleet__c/recordTypes/GILLIG.recordType-meta.xml
<RecordType>
    <fullName>GILLIG</fullName>
    <active>true</active>
    <description>Gillig Fleet Data</description>
    <label>GILLIG</label>
</RecordType>

force-app/main/default/classes/defaultFleetTest.cls
@isTest (seeAlldata=false)
public class defaultFleetTest {

    @testSetup static void init () {
        TestData.init();
        TestData.createAcct();
        TestData.createOpp();
        TestData.createContract();
        TestData.createOppLine(5, 5);
        TestData.createSO();
    }
    
    static testmethod void checkFleetName () {

        test.startTest();

        List<Fleet__c> resultingFleet = [select id, Name, Date_Booked__c, Year_Booked__c, Start_Date__c, Mode__c, Length_GILLIG__c from Fleet__c];

        for (Fleet__c tFleet:resultingFleet) {

            string fName = 'GILLIG - ' + String.valueOf(tFleet.Start_Date__c.year()) + ' ' + tFleet.Length_GILLIG__c 
                                + ' ' + tFleet.Mode__c;

            system.assertEquals(fName, tFleet.Name);
        }
        test.stopTest();
    }
}