force-app/main/default/objects/Exception_Day__c/Exception_Day__c.object-meta.xml
<CustomObject>
    <label>Exception Day</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Day__c/fields/Exception_Date__c.field-meta.xml
<CustomField>
    <fullName>Exception_Date__c</fullName>
    <description>Holds the Date of the holiday or Saturday&apos;s details</description>
    <label>Exception Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Exception_Day__c/fields/Slots__c.field-meta.xml
<CustomField>
    <fullName>Slots__c</fullName>
    <description>Holds max slots allowed on this working day. For holiday, default value will be considered</description>
    <label>Slots</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exception_Day__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Holds working day vs holiday. BTW, working day provisioning is required for only Saturday or Sunday. Not for Mon-Fri</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Working Day</fullName>
            </value>
            <value>
                <fullName>Scheduled Week</fullName>
            </value>
            <value>
                <fullName>Default Slots Per Day</fullName>
            </value>
            <value>
                <fullName>Slots Per Week Constant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExceptionDaysTriggerHandlerTest.cls
@isTest
private class ExceptionDaysTriggerHandlerTest { 
	
	@testSetup
	static void init() {
		
		DisplayBoardDataTest.initCustomMetaData( '01/02/2017');
        Exception_Day__c scheduledWeek = new Exception_Day__c( Name = 'Scheduled Week',
        													Exception_Date__c = Date.newInstance( 2017, 01, 02),
        													Type__c = 'Scheduled Week'
        													);
        Exception_Day__c holiday = new Exception_Day__c( Name = 'Holiday ',
        													Exception_Date__c = Date.newInstance( 2017, 01, 03),
        													Type__c = 'Holiday'
        													);
        Exception_Day__c workingDay = new Exception_Day__c( Name = 'Working Day',
        													Exception_Date__c = Date.newInstance( 2017, 01, 04),
        													Type__c = 'Working Day',
        													Slots__c = 9
        													);
        Exception_Day__c slotsPerWeekConstant = new Exception_Day__c( Name = 'Slots Per Week Constant',
        													Exception_Date__c = Date.newInstance( 2017, 01, 09),
        													Type__c = 'Slots Per Week Constant',
        													Slots__c = 100);
       Exception_Day__c slotsPerDay = new Exception_Day__c( Name = 'Default Slots Per Day',
        													Exception_Date__c = Date.newInstance( 2017, 01, 02),
        													Type__c = 'Default Slots Per Day',
        													Slots__c = 10);
   		Insert scheduledWeek;
  		Insert holiday;
  		Insert workingDay;
  		Insert slotsPerWeekConstant;
  		Insert slotsPerDay;
	}
	
	@isTest
	static void test_IsAlphaNumeric() {
		System.assert( DisplayBoardFunctions.IsAlphaNumeric( '123AA'));
		System.assert( DisplayBoardFunctions.IsAlphaNumeric( '123'));
		System.assert( DisplayBoardFunctions.IsAlphaNumeric( 'AA'));
		System.assert( !DisplayBoardFunctions.IsAlphaNumeric( '123 AA'));
		System.assert( !DisplayBoardFunctions.IsAlphaNumeric( '123 = AA'));
	}
	
	

}