force-app/main/default/objects/Exception_Day__c/Exception_Day__c.object-meta.xml
<CustomObject>
    <label>Exception Day</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Day__c/fields/Exception_Date__c.field-meta.xml
<CustomField>
    <fullName>Exception_Date__c</fullName>
    <description>Holds the Date of the holiday or Saturday&apos;s details</description>
    <label>Exception Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Exception_Day__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Holds working day vs holiday. BTW, working day provisioning is required for only Saturday or Sunday. Not for Mon-Fri</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Working Day</fullName>
            </value>
            <value>
                <fullName>Scheduled Week</fullName>
            </value>
            <value>
                <fullName>Default Slots Per Day</fullName>
            </value>
            <value>
                <fullName>Slots Per Week Constant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExceptionDaysTriggerHandlerSDayTest.cls
@isTest
private class ExceptionDaysTriggerHandlerSDayTest {
	
//	@testSetup
	static void init() {
		DisplayBoardDataTest.initCustomMetaData( '01/02/2017');	
        Exception_Day__c scheduledWeek = new Exception_Day__c( Name = 'Scheduled Week',
        													Exception_Date__c = Date.newInstance( 2017, 01, 02),
        													Type__c = 'Scheduled Week'
        													);
   		Insert scheduledWeek;
  		DisplayBoardConstants.initializeexceptionDays();
	}
	
	@isTest
	static void test_InsertScheduledWeek_Good() {
		init();
		test.startTest();
//		init();
        Exception_Day__c day = new Exception_Day__c( Name = 'Scheduled Week',
        													Exception_Date__c = Date.newInstance( 2017, 01, 09),
        													Type__c = 'Scheduled Week');
 		Insert  day;      													
        System.assert( day.Id != null, 'Failed to create record');
		test.stopTest();
	}

	@isTest
	static void test_InsertScheduledWeek_Bad() {
		init();
		test.startTest();
//		init();
        Exception_Day__c day = new Exception_Day__c( Name = 'Scheduled Week',
        													Exception_Date__c = Date.newInstance( 2017, 01, 10),
        													Type__c = 'Scheduled Week');
        Database.SaveResult result;
        try { 													
	        result = Database.Insert(day);
        } catch( System.DMLException e) {
         	Boolean expectedExceptionThrown =  e.getMessage() != null ? true : false;
			System.AssertEquals(expectedExceptionThrown, true);
       }
		test.stopTest();
	}

	@isTest
	static void test_InsertScheduledWeek_Bad2() {
		init();
		test.startTest();
//		init();
        Exception_Day__c day = new Exception_Day__c( Name = 'Scheduled Week',
        													Exception_Date__c = Date.newInstance( 2017, 04, 10),
        													Type__c = 'Scheduled Week');
        Database.SaveResult result;
        try { 													
	        result = Database.Insert(day);
        } catch( System.DMLException e) {
         	Boolean expectedExceptionThrown =  e.getMessage() != null ? true : false;
			System.AssertEquals(expectedExceptionThrown, true);
       }
		test.stopTest();
	}

	@isTest
	static void test_InsertScheduledWeek_Bad3() {
		init();
		test.startTest();
//		init();
        Exception_Day__c day = new Exception_Day__c( Name = 'Scheduled Week',
        													Exception_Date__c = Date.newInstance( 2017, 01, 02),
        													Type__c = 'Scheduled Week');
        Database.SaveResult result;
        try { 													
	        result = Database.Insert(day);
        } catch( System.DMLException e) {
         	Boolean expectedExceptionThrown =  e.getMessage() != null ? true : false;
			System.AssertEquals(expectedExceptionThrown, true);
       }
		test.stopTest();
	}	

	@isTest
	static void test_UpdateScheduledWeek_Bad() {
		init();
		test.startTest();
//		init();
        Exception_Day__c day = new Exception_Day__c( Name = 'Scheduled Week',
        													Exception_Date__c = Date.newInstance( 2017, 01, 09),
        													Type__c = 'Scheduled Week');
        Database.Insert( day);
        day.Exception_Date__c = Date.newInstance( 2017, 04, 24);
        Database.SaveResult result;
        try { 													
	        result = Database.Update( day);
        } catch( System.DMLException e) {
        	Boolean expectedExceptionThrown =  e.getMessage() != null ? true : false;
			System.AssertEquals(expectedExceptionThrown, true);
        }
        test.stopTest();
	}
	
	@isTest
	static void test_DeleteScheduledWeek_Bad() {
		init();
		test.startTest();
//		init();
        Exception_Day__c day = new Exception_Day__c( Name = 'Scheduled Week',
        													Exception_Date__c = Date.newInstance( 2017, 01, 09),
        													Type__c = 'Scheduled Week');
        Database.Insert(day);
        Database.DeleteResult result = null;
        try { 													
	        result = Database.delete( day);
        } catch( System.DMLException e) {
        	Boolean expectedExceptionThrown =  e.getMessage() != null ? true : false;
			System.AssertEquals(expectedExceptionThrown, true);
        }
		test.stopTest();
	}

}