force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Left_Company__c.field-meta.xml
<CustomField>
    <fullName>Left_Company__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Left Company</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Trip_Report__c/Trip_Report__c.object-meta.xml
<CustomObject>
    <label>Trip Report</label>
    <nameField>
        <label>Trip Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Report__c/fields/Account_Visited__c.field-meta.xml
<CustomField>
    <fullName>Account_Visited__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Visited</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trip Reports</relationshipLabel>
    <relationshipName>Trip_Reports2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TripContact__c/TripContact__c.object-meta.xml
<CustomObject>
    <label>Contact Visited</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>TripContact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts Visited</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TripContact__c/fields/ContactName__c.field-meta.xml
<CustomField>
    <fullName>ContactName__c</fullName>
    <formula>TripContact__r.FirstName + &quot; &quot; +  TripContact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContactName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TripContact__c/fields/TripContact__c.field-meta.xml
<CustomField>
    <fullName>TripContact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trip Reports</relationshipLabel>
    <relationshipName>Trip_Visit</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TripContact__c/fields/TripReport__c.field-meta.xml
<CustomField>
    <fullName>TripReport__c</fullName>
    <label>Trip Report</label>
    <referenceTo>Trip_Report__c</referenceTo>
    <relationshipLabel>Contacts Visited</relationshipLabel>
    <relationshipName>Contacts_Visited</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TripContact__c/fields/Visited__c.field-meta.xml
<CustomField>
    <fullName>Visited__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visited?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ContactVisitedComponentController.cls
/***********************************************************************************************************************************
Developer :Suyati
Name      : ContactVisitedComponentController
Usage     : Apex Controller to create new tripcontact and update existing ones.
Associated Component:ContactVisitedComponent
Date      : October 2019   
************************************************************************************************************************************/   
public class ContactVisitedComponentController {
    /***********************************************************************************************************************************
    Method Name  : getTripContacts
    Parameters   : Id
    Return Type  : list<VisitedContactWrapper>   
    Method call  : getTripContacts(recordId)
    Description  : Returns a list of contact and their associated tripcontact for a given tripreport
    ************************************************************************************************************************************/   
    @auraEnabled
    public static list<VisitedContactWrapper> getTripContacts(Id recordId){   
        list<VisitedContactWrapper> contactwrapperList=new list<VisitedContactWrapper>();
        String AccountVisitedId=[select id,account_visited__c from Trip_Report__c where  id=:recordId].account_visited__c;
        try{
            list<Contact> ContactList=[SELECT Id,Name,phone,mobilephone,Email,accountId,account.Name,(select id,ContactName__c,Visited__c,Name,TripReport__c from Trip_Visit__r  where TripReport__c =:recordId) from contact  where accountId=:AccountVisitedId and Left_Company__c=False  order by createddate asc ];
            for(Contact contactRecord:ContactList)
            {
                VisitedContactWrapper contactWrapper = new VisitedContactWrapper();
                contactWrapper.contactId=contactRecord.Id;
                contactWrapper.accountId=contactRecord.AccountId;
                contactWrapper.contactName=contactRecord.Name;
                contactWrapper.tripReportId =recordId;
                contactWrapper.email=contactRecord.Email;
                contactWrapper.phone=contactRecord.Phone;
                contactWrapper.mobilePhone=contactRecord.MobilePhone;
                if(contactRecord.Trip_Visit__r.size()>0)
                {
                    TripContact__c tripContact =new TripContact__c();
                    tripContact=contactRecord.Trip_Visit__r[0]; 
                    contactWrapper.tripContactId = tripContact.Id;
                    contactWrapper.isVisited=tripContact.Visited__c;
                }
                else
                    contactWrapper.isVisited=FALSE;
                contactwrapperList.add(contactWrapper);
            }
            
        }
        catch(exception e)
        {
            system.debug('Message'+e.getMessage());
        }
        return contactwrapperList;
    }
    
    /***********************************************************************************************************************************
    Class Name   : VisitedContactWrapper
    Description  : To store value of contact details and their respective tripcontact(visited field)
    Used In       :  getTripContacts  method
    ************************************************************************************************************************************/     
    public class VisitedContactWrapper {
        @auraEnabled
        public Id contactId;
        @auraEnabled
        public Id accountId;
        @auraEnabled
        public string tripContactId;
        @auraEnabled
        public boolean isVisited;
        @auraEnabled
        public string contactName;
        @auraEnabled
        public string tripReportId;
        @auraEnabled
        public string email;
        @auraEnabled
        public string phone;
        @auraEnabled
        public string mobilePhone;
        
    }
    
    /***********************************************************************************************************************************
    Method Name  : getRecordtypeId
    Parameters   : none
    Return Type  : string    
    Method call  : getRecordtypeId()
    Description  : Returns recordtype Id from recordtype name
    ************************************************************************************************************************************/   
    @auraEnabled 
    public static string getRecordtypeId()
    {
        String recordtypeId;
        try{
            recordtypeId=Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
            
        }
        catch(exception e)
        {
            system.debug('Message'+e.getMessage());
        }
        return recordtypeId;
    }
    
    /***********************************************************************************************************************************
    Method Name  : createTripContact
    Parameters   : string,string
    Return Type  : list<VisitedContactWrapper>   
    Method call  : createTripContact(tripContactListJson,recordId)
    Description  : To create a new tripcontact or update existing tripcontact
    ************************************************************************************************************************************/   
    @auraEnabled
    public static list<VisitedContactWrapper>createTripContact(string tripContactListJson,string recordId  ){
        
        List<VisitedContactWrapper>tripContactList = (List<VisitedContactWrapper>) JSON.deserialize(tripContactListJson,List<VisitedContactWrapper>.class);
        List<TripContact__c>tripContactInsertList= new List<TripContact__c>();
        List<TripContact__c>tripContactUpdateList= new List<TripContact__c>();
        try
        {
            for(VisitedContactWrapper contactWrapper :tripContactList)
            {
                if(contactWrapper.tripContactId==NULL)
                {
                    if(contactWrapper.isVisited)
                    {
                        TripContact__c newTripContact = new TripContact__c(Visited__c=TRUE,TripReport__c=recordId,TripContact__c=contactWrapper.contactId);
                        tripContactInsertList.add(newTripContact);
                        
                    }
                    else
                    {
                        continue;
                    }
                }
                else
                {   TripContact__c newTripContact=new TripContact__c(Id=contactWrapper.tripContactId,Visited__c=contactWrapper.isVisited);
                 tripContactUpdateList.add(newTripContact);
                } 
            } insert tripContactInsertList;
            update tripContactUpdateList; 
        }
        catch(Exception e)
        {
            throw new AuraHandledException(e.getMessage()); 
        }
        return tripContactList;
    }
}