force-app/main/default/objects/Account/fields/Artic_Bus_Plans__c.field-meta.xml
<CustomField>
    <fullName>Artic_Bus_Plans__c</fullName>
    <description>Describe the customer&apos;s high-level Articulated Bus Plans</description>
    <label>Articulated Bus Plans</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Electric_Bus_Plans__c.field-meta.xml
<CustomField>
    <fullName>Electric_Bus_Plans__c</fullName>
    <description>Describe the customer&apos;s high level plans for electric buses</description>
    <label>Electric Bus Plans</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fleet_Replacement_Plans__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Replacement_Plans__c</fullName>
    <label>Fleet Replacement Plans</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fuel_Cell_Bus_Plans__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Cell_Bus_Plans__c</fullName>
    <label>Fuel Cell Bus Plans</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ridership__c.field-meta.xml
<CustomField>
    <fullName>Ridership__c</fullName>
    <label>Ridership</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/Trip_Report__c.object-meta.xml
<CustomObject>
    <label>Trip Report</label>
    <nameField>
        <label>Trip Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Report__c/fields/Account_Visited__c.field-meta.xml
<CustomField>
    <fullName>Account_Visited__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Visited</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trip Reports</relationshipLabel>
    <relationshipName>Trip_Reports2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Artic_Bus_Plans__c.field-meta.xml
<CustomField>
    <fullName>Artic_Bus_Plans__c</fullName>
    <label>Articulated Bus Plans</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Date_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Visit__c</fullName>
    <label>Date of Visit</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Electric_Bus_Plans__c.field-meta.xml
<CustomField>
    <fullName>Electric_Bus_Plans__c</fullName>
    <label>Electric Bus Plans</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Fleet_Performance__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Performance__c</fullName>
    <label>Fleet Performance Updates</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Fleet_Replacement_Plans__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Replacement_Plans__c</fullName>
    <label>Fleet Replacement Plans</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Fuel_Cell_Bus_Plans__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Cell_Bus_Plans__c</fullName>
    <label>Fuel Cell Bus Plans</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Ridership__c.field-meta.xml
<CustomField>
    <fullName>Ridership__c</fullName>
    <label>Ridership</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
/***********************************************************************************************************************************
     Developer :Suyati
     Name      : TestDataFactory
     Usage     : Creation of test data
     Date      : October 2019   
************************************************************************************************************************************/   
global class TestDataFactory {
    /***********************************************************************************************************************************
     Method Name  : createAccount
     Parameters   : None
     Return Type  : Account    
     Method call  : createAccount()
     Description  : Creation of Account
   ************************************************************************************************************************************/  
    global static Account createAccount()
    {
        Account testAccount= new Account();
        testAccount.name='test Account';
        insert testAccount;
        return testAccount;
    }
       /***********************************************************************************************************************************
     Method Name  : createTripReport
     Parameters   : Id
     Return Type  : Trip_Report__c    
     Method call  : createTripReport(AccountId)
     Description  : Creation of trip report 
   ************************************************************************************************************************************/  
    global static Trip_Report__c createTripReport(Id AccountId)
    {
        Trip_Report__c tripReport= new Trip_Report__c();
        tripReport.Account_Visited__c=AccountId;
        tripReport.Date_of_Visit__c=System.today();
        tripReport.Ridership__c='Karen stated that ridership was up by 3% in 2019 ';
        tripReport.Artic_Bus_Plans__c='No 60 ft. bus interest';
        tripReport.Electric_Bus_Plans__c='No electric bus interest was expressed';
        tripReport.Fleet_Replacement_Plans__c='Karen stated she will have an ITB for 2- 29 ft. diesel buses out this Fall 2019. She stated they want equipped much like the 35 ft. buses. We discussed adding right front skid pad and rear skid pads to the technical specifications.';
        tripReport.Fleet_Performance__c='Performance was good';
        tripReport.Fuel_Cell_Bus_Plans__c='No fuel cell bus plan interest';
        insert tripReport;
        return tripReport;
    }
}