force-app/main/default/objects/Account/fields/Artic_Bus_Plans__c.field-meta.xml
<CustomField>
    <fullName>Artic_Bus_Plans__c</fullName>
    <description>Describe the customer&apos;s high-level Articulated Bus Plans</description>
    <label>Articulated Bus Plans</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Electric_Bus_Plans__c.field-meta.xml
<CustomField>
    <fullName>Electric_Bus_Plans__c</fullName>
    <description>Describe the customer&apos;s high level plans for electric buses</description>
    <label>Electric Bus Plans</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fleet_Performance_Updates__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Performance_Updates__c</fullName>
    <label>Fleet Performance Updates</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fleet_Replacement_Plans__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Replacement_Plans__c</fullName>
    <label>Fleet Replacement Plans</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <label>Customer Contract Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Stage__c.field-meta.xml
<CustomField>
    <fullName>Bid_Stage__c</fullName>
    <label>Bid Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Specification Received</fullName>
            </value>
            <value>
                <fullName>Prepare Approved Equals</fullName>
            </value>
            <value>
                <fullName>Awaiting Approved Equals</fullName>
            </value>
            <value>
                <fullName>Prepare Bid</fullName>
            </value>
            <value>
                <fullName>Clarifications</fullName>
            </value>
            <value>
                <fullName>BAFO</fullName>
            </value>
            <value>
                <fullName>Awaiting Decision</fullName>
            </value>
            <value>
                <fullName>Intent to Award GILLIG</fullName>
            </value>
            <value>
                <fullName>Award GILLIG</fullName>
            </value>
            <value>
                <fullName>Award Competitor</fullName>
            </value>
            <value>
                <fullName>No-Bid</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Status__c.field-meta.xml
<CustomField>
    <fullName>Bid_Status__c</fullName>
    <label>Bid Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bid</fullName>
            </value>
            <value>
                <fullName>Reviewing</fullName>
            </value>
            <value>
                <fullName>No-Bid</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Submission_Type__c.field-meta.xml
<CustomField>
    <fullName>Bid_Submission_Type__c</fullName>
    <label>Bid Submission Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Mail In</fullName>
            </value>
            <value>
                <fullName>Mail In &amp; USB</fullName>
            </value>
            <value>
                <fullName>Mail In &amp; Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Lead_Agency__r.Internal_Name__c</formula>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Lead_Agency__c.field-meta.xml
<CustomField>
    <fullName>Lead_Agency__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lead Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Sales Manager Assigned to the Bid</description>
    <label>Project Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/recordTypes/GILLIG.recordType-meta.xml
<RecordType>
    <fullName>GILLIG</fullName>
    <active>true</active>
    <description>GILLIG Contract</description>
    <label>GILLIG</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Account.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_Probability__c.field-meta.xml
<CustomField>
    <fullName>Order_Probability__c</fullName>
    <label>Order Probability</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. High Probability</fullName>
            </value>
            <value>
                <fullName>2. Medium Probability</fullName>
            </value>
            <value>
                <fullName>3. Low Probability</fullName>
            </value>
            <value>
                <fullName>4. Unlikely</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <formula>Account.Project_Sales_Manager__r.FirstName + &apos; &apos; +  Account.Project_Sales_Manager__r.LastName</formula>
    <label>Project Sales Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/Opportunity_Line__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line</label>
    <nameField>
        <label>Opportunity Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Opportunity_Line__r.Account.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Opportunity_Line__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Lines</relationshipLabel>
    <relationshipName>Opportunity_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <formula>Opportunity_Line__r.Account.Project_Sales_Manager__r.FirstName  + &apos; &apos; +   Opportunity_Line__r.Account.Project_Sales_Manager__r.LastName</formula>
    <label>Project Sales Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/recordTypes/Booked.recordType-meta.xml
<RecordType>
    <fullName>Booked</fullName>
    <active>false</active>
    <label>Booked</label>
</RecordType>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Account__r.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity which generated the Sales Order</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <summarizedField>Opportunity_Sales_Order__c.Quantity__c</summarizedField>
    <summaryForeignKey>Opportunity_Sales_Order__c.Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/Trip_Report__c.object-meta.xml
<CustomObject>
    <label>Trip Report</label>
    <nameField>
        <label>Trip Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Report__c/fields/Account_Visited__c.field-meta.xml
<CustomField>
    <fullName>Account_Visited__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Visited</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trip Reports</relationshipLabel>
    <relationshipName>Trip_Reports2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Artic_Bus_Plans__c.field-meta.xml
<CustomField>
    <fullName>Artic_Bus_Plans__c</fullName>
    <label>Articulated Bus Plans</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Date_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Visit__c</fullName>
    <label>Date of Visit</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Electric_Bus_Plans__c.field-meta.xml
<CustomField>
    <fullName>Electric_Bus_Plans__c</fullName>
    <label>Electric Bus Plans</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Fleet_Replacement_Plans__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Replacement_Plans__c</fullName>
    <label>Fleet Replacement Plans</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Account_Visited__r.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TripOpportunity__c/TripOpportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity Discussed</label>
    <nameField>
        <displayFormat>TO-{00000}</displayFormat>
        <label>tripopportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities Discussed</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TripOpportunity__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/TripOpportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Trip Reports</relationshipLabel>
    <relationshipName>Trip_Report</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TripOpportunity__c/fields/TripReport__c.field-meta.xml
<CustomField>
    <fullName>TripReport__c</fullName>
    <label>Trip Report</label>
    <referenceTo>Trip_Report__c</referenceTo>
    <relationshipLabel>Opportunities Discussed</relationshipLabel>
    <relationshipName>Opportunities_Discussed</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/updatesfromTripTest.cls
@isTest (seeAlldata=true)
public class updatesfromTripTest {
    
    static user rRep;
    static user pRep;
    static account tAccount;
    static account preUpd;
    static account postUpd;
    static Trip_Report__c TripReport;
    static Opportunity commentOpp;
    static Opportunity nocommentOpp;
    static TripOpportunity__c oppDiscussed;

    static void init(){
        
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

        system.runAs(thisUser) {
            Profile p = [SELECT Id FROM Profile WHERE Name='Regional Sales Manager'];
            rRep = new user(LastName = 'National Sales Rep', Username = 'NationalSales.User@example.com', Email = 'NationalSales.User@example.com', 
                        Alias = 'rRep', CommunityNickname = 'rRep', 
                        TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',
                       	EmailEncodingKey = 'ISO-8859-1', ProfileId = p.ID,
                       	LanguageLocaleKey = 'en_US');
            insert rRep;
            Profile pm = [SELECT Id FROM Profile WHERE Name='Project Sales Manager'];
            pRep = new user(LastName = 'Project Sales Rep', Username = 'ProjectSales.User@example.com', Email = 'ProjectSales.User@example.com', 
                        Alias = 'pRep', CommunityNickname = 'pRep', 
                        TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',
                        EmailEncodingKey = 'ISO-8859-1', ProfileId = pm.ID,
                        LanguageLocaleKey = 'en_US');
            insert pRep;
        }
        tAccount = new account(Name='Test Account', Internal_Name__c='Test, Ca', 
                                OwnerId = rRep.Id, Project_Sales_Manager__c = pRep.Id,
                                Artic_Bus_Plans__c = 'Artic plan', 
                                Electric_Bus_Plans__c = 'Electric Plan', Fleet_Performance_Updates__c = 'Fleet Perf Plan', 
                                Fleet_Replacement_Plans__c= 'Fleet Repl Plan');
        insert tAccount;
        List<Contact> tconts = new List<Contact>();
        for (Integer i = 0; i < 101; i++) {
            tconts.add(new contact (AccountID=tAccount.ID,FirstName='Test - '+i.format(),
                                    LastName='Contact'+i.format()));
        }
        insert tconts;
        commentOpp = new opportunity(AccountID = tAccount.Id, Name='Opp with comment',StageName='Forecast', 
                                                    Type = 'Existing Business', Order_Probability__c = '1. High Probability',
                                                    CloseDate=system.today());
        insert commentOpp;
        nocommentOpp = new opportunity(AccountID = tAccount.Id, Name='Opp without comment',StageName='Forecast', 
                                                    Type = 'Existing Business', Order_Probability__c = '1. High Probability',
                                                    CloseDate=system.today());
        insert nocommentOpp;
        TripReport = new Trip_Report__c(Account_Visited__c=tAccount.Id, Date_of_Visit__c=system.today());
        insert TripReport;
        oppDiscussed = [select TripReport__c, Opportunity__c, Comments__c 
                                               from TripOpportunity__c where TripReport__c=:TripReport.Id AND Opportunity__c =:commentOpp.Id ];
        oppDiscussed.Comments__c = 'Test comment';
        update oppDiscussed;

        recordtype rType = [select id from recordtype where Name = 'GILLIG' and SOBJECTTYPE = 'Customer_Contract__c' limit 1];

        Customer_Contract__c cContract = new Customer_Contract__c (name = 'Test Contract', ownerid = rRep.Id, RecordTypeID = rType.ID,
                                                                  Lead_Agency__c = tAccount.Id, Project_Sales_Manager__c = pRep.Id,
                                                                  Bid_Status__c = 'Bid', Bid_Stage__c = 'Award GILLIG', Bid_Submission_Type__c = 'Email');
        insert cContract;
        
        // Opportunity line with Date Booked when record created
        List<Opportunity_Line__c> tOppLine = new List<Opportunity_Line__c>();
        tOppLine.add(new Opportunity_Line__c (Opportunity_Line__c = commentOpp.Id, 
                                            Quantity__c = 2,
                                            Serial_Number__c = '123456',
                                            Date_Booked__c = system.today(), 
                                            Mode__c = 'Diesel',
                                            PO_Amount__c = 150, 
                                            PO_Date__c = system.today(), 
                                            PO_Reference__c = 'Test PO',
                                            Quoted_Price__c = 100, 
                                            Reference_Contract__c = cContract.Id,
                                            Style__c = 'LF',
                                            Length__c = '40',
                                            Start_Date__c = system.today()));

        insert tOppLine;
        createSO.insertSO(tOppLine);
        list<Sales_Order__c> resultingSO = new list<Sales_Order__c>([select id, Name  from Sales_Order__c where Name = :tOppLine[0].Serial_Number__c]);

    }
    
    static testmethod void testAcctUpdate (){
        init();
        
        test.startTest();
        
        preUpd = [select ID, Artic_Bus_Plans__c, 
                               Electric_Bus_Plans__c, Fleet_Performance_Updates__c, 
                               Fleet_Replacement_Plans__c from account where id=:tAccount.Id];
        
        system.assertEquals('Artic plan', preUpd.Artic_Bus_Plans__c);
        system.assertEquals('Electric Plan', preUpd.Electric_Bus_Plans__c);
        system.assertEquals('Fleet Perf Plan', preUpd.Fleet_Performance_Updates__c);
        system.assertEquals('Fleet Repl Plan', preUpd.Fleet_Replacement_Plans__c);
        
        Trip_Report__c Trip = [select ID, Name, Account_Visited__c, OwnerID, Status__c,Artic_Bus_Plans__c,Electric_Bus_Plans__c,
                                Fleet_Performance__c, Fleet_Replacement_Plans__c 
                                from Trip_Report__c where id = :TripReport.id];

        Trip.Status__c = 'Final';
        Trip.Artic_Bus_Plans__c = 'Artic_Bus_Plans__c';
        Trip.Electric_Bus_Plans__c = 'Electric_Bus_Plans__c';
        Trip.Fleet_Performance__c = 'Fleet_Performance__c';
        Trip.Fleet_Replacement_Plans__c = 'Fleet_Replacement_Plans__c';

        update Trip;
        
        postUpd = [select ID, Artic_Bus_Plans__c, 
                               Electric_Bus_Plans__c, Fleet_Performance_Updates__c, 
                               Fleet_Replacement_Plans__c from account where id = :tAccount.Id];
        system.assertNotEquals('Artic plan', postUpd.Artic_Bus_Plans__c);
        system.assertNotEquals('Electric Plan', postUpd.Electric_Bus_Plans__c);
        system.assertNotEquals('Fleet Perf Plan', postUpd.Fleet_Performance_Updates__c);
        system.assertNotEquals('Fleet Repl Plan', postUpd.Fleet_Replacement_Plans__c);
        system.assertEquals('Artic_Bus_Plans__c', postUpd.Artic_Bus_Plans__c);
        system.assertEquals('Electric_Bus_Plans__c', postUpd.Electric_Bus_Plans__c);
        system.assertEquals('Fleet_Performance__c', postUpd.Fleet_Performance_Updates__c);
        system.assertEquals('Fleet_Replacement_Plans__c', postUpd.Fleet_Replacement_Plans__c);
            
        test.stopTest();
    }
}