force-app/main/default/objects/Account/fields/Artic_Bus_Plans__c.field-meta.xml
<CustomField>
    <fullName>Artic_Bus_Plans__c</fullName>
    <description>Describe the customer&apos;s high-level Articulated Bus Plans</description>
    <label>Articulated Bus Plans</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_Probability__c.field-meta.xml
<CustomField>
    <fullName>Order_Probability__c</fullName>
    <label>Order Probability</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. High Probability</fullName>
            </value>
            <value>
                <fullName>2. Medium Probability</fullName>
            </value>
            <value>
                <fullName>3. Low Probability</fullName>
            </value>
            <value>
                <fullName>4. Unlikely</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip_Report__c/Trip_Report__c.object-meta.xml
<CustomObject>
    <label>Trip Report</label>
    <nameField>
        <label>Trip Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Report__c/fields/Artic_Bus_Plans__c.field-meta.xml
<CustomField>
    <fullName>Artic_Bus_Plans__c</fullName>
    <label>Articulated Bus Plans</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Date_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Visit__c</fullName>
    <label>Date of Visit</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TripReporttriggertest.cls
/***********************************************************************************************************************************
     Developer :Suyati
     Name      : TripReporttriggertest
     Associated Trigger:TripReportTrigger
     Date      : October 2019   
************************************************************************************************************************************/
@isTest
public class TripReporttriggertest {
/***********************************************************************************************************************************
     Method Name  : tripReport_test
************************************************************************************************************************************/  
    static testmethod void tripReport_test()
    {
        Account testAccount = TestDataFactory.createAccount();
        Trip_Report__c tripReport = TestDataFactory.createTripReport(testAccount.id);
        Opportunity opp = new Opportunity(Name='test opp',AccountId=testAccount.Id,StageName='Forecast',Type='Existing Business',Order_Probability__c = '1. High Probability',CloseDate=System.today());
        insert opp;
        tripReport.Artic_Bus_Plans__c = 'No 62 ft. bus interest';
        tripReport.Status__c = 'Final';
        tripReport.Date_of_Visit__c = System.today()-3;
        test.startTest();
        update tripReport;
        test.stopTest();
        Account queryAccount = [select id ,Artic_Bus_Plans__c from Account];
        system.assertEquals('No 62 ft. bus interest' , queryAccount.Artic_Bus_Plans__c);
    }
}