force-app/main/default/objects/Account/fields/ASW_ID__c.field-meta.xml
<CustomField>
    <fullName>ASW_ID__c</fullName>
    <externalId>true</externalId>
    <label>ASW ID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gillig_ID__c.field-meta.xml
<CustomField>
    <fullName>Gillig_ID__c</fullName>
    <externalId>true</externalId>
    <label>Gillig ID</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Option__c/Contract_Option__c.object-meta.xml
<CustomObject>
    <label>Contract Option</label>
    <nameField>
        <label>Options</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Option__c/fields/Customer_Contract__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contract__c</fullName>
    <label>Customer Contract</label>
    <referenceTo>Customer_Contract__c</referenceTo>
    <relationshipLabel>Member Agencies</relationshipLabel>
    <relationshipName>OptionContract</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Option__c/fields/Expiration__c.field-meta.xml
<CustomField>
    <fullName>Expiration__c</fullName>
    <formula>Customer_Contract__r.Expiration__c</formula>
    <label>Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Option__c/fields/Member_Agency__c.field-meta.xml
<CustomField>
    <fullName>Member_Agency__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Joint Procurements</relationshipLabel>
    <relationshipName>OptionAccount</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Option__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <label>Customer Contract Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Stage__c.field-meta.xml
<CustomField>
    <fullName>Bid_Stage__c</fullName>
    <label>Bid Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Specification Received</fullName>
            </value>
            <value>
                <fullName>Prepare Approved Equals</fullName>
            </value>
            <value>
                <fullName>Awaiting Approved Equals</fullName>
            </value>
            <value>
                <fullName>Prepare Bid</fullName>
            </value>
            <value>
                <fullName>Clarifications</fullName>
            </value>
            <value>
                <fullName>BAFO</fullName>
            </value>
            <value>
                <fullName>Awaiting Decision</fullName>
            </value>
            <value>
                <fullName>Intent to Award GILLIG</fullName>
            </value>
            <value>
                <fullName>Award GILLIG</fullName>
            </value>
            <value>
                <fullName>Award Competitor</fullName>
            </value>
            <value>
                <fullName>No-Bid</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Status__c.field-meta.xml
<CustomField>
    <fullName>Bid_Status__c</fullName>
    <label>Bid Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bid</fullName>
            </value>
            <value>
                <fullName>Reviewing</fullName>
            </value>
            <value>
                <fullName>No-Bid</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Submission_Type__c.field-meta.xml
<CustomField>
    <fullName>Bid_Submission_Type__c</fullName>
    <label>Bid Submission Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Mail In</fullName>
            </value>
            <value>
                <fullName>Mail In &amp; USB</fullName>
            </value>
            <value>
                <fullName>Mail In &amp; Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Expiration__c.field-meta.xml
<CustomField>
    <fullName>Expiration__c</fullName>
    <label>Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Lead_Agency__r.Internal_Name__c</formula>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Lead_Agency__c.field-meta.xml
<CustomField>
    <fullName>Lead_Agency__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lead Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/recordTypes/Expired.recordType-meta.xml
<RecordType>
    <fullName>Expired</fullName>
    <active>true</active>
    <description>Expired Contracts</description>
    <label>Expired</label>
</RecordType>

force-app/main/default/objects/Customer_Contract__c/recordTypes/GILLIG.recordType-meta.xml
<RecordType>
    <fullName>GILLIG</fullName>
    <active>true</active>
    <description>GILLIG Contract</description>
    <label>GILLIG</label>
</RecordType>

force-app/main/default/classes/listJointProcurementsTest.cls
@isTest (seeAllData=false)
public class listJointProcurementsTest {
    
    public static account tAccount;
    public static account cAccount;
    public static Customer_Contract__c tContract;
    public static Contract_Option__c tCoption;
    
    public static ID objId;
    public static ID tAcct;
    
    public static testmethod void init() {
        //to-do run test as Sales manager role
        cAccount = new account (Name='Test Main Contract Account', ASW_ID__c = 't1', Gillig_ID__c  = 1, Internal_Name__c ='iT1');
        insert cAccount;
        tAccount = new account (Name='Test Account', ASW_ID__c = 't2', Gillig_ID__c  = 2, Internal_Name__c ='iT2');
        insert tAccount;
        tAcct = tAccount.id;
    }
    
    // When all data is valid
    public static TestMethod void testJointProcurements () {
        init();
        
        // set up before test
        tContract = new Customer_Contract__c (Name='Test Contract', Lead_Agency__c = cAccount.Id, Expiration__c = system.today(),Bid_Status__c = 'Bid', Bid_Stage__c = 'Award GILLIG', Bid_Submission_Type__c = 'Email');
        insert tContract;
        tCoption = new Contract_Option__c (Member_Agency__c = tAccount.Id, Customer_Contract__c = tContract.Id, Quantity__c = 1);
        insert tCoption;
        objId = tAccount.Id;
        Test.startTest();
        
        listJointProcurements tJP = new listJointProcurements();
        tjp.objId = objid;
        tjp.getlistJointProcurements();
        system.debug(tJP);
        
        system.assertEquals(objId, tJP.objid);
        
        Test.stopTest();
        
    }
    
/*    public static TestMethod void testExpiredJointP () {
        init();
        
        //set up before test with expired contract
        tContract = new Customer_Contract__c (Name='Test Contract', Lead_Agency__c = cAccount.Id, Expiration__c = system.today()-1);
        insert tContract;
        tCoption = new Contract_Option__c (Member_Agency__c = tAccount.Id, Customer_Contract__c = tContract.Id, Quantity__c = 1);
        insert tCoption;
        objId = tAccount.Id;
        Test.startTest();
        
        listJointProcurements tJP = new listJointProcurements();
        tjp.objId = objid;
        tjp.getlistJointProcurements();
        system.debug('In expired contract test');
        system.debug(tJP);
        
        system.assertEquals(Null, tJP.objId);
        
        Test.stopTest();        
    }
*/    
}