force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Sales_Order__r.Account__r.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <formula>if( or(RecordType.Name =&quot;Delivered&quot;,RecordType.Name =&quot;Firm&quot;,RecordType.Name =&quot;In Service&quot;), text(Sales_Order__r.Mode__c) , 

IF(INCLUDES( Opportunity_Line__r.Mode__c , &quot;Diesel&quot;), &quot;Diesel&quot;, NULL)+ 
IF(INCLUDES( Opportunity_Line__r.Mode__c , &quot;CNG&quot;), &quot;CNG&quot;, NULL)  + 
IF(INCLUDES( Opportunity_Line__r.Mode__c , &quot;Allison Hybrid&quot;), &quot;Allison Hybrid&quot;, NULL)+ 
IF(INCLUDES( Opportunity_Line__r.Mode__c , &quot;BAE Hybrid&quot;), &quot;BAE Hybrid&quot;, NULL) + 
IF(INCLUDES( Opportunity_Line__r.Mode__c , &quot;Electric&quot;), &quot;Electric&quot;, NULL))</formula>
    <label>Mode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Opportunity_Line__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Line</label>
    <referenceTo>Opportunity_Line__c</referenceTo>
    <relationshipLabel>Buses</relationshipLabel>
    <relationshipName>Buses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/PO_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Date__c</fullName>
    <formula>Sales_Order__r.PO_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <formula>if(isblank( Sales_Order__c ), Current_Owner__r.Project_Sales_Manager__r.FirstName +&quot; &quot;+Current_Owner__r.Project_Sales_Manager__r.LastName, Sales_Order__r.Owner:User.FirstName + &apos; &apos; + Sales_Order__r.Owner:User.LastName)</formula>
    <label>Project Sales Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>if( or(RecordType.Name =&quot;Delivered&quot;,RecordType.Name =&quot;Firm&quot;,RecordType.Name =&quot;In Service&quot;),  Sales_Order__r.Quantity__c , Opportunity_Line__r.Quantity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <description>Holds Serial Number will be populated by the sales process</description>
    <label>Serial Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/recordTypes/Scheduled.recordType-meta.xml
<RecordType>
    <fullName>Scheduled</fullName>
    <active>true</active>
    <description>Opportunity line has serial number and start date</description>
    <label>Scheduled</label>
</RecordType>

force-app/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <label>Customer Contract Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Stage__c.field-meta.xml
<CustomField>
    <fullName>Bid_Stage__c</fullName>
    <label>Bid Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Specification Received</fullName>
            </value>
            <value>
                <fullName>Prepare Approved Equals</fullName>
            </value>
            <value>
                <fullName>Awaiting Approved Equals</fullName>
            </value>
            <value>
                <fullName>Prepare Bid</fullName>
            </value>
            <value>
                <fullName>Clarifications</fullName>
            </value>
            <value>
                <fullName>BAFO</fullName>
            </value>
            <value>
                <fullName>Awaiting Decision</fullName>
            </value>
            <value>
                <fullName>Intent to Award GILLIG</fullName>
            </value>
            <value>
                <fullName>Award GILLIG</fullName>
            </value>
            <value>
                <fullName>Award Competitor</fullName>
            </value>
            <value>
                <fullName>No-Bid</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Status__c.field-meta.xml
<CustomField>
    <fullName>Bid_Status__c</fullName>
    <label>Bid Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bid</fullName>
            </value>
            <value>
                <fullName>Reviewing</fullName>
            </value>
            <value>
                <fullName>No-Bid</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Submission_Type__c.field-meta.xml
<CustomField>
    <fullName>Bid_Submission_Type__c</fullName>
    <label>Bid Submission Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Mail In</fullName>
            </value>
            <value>
                <fullName>Mail In &amp; USB</fullName>
            </value>
            <value>
                <fullName>Mail In &amp; Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Lead_Agency__r.Internal_Name__c</formula>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Lead_Agency__c.field-meta.xml
<CustomField>
    <fullName>Lead_Agency__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lead Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Sales Manager Assigned to the Bid</description>
    <label>Project Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/recordTypes/GILLIG.recordType-meta.xml
<RecordType>
    <fullName>GILLIG</fullName>
    <active>true</active>
    <description>GILLIG Contract</description>
    <label>GILLIG</label>
</RecordType>

force-app/main/default/objects/Exception_Day__c/Exception_Day__c.object-meta.xml
<CustomObject>
    <label>Exception Day</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Day__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Holds working day vs holiday. BTW, working day provisioning is required for only Saturday or Sunday. Not for Mon-Fri</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Working Day</fullName>
            </value>
            <value>
                <fullName>Scheduled Week</fullName>
            </value>
            <value>
                <fullName>Default Slots Per Day</fullName>
            </value>
            <value>
                <fullName>Slots Per Week Constant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Account.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_Probability__c.field-meta.xml
<CustomField>
    <fullName>Order_Probability__c</fullName>
    <label>Order Probability</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. High Probability</fullName>
            </value>
            <value>
                <fullName>2. Medium Probability</fullName>
            </value>
            <value>
                <fullName>3. Low Probability</fullName>
            </value>
            <value>
                <fullName>4. Unlikely</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <formula>Account.Project_Sales_Manager__r.FirstName + &apos; &apos; +  Account.Project_Sales_Manager__r.LastName</formula>
    <label>Project Sales Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/Opportunity_Line__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line</label>
    <nameField>
        <label>Opportunity Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <description>Date bus booked into backlog</description>
    <inlineHelpText>When this field is completed, the bus is added to the production backlog and the Sales Order is Generated.</inlineHelpText>
    <label>Date Booked</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Opportunity_Line__r.Account.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>Allison Hybrid</fullName>
            </value>
            <value>
                <fullName>BAE Hybrid</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Trolley (Overhead)</fullName>
            </value>
            <value>
                <fullName>Glider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Opportunity_Line__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Lines</relationshipLabel>
    <relationshipName>Opportunity_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/PO_Amount__c.field-meta.xml
<CustomField>
    <fullName>PO_Amount__c</fullName>
    <label>PO Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/PO_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Date__c</fullName>
    <label>PO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <formula>Opportunity_Line__r.Account.Project_Sales_Manager__r.FirstName  + &apos; &apos; +   Opportunity_Line__r.Account.Project_Sales_Manager__r.LastName</formula>
    <label>Project Sales Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <description>Serial Number for First Bus</description>
    <label>Serial Number</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DisplayBoardBusPlacementHandlerTest.cls
@isTest
private with sharing class DisplayBoardBusPlacementHandlerTest {
	
	static Opportunity tOpportunity;
    static Customer_Contract__c cContract;
    static Account tAccount;
    static User rRep;
    static User pRep;
     
    static void init () { 
    	
    	DisplayBoardDataTest.initCustomMetaData( '01/01/2035');
        
    	User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

        system.runAs(thisUser) {
            Profile p = [SELECT Id FROM Profile WHERE Name='Regional Sales Manager'];
            rRep = new user(LastName = 'National Sales Rep', Username = 'NationalSales.User@example.com', Email = 'NationalSales.User@example.com', 
                        Alias = 'rRep', CommunityNickname = 'rRep', 
                        TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',
                       	EmailEncodingKey = 'ISO-8859-1', ProfileId = p.ID,
                       	LanguageLocaleKey = 'en_US');
            insert rRep;
            Profile pm = [SELECT Id FROM Profile WHERE Name='Project Sales Manager'];
            pRep = new user(LastName = 'Project Sales Rep', Username = 'ProjectSales.User@example.com', Email = 'ProjectSales.User@example.com', 
                        Alias = 'pRep', CommunityNickname = 'pRep', 
                        TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',
                       	EmailEncodingKey = 'ISO-8859-1', ProfileId = pm.ID,
                       	LanguageLocaleKey = 'en_US');
            insert pRep;
        }
        tAccount = new account(Name='Test Account', Owner = rRep, Internal_Name__c = 'test, st',
                             Project_Sales_Manager__c = pRep.Id);
        insert tAccount;
        
        tOpportunity = new opportunity (AccountID=tAccount.ID,Name='Test Opp',StageName='Forecast', 
                                                    Type = 'Existing Business',Order_Probability__c = '1. High Probability', 
                                                    CloseDate=system.today(), ownerid = rRep.Id);
        insert tOpportunity;
       
        recordtype rType = [select id from recordtype where Name = 'GILLIG' and SOBJECTTYPE = 'Customer_Contract__c' limit 1];

        cContract = new Customer_Contract__c (name = 'Test Contract', ownerid = rRep.Id, RecordTypeID = rType.ID,
                                                                  Lead_Agency__c = tAccount.Id, Project_Sales_Manager__c = pRep.Id,
                                                                  Bid_Status__c = 'Bid', Bid_Stage__c = 'Award GILLIG', Bid_Submission_Type__c = 'Email');
        insert cContract;
        
//        DisplayBoardDataTest.init(); 
    }
    
    // test future_holding buses placement.  on hold.... due to the question
    
    // test 2 slot bus in the process
   	@isTest
	static void testPlacementInUnScheduledWeekMultiSlotBus() {
		init();		
		// System.debug( 'testPlacementInUnScheduledWeek');
		// Given an exisitng Opportinity Line
        test.startTest();
        // Opportunity line list
        List<Opportunity_Line__c> tOppLine = new List<Opportunity_Line__c>();
        tOppLine.add(new Opportunity_Line__c (Opportunity_Line__c = tOpportunity.Id,
                                            Quantity__c = 4,
                                            Serial_Number__c = '123456',
                                            Date_Booked__c = system.today(), 
                                            Mode__c = 'Diesel',
                                            PO_Amount__c = 150, 
                                            PO_Date__c = system.today(), 
                                            PO_Reference__c = 'Test PO',
                                            Quoted_Price__c = 100, 
                                            Reference_Contract__c = cContract.Id,
                                            Style__c = 'LF',
                                            Length__c = '40',
                                            Start_Date__c = Date.newInstance( 2017, 01, 02)));
        insert tOppLine;

		// When the create fleet class is called
		// createFleet.insertFleet(tOppLine);
        // serialize.serializeBus(tOppLine);
        // createSO.insertSO(tOppLine); 
        
        List<Bus__c> buses = [ SELECT Id, Name, Slots__c, Start_Date__c, Slot_Index_In_Day__c, Week_Start_Date__c, is_Future_Holding__c FROM Bus__c];       
        system.assertEquals( buses.size(), 4);
        // Date startDate = Date.newInstance( 2017, 01, 02);
        Date startDate = Date.newInstance( 2035, 01, 01);
        For( Bus__C bus: buses) {
        	bus.Start_Date__c = startDate;
        	bus.Slot_Index_In_Day__c = -1;
        	bus.Week_Start_Date__c = startDate;
        }
        
        buses[0].Slots__c = 2;
        update buses;
        buses = [ SELECT Id, Name, Slots__c, Start_Date__c, Slot_Index_In_Day__c, Week_Start_Date__c, is_Future_Holding__c FROM Bus__c];       
        
        DisplayBoardBusPlacementHandler.initializeBusList( buses);
        DisplayBoardBusPlacementHandler.placeBusesInUnscheduledWeeks( startDate,
        																2,
        																buses);
        
        buses = [ SELECT Id, Name, Slots__c, Start_Date__c, Slot_Index_In_Day__c, Week_Start_Date__c FROM Bus__c ORDER BY Start_Date__c, Slot_Index_In_Day__c];       
        Integer i = 0;
        Integer weeksCount = 0;
        Date placedDate = DisplayBoardFunctions.getWeekStartDate( startDate);

		// validateBusesPlacement( buses[0], 0, Date.newInstance( 2017, 01, 02));       
		// validateBusesPlacement( buses[1], 2, Date.newInstance( 2017, 01, 02));       
		// validateBusesPlacement( buses[2], 0, Date.newInstance( 2017, 01, 09));       
		// validateBusesPlacement( buses[3], 1, Date.newInstance( 2017, 01, 09));       

		validateBusesPlacement( buses[0], 0, Date.newInstance( 2035, 01, 01));       
		validateBusesPlacement( buses[1], 2, Date.newInstance( 2035, 01, 01));       
		validateBusesPlacement( buses[2], 0, Date.newInstance( 2035, 01, 08));       
		validateBusesPlacement( buses[3], 1, Date.newInstance( 2035, 01, 08));       

        																
		test.stopTest();
	}
    // test future_holding skipping 
    
    @isTest
	static void testPlacementInUnScheduledWeekHoliday() {
		init();		
		// Given an exisitng Opportinity Line
        test.startTest();
        Exception_Day__c holiday1 = new Exception_Day__c( Name = 'Holiday Monday Week 04/10/2017',
//        													Exception_Date__c = Date.newInstance( 2017, 01, 02),
        													Exception_Date__c = Date.newInstance( 2035, 01, 01),
        													Type__c = 'Holiday'
        													);
        
        Insert holiday1;
  		DisplayBoardConstants.PLANT_DAYS.put( DisplayBoardConstants.plantDayKey( holiday1.Exception_Date__c, holiday1.Type__c), holiday1);
        
        // Opportunity line list
        List<Opportunity_Line__c> tOppLine = new List<Opportunity_Line__c>();
        tOppLine.add(new Opportunity_Line__c (Opportunity_Line__c = tOpportunity.Id,
                                            Quantity__c = 4,
                                            Serial_Number__c = '123456',
                                            Date_Booked__c = system.today(), 
                                            Mode__c = 'Diesel',
                                            PO_Amount__c = 150, 
                                            PO_Date__c = system.today(), 
                                            PO_Reference__c = 'Test PO',
                                            Quoted_Price__c = 100, 
                                            Reference_Contract__c = cContract.Id,
                                            Style__c = 'LF',
                                            Length__c = '40',
                                            Start_Date__c = Date.newInstance( 2035, 01, 01)));
        insert tOppLine;

		// When the create fleet class is called
		// createFleet.insertFleet(tOppLine);
        // serialize.serializeBus(tOppLine);
        // createSO.insertSO(tOppLine); 
        
        List<Bus__c> buses = [ SELECT Id, Name, Slots__c, Start_Date__c, Slot_Index_In_Day__c, Week_Start_Date__c FROM Bus__c];       
        system.assertEquals( buses.size(), 4);
//         Date startDate = Date.newInstance( 2017, 01, 02);
        Date startDate = Date.newInstance( 2035, 01, 01);
        For( Bus__C bus: buses) {
        	bus.Start_Date__c = startDate;
        	bus.Slot_Index_In_Day__c = -1;
        	bus.Week_Start_Date__c = startDate;
        }
        update buses;
        buses = [ SELECT Id, Name, Slots__c, Start_Date__c, Slot_Index_In_Day__c, Week_Start_Date__c, is_Future_Holding__c FROM Bus__c];       
        
        DisplayBoardBusPlacementHandler.initializeBusList( buses);
        DisplayBoardBusPlacementHandler.placeBusesInUnscheduledWeeks( startDate,
        																2,
        																buses);
        
        buses = [ SELECT Id, Name, Slots__c, Start_Date__c, Slot_Index_In_Day__c, Week_Start_Date__c FROM Bus__c ORDER BY Start_Date__c, Slot_Index_In_Day__c];       
        Integer i = 0;
        Integer weeksCount = 0;
        Date placedDate = DisplayBoardFunctions.getWeekStartDate( startDate);

/*
		validateBusesPlacement( buses[0], 7, Date.newInstance( 2017, 01, 02));       
		validateBusesPlacement( buses[1], 8, Date.newInstance( 2017, 01, 02));       
		validateBusesPlacement( buses[2], 0, Date.newInstance( 2017, 01, 09));       
		validateBusesPlacement( buses[3], 1, Date.newInstance( 2017, 01, 09));       
*/        																

		validateBusesPlacement( buses[0], 7, Date.newInstance( 2035, 01, 01));       
		validateBusesPlacement( buses[1], 8, Date.newInstance( 2035, 01, 01));       
		validateBusesPlacement( buses[2], 0, Date.newInstance( 2035, 01, 08));       
		validateBusesPlacement( buses[3], 1, Date.newInstance( 2035, 01, 08));       


		test.stopTest();
	}

	@isTest
	static void testPlacementInScheduledWeek() {
		init();		
		// Given an exisitng Opportinity Line
        test.startTest();
        
        /*
        String key = DisplayBoardConstants.plantDayKey( Date.newInstance( 2034, 12, 25), 'Scheduled Week');
        Exception_Day__c eDate = new Exception_Day__c( name='test', Type__c = 'Scheduled Week', Exception_Date__c = Date.newInstance( 2034, 12, 25));
        
        DisplayBoardConstants.PLANT_DAYS.put( key, eDate);
        */
      
        
        Exception_Day__c scheduledWeek1 = new Exception_Day__c( Name = 'Scheduled Week 04/10/2017',
//													Exception_Date__c = Date.newInstance( 2017, 01, 02),
													Exception_Date__c = Date.newInstance( 2035, 01, 01),
													Type__c = 'Scheduled Week'
													);
        Insert scheduledWeek1;
  		DisplayBoardConstants.PLANT_DAYS.put( DisplayBoardConstants.plantDayKey( scheduledWeek1.Exception_Date__c, scheduledWeek1.Type__c), scheduledWeek1);
        
        // Opportunity line list
        List<Opportunity_Line__c> tOppLine = new List<Opportunity_Line__c>();
        tOppLine.add(new Opportunity_Line__c (Opportunity_Line__c = tOpportunity.Id,
                                            Quantity__c = 4,
                                            Serial_Number__c = '123456',
                                            Date_Booked__c = system.today(), 
                                            Mode__c = 'Diesel',
                                            PO_Amount__c = 150, 
                                            PO_Date__c = system.today(), 
                                            PO_Reference__c = 'Test PO',
                                            Quoted_Price__c = 100, 
                                            Reference_Contract__c = cContract.Id,
                                            Style__c = 'LF',
                                            Length__c = '40',
                                            Start_Date__c = Date.newInstance( 2035, 01, 01)));
        insert tOppLine;

		// When the create fleet class is called
		// createFleet.insertFleet(tOppLine);
        // serialize.serializeBus(tOppLine);
        // createSO.insertSO(tOppLine); 
        
        List<Bus__c> buses = [ SELECT Id, Name, Slots__c, Start_Date__c, Slot_Index_In_Day__c, Week_Start_Date__c FROM Bus__c];       
        system.assertEquals( buses.size(), 4);
//        Date startDate = Date.newInstance( 2017, 01, 02);
        Date startDate = Date.newInstance( 2035, 01, 01);
        For( Bus__C bus: buses) {
        	bus.Start_Date__c = startDate;
        	bus.Slot_Index_In_Day__c = -1;
        	bus.Week_Start_Date__c = startDate;
        }
        
        update buses;
        buses = [ SELECT Id, Name, Slots__c, Start_Date__c, Slot_Index_In_Day__c, Week_Start_Date__c, is_Future_Holding__c FROM Bus__c];       
        
        // Date startDate = Date.newInstance( 2017, 01, 02);
        DisplayBoardBusPlacementHandler.initializeBusList( buses);
        DisplayBoardBusPlacementHandler.placeBusesInUnscheduledWeeks( startDate,
        																2,
        																buses);
        
        buses = [ SELECT Id, Name, Slots__c, Start_Date__c, Slot_Index_In_Day__c, Week_Start_Date__c FROM Bus__c ORDER BY Start_Date__c, Slot_Index_In_Day__c];       
        Integer i = 0;
        Integer weeksCount = 0;
        Date placedDate = DisplayBoardFunctions.getWeekStartDate( startDate);

/*
		validateBusesPlacement( buses[0], 0, Date.newInstance( 2017, 01, 09));       
		validateBusesPlacement( buses[1], 1, Date.newInstance( 2017, 01, 09));       
		validateBusesPlacement( buses[2], 0, Date.newInstance( 2017, 01, 16));       
		validateBusesPlacement( buses[3], 1, Date.newInstance( 2017, 01, 16));       
 */       																

		validateBusesPlacement( buses[0], 0, Date.newInstance( 2035, 01, 08));       
		validateBusesPlacement( buses[1], 1, Date.newInstance( 2035, 01, 08));       
		validateBusesPlacement( buses[2], 0, Date.newInstance( 2035, 01, 15));       
		validateBusesPlacement( buses[3], 1, Date.newInstance( 2035, 01, 15));       

		test.stopTest();
	}
	
	    @isTest
	static void testPlacementInUnScheduledWeek() {
		init();		
		// Given an exisitng Opportinity Line
        test.startTest();
        // Opportunity line list
        List<Opportunity_Line__c> tOppLine = new List<Opportunity_Line__c>();
        tOppLine.add(new Opportunity_Line__c (Opportunity_Line__c = tOpportunity.Id,
                                            Quantity__c = 4,
                                            Serial_Number__c = '123456',
                                            Date_Booked__c = system.today(), 
                                            Mode__c = 'Diesel',
                                            PO_Amount__c = 150, 
                                            PO_Date__c = system.today(), 
                                            PO_Reference__c = 'Test PO',
                                            Quoted_Price__c = 100, 
                                            Reference_Contract__c = cContract.Id,
                                            Style__c = 'LF',
                                            Length__c = '40',
                                            Start_Date__c = Date.newInstance( 2035, 01, 01)));
        insert tOppLine;

		// When the create fleet class is called
		// createFleet.insertFleet(tOppLine);
        // serialize.serializeBus(tOppLine);
        // createSO.insertSO(tOppLine); 
        
        List<Bus__c> buses = [ SELECT Id, Name, Slots__c, Start_Date__c, Slot_Index_In_Day__c, Week_Start_Date__c, is_Future_Holding__c FROM Bus__c];       
        system.assertEquals( buses.size(), 4);
//         Date startDate = Date.newInstance( 2017, 01, 02);
        Date startDate = Date.newInstance( 2035, 01, 01);
        For( Bus__C bus: buses) {
        	bus.Start_Date__c = startDate;
        	bus.Slot_Index_In_Day__c = -1;
        	bus.Week_Start_Date__c = startDate;
        }
        
        update buses;
        buses = [ SELECT Id, Name, Slots__c, Start_Date__c, Slot_Index_In_Day__c, Week_Start_Date__c, is_Future_Holding__c FROM Bus__c];       
        
        
        DisplayBoardBusPlacementHandler.initializeBusList( buses);
        DisplayBoardBusPlacementHandler.placeBusesInUnscheduledWeeks( startDate,
        																2,
        																buses);
        
        buses = [ SELECT Id, Name, Slots__c, Start_Date__c, Slot_Index_In_Day__c, Week_Start_Date__c FROM Bus__c ORDER BY Start_Date__c, Slot_Index_In_Day__c];       
        Integer i = 0;
        Integer weeksCount = 0;
        Date placedDate = DisplayBoardFunctions.getWeekStartDate( startDate);

/*
		validateBusesPlacement( buses[0], 0, Date.newInstance( 2017, 01, 02));       
		validateBusesPlacement( buses[1], 1, Date.newInstance( 2017, 01, 02));       
		validateBusesPlacement( buses[2], 0, Date.newInstance( 2017, 01, 09));       
		validateBusesPlacement( buses[3], 1, Date.newInstance( 2017, 01, 09));       
*/
		validateBusesPlacement( buses[0], 0, Date.newInstance( 2035, 01, 01));       
		validateBusesPlacement( buses[1], 1, Date.newInstance( 2035, 01, 01));       
		validateBusesPlacement( buses[2], 0, Date.newInstance( 2035, 01, 08));       
		validateBusesPlacement( buses[3], 1, Date.newInstance( 2035, 01, 08));       
        																
		test.stopTest();
	}
	
	@isTest
	static void testPlacementInUnScheduledWeekTEST() {
		System.debug( 'TEST METHOD');
		init();		
		// Given an exisitng Opportinity Line
        test.startTest();
        // Opportunity line list
        List<Opportunity_Line__c> tOppLine = new List<Opportunity_Line__c>();
        tOppLine.add(new Opportunity_Line__c (Opportunity_Line__c = tOpportunity.Id,
                                            Quantity__c = 4,
                                            Serial_Number__c = '123456',
                                            Date_Booked__c = system.today(), 
                                            Mode__c = 'Diesel',
                                            PO_Amount__c = 150, 
                                            PO_Date__c = system.today(), 
                                            PO_Reference__c = 'Test PO',
                                            Quoted_Price__c = 100, 
                                            Reference_Contract__c = cContract.Id,
                                            Style__c = 'LF',
                                            Length__c = '40',
                                            Start_Date__c = Date.newInstance( 2035, 01, 01)));
        insert tOppLine;

		// When the create fleet class is called
		// createFleet.insertFleet(tOppLine);
        // serialize.serializeBus(tOppLine);
        // createSO.insertSO(tOppLine); 
        
        List<Bus__c> buses = [ SELECT Id, Name, Slots__c, Start_Date__c, Slot_Index_In_Day__c, Week_Start_Date__c, is_Future_Holding__c FROM Bus__c];       
        system.assertEquals( buses.size(), 4);
 		System.debug( 'After Trigger update');
		For( Bus__c bus: buses) {
			System.debug( bus);
		} 
		
//		Date startDate = Date.newInstance( 2017, 01, 02);
		Date startDate = Date.newInstance( 2035, 01, 01);
        For( Bus__C bus: buses) {
        	bus.Start_Date__c = startDate;
        	bus.Slot_Index_In_Day__c = -1;
        	bus.Week_Start_Date__c = startDate;
        }
        
        update buses;
        buses = [ SELECT Id, Name, Slots__c, Start_Date__c, Slot_Index_In_Day__c, Week_Start_Date__c, is_Future_Holding__c FROM Bus__c];       
        System.debug( 'After resetting the data');
        For( Bus__c bus: buses) {
			System.debug( bus);
		} 
		
        DisplayBoardBusPlacementHandler.initializeBusList( buses);
        DisplayBoardBusPlacementHandler.placeBusesInUnscheduledWeeks( startDate,
        																2,
        																buses);
        
        buses = [ SELECT Id, Name, Slots__c, Start_Date__c, Slot_Index_In_Day__c, Week_Start_Date__c FROM Bus__c ORDER BY Start_Date__c, Slot_Index_In_Day__c];       
        Integer i = 0;
        Integer weeksCount = 0;
        Date placedDate = DisplayBoardFunctions.getWeekStartDate( startDate);

		For( Bus__c bus: buses) {
			System.debug( bus);
		} 

/*		
		validateBusesPlacement( buses[0], 0, Date.newInstance( 2017, 01, 02));       
		validateBusesPlacement( buses[1], 1, Date.newInstance( 2017, 01, 02));       
		validateBusesPlacement( buses[2], 0, Date.newInstance( 2017, 01, 09));       
		validateBusesPlacement( buses[3], 1, Date.newInstance( 2017, 01, 09));       
*/        																 
		validateBusesPlacement( buses[0], 0, Date.newInstance( 2035, 01, 01));       
		validateBusesPlacement( buses[1], 1, Date.newInstance( 2035, 01, 01));       
		validateBusesPlacement( buses[2], 0, Date.newInstance( 2035, 01, 08));       
		validateBusesPlacement( buses[3], 1, Date.newInstance( 2035, 01, 08));       
        																
		test.stopTest();
	}
	
	private static void validateBusesPlacement( Bus__c placedBus, Integer expectedSlotIndex, Date expectedStartDate ) {
		System.assertEquals( expectedSlotIndex, 
							 placedBus.Slot_Index_In_Day__c , 
							 expectedSlotIndex + ' = SlotIndex did not match' + placedBus);
		System.assertEquals( 	expectedStartDate, 
								placedBus.Start_Date__c,
								expectedStartDate + ' = expectedStartDate did not match' + placedBus );
	}
	
	
    
}