force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Sales_Order__r.Account__r.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Opportunity_Line__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Line</label>
    <referenceTo>Opportunity_Line__c</referenceTo>
    <relationshipLabel>Buses</relationshipLabel>
    <relationshipName>Buses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <formula>if(isblank( Sales_Order__c ), Current_Owner__r.Project_Sales_Manager__r.FirstName +&quot; &quot;+Current_Owner__r.Project_Sales_Manager__r.LastName, Sales_Order__r.Owner:User.FirstName + &apos; &apos; + Sales_Order__r.Owner:User.LastName)</formula>
    <label>Project Sales Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>if( or(RecordType.Name =&quot;Delivered&quot;,RecordType.Name =&quot;Firm&quot;,RecordType.Name =&quot;In Service&quot;),  Sales_Order__r.Quantity__c , Opportunity_Line__r.Quantity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <description>Holds Serial Number will be populated by the sales process</description>
    <label>Serial Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/recordTypes/Retired.recordType-meta.xml
<RecordType>
    <fullName>Retired</fullName>
    <active>true</active>
    <description>Bus has been retired from the fleet</description>
    <label>Retired</label>
</RecordType>

force-app/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <label>Customer Contract Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Stage__c.field-meta.xml
<CustomField>
    <fullName>Bid_Stage__c</fullName>
    <label>Bid Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Specification Received</fullName>
            </value>
            <value>
                <fullName>Prepare Approved Equals</fullName>
            </value>
            <value>
                <fullName>Awaiting Approved Equals</fullName>
            </value>
            <value>
                <fullName>Prepare Bid</fullName>
            </value>
            <value>
                <fullName>Clarifications</fullName>
            </value>
            <value>
                <fullName>BAFO</fullName>
            </value>
            <value>
                <fullName>Awaiting Decision</fullName>
            </value>
            <value>
                <fullName>Intent to Award GILLIG</fullName>
            </value>
            <value>
                <fullName>Award GILLIG</fullName>
            </value>
            <value>
                <fullName>Award Competitor</fullName>
            </value>
            <value>
                <fullName>No-Bid</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Status__c.field-meta.xml
<CustomField>
    <fullName>Bid_Status__c</fullName>
    <label>Bid Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bid</fullName>
            </value>
            <value>
                <fullName>Reviewing</fullName>
            </value>
            <value>
                <fullName>No-Bid</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Submission_Type__c.field-meta.xml
<CustomField>
    <fullName>Bid_Submission_Type__c</fullName>
    <label>Bid Submission Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Mail In</fullName>
            </value>
            <value>
                <fullName>Mail In &amp; USB</fullName>
            </value>
            <value>
                <fullName>Mail In &amp; Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Lead_Agency__r.Internal_Name__c</formula>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Lead_Agency__c.field-meta.xml
<CustomField>
    <fullName>Lead_Agency__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lead Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Sales Manager Assigned to the Bid</description>
    <label>Project Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/recordTypes/GILLIG.recordType-meta.xml
<RecordType>
    <fullName>GILLIG</fullName>
    <active>true</active>
    <description>GILLIG Contract</description>
    <label>GILLIG</label>
</RecordType>

force-app/main/default/objects/Fleet__c/Fleet__c.object-meta.xml
<CustomObject>
    <label>Fleet</label>
    <nameField>
        <label>Fleet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Fleet__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <label>Date Booked</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fleet__c/fields/Opportunity_Line__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Line</label>
    <referenceTo>Opportunity_Line__c</referenceTo>
    <relationshipLabel>Fleet</relationshipLabel>
    <relationshipName>Fleet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fleet__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>Active_Quantity_Competitor__c + Active_Quantity_GILLIG__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet__c/recordTypes/GILLIG.recordType-meta.xml
<RecordType>
    <fullName>GILLIG</fullName>
    <active>true</active>
    <description>Gillig Fleet Data</description>
    <label>GILLIG</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Account.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_Probability__c.field-meta.xml
<CustomField>
    <fullName>Order_Probability__c</fullName>
    <label>Order Probability</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. High Probability</fullName>
            </value>
            <value>
                <fullName>2. Medium Probability</fullName>
            </value>
            <value>
                <fullName>3. Low Probability</fullName>
            </value>
            <value>
                <fullName>4. Unlikely</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <formula>Account.Project_Sales_Manager__r.FirstName + &apos; &apos; +  Account.Project_Sales_Manager__r.LastName</formula>
    <label>Project Sales Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reference_Contract__c.field-meta.xml
<CustomField>
    <fullName>Reference_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Contract</label>
    <referenceTo>Customer_Contract__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/Opportunity_Line__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line</label>
    <nameField>
        <label>Opportunity Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <description>Date bus booked into backlog</description>
    <inlineHelpText>When this field is completed, the bus is added to the production backlog and the Sales Order is Generated.</inlineHelpText>
    <label>Date Booked</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Opportunity_Line__r.Account.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Opportunity_Line__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Lines</relationshipLabel>
    <relationshipName>Opportunity_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <formula>Opportunity_Line__r.Account.Project_Sales_Manager__r.FirstName  + &apos; &apos; +   Opportunity_Line__r.Account.Project_Sales_Manager__r.LastName</formula>
    <label>Project Sales Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Reference_Contract__c.field-meta.xml
<CustomField>
    <fullName>Reference_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Contract</label>
    <referenceTo>Customer_Contract__c</referenceTo>
    <relationshipLabel>Opportunity Lines</relationshipLabel>
    <relationshipName>Opportunity_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <description>Serial Number for First Bus</description>
    <label>Serial Number</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/recordTypes/Booked.recordType-meta.xml
<RecordType>
    <fullName>Booked</fullName>
    <active>false</active>
    <label>Booked</label>
</RecordType>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Account__r.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <summarizedField>Opportunity_Sales_Order__c.Quantity__c</summarizedField>
    <summaryForeignKey>Opportunity_Sales_Order__c.Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Reference_Contract__c.field-meta.xml
<CustomField>
    <fullName>Reference_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Contract</label>
    <referenceTo>Customer_Contract__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/retireFleetTest.cls
@istest (seeAlldata=false)
public class retireFleetTest {
    
    static List<Opportunity_Line__c> tOppLine;
    static Account tAccount;
    
    static void init() {
        
        User rRep;
        User pRep;
        
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

        system.runAs(thisUser) {
            Profile p = [SELECT Id FROM Profile WHERE Name='Regional Sales Manager'];
            rRep = new user(LastName = 'National Sales Rep', Username = 'NationalSales.User@example.com', Email = 'NationalSales.User@example.com', 
                        Alias = 'rRep', CommunityNickname = 'rRep', 
                        TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',
                       	EmailEncodingKey = 'ISO-8859-1', ProfileId = p.ID,
                       	LanguageLocaleKey = 'en_US');
            insert rRep;
            Profile pm = [SELECT Id FROM Profile WHERE Name='Project Sales Manager'];
            pRep = new user(LastName = 'Project Sales Rep', Username = 'ProjectSales.User@example.com', Email = 'ProjectSales.User@example.com', 
                        Alias = 'pRep', CommunityNickname = 'pRep', 
                        TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',
                       	EmailEncodingKey = 'ISO-8859-1', ProfileId = pm.ID,
                       	LanguageLocaleKey = 'en_US');
            insert pRep;
        }
        tAccount = new account(Name='Test Account', Owner = rRep, Project_Sales_Manager__c = pRep.Id, Internal_Name__c = 'test, st'
                             );
        insert tAccount;
        
        recordtype rType = [select id from recordtype where Name = 'GILLIG' and SOBJECTTYPE = 'Customer_Contract__c' limit 1];

        Customer_Contract__c cContract = new Customer_Contract__c (name = 'Test Contract', ownerid = rRep.Id, RecordTypeID = rType.ID,
                                                                  Lead_Agency__c = tAccount.Id, Project_Sales_Manager__c = pRep.Id,
                                                                  Bid_Status__c = 'Bid', Bid_Stage__c = 'Award GILLIG', Bid_Submission_Type__c = 'Email');
        insert cContract;

        opportunity tOpportunity = new opportunity (AccountID=tAccount.ID,Name='Test Opp',StageName='Forecast', Reference_Contract__c=cContract.id,
                                                    Type = 'Existing Business', Order_Probability__c = '1. High Probability',
                                                    CloseDate=system.today(), ownerid = rRep.Id);
        insert tOpportunity;
        
        tOppLine = new List<Opportunity_Line__c>();
        // Opportunity line with Date Booked when record created
        tOppLine.add(new Opportunity_Line__c (Opportunity_Line__c = tOpportunity.Id, 
                                            Quantity__c = 2,
                                            Serial_Number__c = '123456',
                                            Date_Booked__c = system.today(), 
                                            Mode__c = 'Diesel',
                                            PO_Amount__c = 150, 
                                            PO_Date__c = system.today(), 
                                            PO_Reference__c = 'Test PO',
                                            Quoted_Price__c = 100, 
                                            Reference_Contract__c = cContract.Id,
                                            Style__c = 'LF',
                                            Length__c = '40',
                                            Start_Date__c = system.today()));
        insert tOppLine;

    }

    static testmethod void retireFleet () {
        
        init();

        test.startTest();
        set<Id> toppId = new set<Id>();
        for (Opportunity_Line__c t:tOppLine) {
            toppId.add(t.Id);
        }
        List<Opportunity_Line__c> topp = [select Id, Fleet__c from Opportunity_Line__c where Id in :toppId];
        Fleet__c newFleet = [select Id, Name, OwnerId, RecordTypeID, Account__c, Length_GILLIG__c, Mode__c, Retired__c, Start_Date__c, Style_GILLIG__c 
                                     from Fleet__c where Id=:tOpp[0].Fleet__c];

        Fleet__c uFleet = [select id, Account__c, Retired__c from Fleet__c where Id=:newFleet.Id];
        uFleet.Retired__c = true;
        update uFleet;

        // check that the Fleet was retired
        Fleet__c resultingFleet = [select id, Account__c, Retired__c from Fleet__c where Id=:newFleet.Id];
        system.assertEquals(true, resultingFleet.Retired__c);

        // Check that the busses retired too
        List<Bus__c> resultingBus = [select ID, Name, Fleet__c, Sales_Order__c, Retired__c from Bus__c where Fleet__c = :resultingFleet.Id];

        for (Bus__c rBus:resultingBus) {
                    system.assertEquals(true, rBus.Retired__c);
        }
        test.stopTest();
    }
}