force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Option__c/Contract_Option__c.object-meta.xml
<CustomObject>
    <label>Contract Option</label>
    <nameField>
        <label>Options</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Option__c/fields/Customer_Contract__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contract__c</fullName>
    <label>Customer Contract</label>
    <referenceTo>Customer_Contract__c</referenceTo>
    <relationshipLabel>Member Agencies</relationshipLabel>
    <relationshipName>OptionContract</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Option__c/fields/Member_Agency__c.field-meta.xml
<CustomField>
    <fullName>Member_Agency__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Joint Procurements</relationshipLabel>
    <relationshipName>OptionAccount</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Option__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <label>Customer Contract Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Stage__c.field-meta.xml
<CustomField>
    <fullName>Bid_Stage__c</fullName>
    <label>Bid Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Specification Received</fullName>
            </value>
            <value>
                <fullName>Prepare Approved Equals</fullName>
            </value>
            <value>
                <fullName>Awaiting Approved Equals</fullName>
            </value>
            <value>
                <fullName>Prepare Bid</fullName>
            </value>
            <value>
                <fullName>Clarifications</fullName>
            </value>
            <value>
                <fullName>BAFO</fullName>
            </value>
            <value>
                <fullName>Awaiting Decision</fullName>
            </value>
            <value>
                <fullName>Intent to Award GILLIG</fullName>
            </value>
            <value>
                <fullName>Award GILLIG</fullName>
            </value>
            <value>
                <fullName>Award Competitor</fullName>
            </value>
            <value>
                <fullName>No-Bid</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Status__c.field-meta.xml
<CustomField>
    <fullName>Bid_Status__c</fullName>
    <label>Bid Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bid</fullName>
            </value>
            <value>
                <fullName>Reviewing</fullName>
            </value>
            <value>
                <fullName>No-Bid</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Submission_Type__c.field-meta.xml
<CustomField>
    <fullName>Bid_Submission_Type__c</fullName>
    <label>Bid Submission Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Mail In</fullName>
            </value>
            <value>
                <fullName>Mail In &amp; USB</fullName>
            </value>
            <value>
                <fullName>Mail In &amp; Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Lead_Agency__r.Internal_Name__c</formula>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Lead_Agency__c.field-meta.xml
<CustomField>
    <fullName>Lead_Agency__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lead Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Sales Manager Assigned to the Bid</description>
    <label>Project Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/recordTypes/GILLIG.recordType-meta.xml
<RecordType>
    <fullName>GILLIG</fullName>
    <active>true</active>
    <description>GILLIG Contract</description>
    <label>GILLIG</label>
</RecordType>

force-app/main/default/classes/defaultContractOptionNameTest.cls
@isTest (seealldata=false)
public class defaultContractOptionNameTest {
    
    static Customer_Contract__c cContract;
    static List<Contract_Option__c> memberContract;
    static set<string> cNames;

    static void init () {

        User rRep;
        User pRep;
        
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

        system.runAs(thisUser) {

            Profile p = [SELECT Id FROM Profile WHERE Name='Regional Sales Manager'];
            rRep = new user(LastName = 'National Sales Rep', Username = 'NationalSales.User@example.com', Email = 'NationalSales.User@example.com', 
                        Alias = 'rRep', CommunityNickname = 'rRep', 
                        TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',
                       	EmailEncodingKey = 'ISO-8859-1', ProfileId = p.ID,
                       	LanguageLocaleKey = 'en_US');
            insert rRep;
            Profile pm = [SELECT Id FROM Profile WHERE Name='Project Sales Manager'];
            pRep = new user(LastName = 'Project Sales Rep', Username = 'ProjectSales.User@example.com', Email = 'ProjectSales.User@example.com', 
                        Alias = 'pRep', CommunityNickname = 'pRep', 
                        TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',
                       	EmailEncodingKey = 'ISO-8859-1', ProfileId = pm.ID,
                       	LanguageLocaleKey = 'en_US');
            insert pRep;
        }       
        account tAccount = new account(Name='Test Account', Owner = rRep, Project_Sales_Manager__c = pRep.Id,
                             Internal_Name__c='Test Acct, St');
        insert tAccount;

        cNames = new set<string>();
        List<Account> mAccount = new List<Account>();
        for (integer a=0; a < 101; a++) {
        	mAccount.add(new account(Name='Test Member Account - '+a.format(), Owner = rRep, Project_Sales_Manager__c = pRep.Id,
                             Internal_Name__c='Mem Acct, St'+a.format()));
        	cNames.add('Test Contract - Mem Acct, St'+a.format());
        }
        insert mAccount;
       
        recordtype rType = [select id from recordtype where Name = 'GILLIG' and SOBJECTTYPE = 'Customer_Contract__c' limit 1];

        cContract = new Customer_Contract__c (name = 'Test Contract', ownerid = rRep.Id, RecordTypeID = rType.ID,
                                                                  Lead_Agency__c = tAccount.Id, Project_Sales_Manager__c = pRep.Id,
                                                                  Bid_Status__c = 'Bid', Bid_Stage__c = 'Award GILLIG', Bid_Submission_Type__c = 'Email');
        insert cContract;

		memberContract = new List<Contract_Option__c>();
        for (Integer i = 0; i < 101; i++) {
				memberContract.add(new Contract_Option__c(Member_Agency__c=mAccount[i].id, Customer_Contract__c=cContract.id,
        										Quantity__c = 1));
        }
        insert memberContract;
    }

    static testmethod void checkName () {
    	init();
    	List<Contract_Option__c> chkName = new List<Contract_Option__c>([select id, Name from Contract_Option__c where Customer_Contract__c = :cContract.ID]);

    	Test.startTest();

    	for (Contract_Option__c dName:chkName) {
    		system.assert(cNames.contains(dName.Name));
    	}

    	Test.stopTest();
    }
}