force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Option__c/Contract_Option__c.object-meta.xml
<CustomObject>
    <label>Contract Option</label>
    <nameField>
        <label>Options</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Option__c/fields/Customer_Contract__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contract__c</fullName>
    <label>Customer Contract</label>
    <referenceTo>Customer_Contract__c</referenceTo>
    <relationshipLabel>Member Agencies</relationshipLabel>
    <relationshipName>OptionContract</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Option__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <label>Customer Contract Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Stage__c.field-meta.xml
<CustomField>
    <fullName>Bid_Stage__c</fullName>
    <label>Bid Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Specification Received</fullName>
            </value>
            <value>
                <fullName>Prepare Approved Equals</fullName>
            </value>
            <value>
                <fullName>Awaiting Approved Equals</fullName>
            </value>
            <value>
                <fullName>Prepare Bid</fullName>
            </value>
            <value>
                <fullName>Clarifications</fullName>
            </value>
            <value>
                <fullName>BAFO</fullName>
            </value>
            <value>
                <fullName>Awaiting Decision</fullName>
            </value>
            <value>
                <fullName>Intent to Award GILLIG</fullName>
            </value>
            <value>
                <fullName>Award GILLIG</fullName>
            </value>
            <value>
                <fullName>Award Competitor</fullName>
            </value>
            <value>
                <fullName>No-Bid</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Status__c.field-meta.xml
<CustomField>
    <fullName>Bid_Status__c</fullName>
    <label>Bid Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bid</fullName>
            </value>
            <value>
                <fullName>Reviewing</fullName>
            </value>
            <value>
                <fullName>No-Bid</fullName>
            </value>
            <value>
                <fullName>Forecast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Bid_Submission_Type__c.field-meta.xml
<CustomField>
    <fullName>Bid_Submission_Type__c</fullName>
    <label>Bid Submission Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Mail In</fullName>
            </value>
            <value>
                <fullName>Mail In &amp; USB</fullName>
            </value>
            <value>
                <fullName>Mail In &amp; Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Lead_Agency__r.Internal_Name__c</formula>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Lead_Agency__c.field-meta.xml
<CustomField>
    <fullName>Lead_Agency__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lead Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Contracts</relationshipLabel>
    <relationshipName>Customer_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Sales Manager Assigned to the Bid</description>
    <label>Project Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/recordTypes/GILLIG.recordType-meta.xml
<RecordType>
    <fullName>GILLIG</fullName>
    <active>true</active>
    <description>GILLIG Contract</description>
    <label>GILLIG</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Account.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_Probability__c.field-meta.xml
<CustomField>
    <fullName>Order_Probability__c</fullName>
    <label>Order Probability</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. High Probability</fullName>
            </value>
            <value>
                <fullName>2. Medium Probability</fullName>
            </value>
            <value>
                <fullName>3. Low Probability</fullName>
            </value>
            <value>
                <fullName>4. Unlikely</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <formula>Account.Project_Sales_Manager__r.FirstName + &apos; &apos; +  Account.Project_Sales_Manager__r.LastName</formula>
    <label>Project Sales Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reference_Contract__c.field-meta.xml
<CustomField>
    <fullName>Reference_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Contract</label>
    <referenceTo>Customer_Contract__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/Opportunity_Line__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line</label>
    <nameField>
        <label>Opportunity Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Opportunity_Line__r.Account.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>Allison Hybrid</fullName>
            </value>
            <value>
                <fullName>BAE Hybrid</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Trolley (Overhead)</fullName>
            </value>
            <value>
                <fullName>Glider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Opportunity_Line__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Lines</relationshipLabel>
    <relationshipName>Opportunity_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Project_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Sales_Manager__c</fullName>
    <formula>Opportunity_Line__r.Account.Project_Sales_Manager__r.FirstName  + &apos; &apos; +   Opportunity_Line__r.Account.Project_Sales_Manager__r.LastName</formula>
    <label>Project Sales Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Reference_Contract__c.field-meta.xml
<CustomField>
    <fullName>Reference_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Contract</label>
    <referenceTo>Customer_Contract__c</referenceTo>
    <relationshipLabel>Opportunity Lines</relationshipLabel>
    <relationshipName>Opportunity_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Style__c.field-meta.xml
<CustomField>
    <fullName>Style__c</fullName>
    <label>Style</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low Floor</fullName>
            </value>
            <value>
                <fullName>Low Floor BRT</fullName>
            </value>
            <value>
                <fullName>Low Floor Plus</fullName>
            </value>
            <value>
                <fullName>BRT PLUS</fullName>
            </value>
            <value>
                <fullName>Trolley</fullName>
            </value>
            <value>
                <fullName>Double Decker</fullName>
            </value>
            <value>
                <fullName>Suburban</fullName>
                <label>SUBURBAN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Account__r.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CNG</fullName>
                <color>#CC6600</color>
                <label>CNG</label>
            </value>
            <value>
                <fullName>Diesel</fullName>
                <color>#3333FF</color>
                <label>Diesel</label>
            </value>
            <value>
                <fullName>Electric</fullName>
                <color>#6600CC</color>
                <label>Electric</label>
            </value>
            <value>
                <fullName>Allison Hybrid</fullName>
                <color>#CC9933</color>
                <label>Allison Hybrid</label>
            </value>
            <value>
                <fullName>BAE Hybrid</fullName>
                <color>#009900</color>
                <label>BAE Hybrid</label>
            </value>
            <value>
                <fullName>Trolley (Overhead)</fullName>
                <color>#FF0000</color>
                <label>Trolley (Overhead)</label>
            </value>
            <value>
                <fullName>Glider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <summarizedField>Opportunity_Sales_Order__c.Quantity__c</summarizedField>
    <summaryForeignKey>Opportunity_Sales_Order__c.Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Reference_Contract__c.field-meta.xml
<CustomField>
    <fullName>Reference_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Contract</label>
    <referenceTo>Customer_Contract__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestData.cls
@isTest
public class TestData

{
	public static Opportunity tOpportunity;
    public static Opportunity t29Opportunity;
    public static Customer_Contract__c cContract;
    public static Account tAccount;
    public static User rRep;
    public static User pRep;
    public static User sDir;
    public static User sAdmin;
    public static User cAdmin;
    public static List<Opportunity_Line__c> tOppLine;
    public static List<Opportunity_Line__c> t29OppLine;

   	public static void init () {

    	User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

        system.runAs(thisUser) {
            Profile p = [SELECT Id FROM Profile WHERE Name='Regional Sales Manager'];
            rRep = new user(LastName = 'National Sales Rep', Username = 'NationalSales.User@example.com', Email = 'NationalSales.User@example.com', 
                        Alias = 'rRep', CommunityNickname = 'rRep', 
                        TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',
                       	EmailEncodingKey = 'ISO-8859-1', ProfileId = p.ID,
                       	LanguageLocaleKey = 'en_US');
            insert rRep;
            Profile pm = [SELECT Id FROM Profile WHERE Name='Project Sales Manager'];
            pRep = new user(LastName = 'Project Sales Rep', Username = 'ProjectSales.User@example.com', Email = 'ProjectSales.User@example.com', 
                        Alias = 'pRep', CommunityNickname = 'pRep', 
                        TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',
                       	EmailEncodingKey = 'ISO-8859-1', ProfileId = pm.ID,
                       	LanguageLocaleKey = 'en_US');
            insert pRep;
            Profile sd = [SELECT Id FROM Profile WHERE Name='Sales Director'];
            sDir = new user(FirstName = 'Sales', LastName = 'Director', Username = 'Sales.Director@example.com', Email = 'Sales.Director@example.com', 
                        Alias = 'sDir', CommunityNickname = 'sDir', 
                        TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',
                       	EmailEncodingKey = 'ISO-8859-1', ProfileId = sd.ID,
                       	LanguageLocaleKey = 'en_US');
            insert sDir;       
            PermissionSet ps1 = [SELECT Id FROM PermissionSet WHERE Name = 'Test_Class_Fleet_Access'];
            insert new PermissionSetAssignment(AssigneeId = sDir.id, PermissionSetId = ps1.Id);         
            Profile sa = [SELECT Id FROM Profile WHERE Name='Sales Admin'];
            sAdmin = new user(FirstName = 'Sales', LastName = 'Admin', Username = 'Sales.Admin@example.com', Email = 'Sales.Admin@example.com', 
                        Alias = 'sAdm', CommunityNickname = 'sAdm', 
                        TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',
                       	EmailEncodingKey = 'ISO-8859-1', ProfileId = sa.ID,
                       	LanguageLocaleKey = 'en_US');
            insert sAdmin;
            PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Test_Class_Fleet_Access'];
            insert new PermissionSetAssignment(AssigneeId = sAdmin.id, PermissionSetId = ps.Id);      
            Profile ca = [SELECT Id FROM Profile WHERE Name='Sales Contract Admin'];
            cAdmin = new user(FirstName = 'Contract', LastName = 'Admin', Username = 'Contract.Admin@example.com', Email = 'Contract.Admin@example.com', 
                        Alias = 'cAdm', CommunityNickname = 'cAdm', 
                        TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',
                        EmailEncodingKey = 'ISO-8859-1', ProfileId = ca.ID,
                        LanguageLocaleKey = 'en_US');
            insert cAdmin;
        }
    }

    public static void createAcct() {
        system.runAs(rRep) {
            tAccount = new account(Name='Test Account', Internal_Name__c = 'test, st',
                             Project_Sales_Manager__c = pRep.Id);
            insert tAccount;            
        }
    }

    public static void createOpp() {
        system.runAs(rRep) {
            tOpportunity = new opportunity (AccountID=tAccount.ID,Name='Test Opp',StageName='Forecast', 
                                                    Type = 'Existing Business', Order_Probability__c = '1. High Probability',
                                                    CloseDate=system.today().addDays(45));
            insert tOpportunity;
            t29Opportunity = new opportunity (AccountID=tAccount.ID,Name='Test Opp29',StageName='Forecast', 
                                                    Type = 'Existing Business', Order_Probability__c = '1. High Probability',
                                                    CloseDate=system.today().addDays(45));
            insert t29Opportunity;

        }
    }

    public static void createContract() {
        manualShareRead(tAccount.Id, cAdmin.Id);
        system.runAs(cAdmin) {
            Schema.DescribeSObjectResult contractSchema = Schema.SObjectType.Customer_Contract__c;
            Map<String,Schema.RecordTypeInfo> contractMap = contractSchema.getRecordTypeInfosByName();

            Schema.RecordTypeInfo contractRecordType = contractMap.get('GILLIG');
            cContract = new Customer_Contract__c (name = 'Test Contract', RecordTypeID = contractRecordType.getRecordTypeId(),
                                                                  Lead_Agency__c = tAccount.Id, Project_Sales_Manager__c = pRep.Id,
                                                                  Bid_Status__c = 'Bid', Bid_Stage__c = 'Award GILLIG', Bid_Submission_Type__c = 'Email');
            insert cContract;
        }
    }

    public static void createOppLine(Integer n, Integer qty) {
        tOppLine = new List<Opportunity_Line__c>();
        t29OppLine = new List<Opportunity_Line__c>();

        system.runAs(rRep) {
            for (Integer i = 0; i < n; i++) {
                tOppLine.add(new Opportunity_Line__c (Name=TestData.tOpportunity.Name+' - '+String.valueOf(i+1),
                                            Opportunity_Line__c = TestData.tOpportunity.Id,
                                            Quantity__c = qty,
                                            Mode__c = 'Diesel',
                                            Reference_Contract__c = TestData.cContract.Id,
                                            Style__c = 'LF',
                                            Length__c = '40'));
                t29OppLine.add(new Opportunity_Line__c (Name=TestData.t29Opportunity.Name+' - '+String.valueOf(i+1),
                                            Opportunity_Line__c = TestData.t29Opportunity.Id,
                                            Quantity__c = qty,
                                            Mode__c = 'Diesel',
                                            Reference_Contract__c = TestData.cContract.Id,
                                            Style__c = 'LF',
                                            Length__c = '29'));

            }
            insert tOppLine;
            insert t29OppLine;
        }

        system.runAs(sAdmin) {

            for (Opportunity_Line__c t:tOppLine) {
                t.PO_Amount__c = 150;
                t.PO_Date__c = system.today();
                t.PO_Reference__c = 'Test PO';
                t.Quoted_Price__c = 100;
            }
            update tOppLine;
            for (Opportunity_Line__c t29:t29OppLine) {
                t29.PO_Amount__c = 150;
                t29.PO_Date__c = system.today();
                t29.PO_Reference__c = 'Test PO';
                t29.Quoted_Price__c = 100;
            }
            update t29OppLine;

        }
    }

    public static void createSO() {

        List<Opportunity_Line__c> tOpps = [select Id, Quantity__c, Start_Date__c, Serial_Number__c, Opportunity_Line__c, Mode__c, PO_Amount__c, PO_Date__c, PO_Reference__c, Quoted_Price__c, Style__c, Length__c, Contract_Option__c, Book_with_Sales_Order__c
                        from Opportunity_Line__c];
        Integer oppLineTotal=0;
        Integer     i = 1;
        system.runAs(sAdmin) {
            for (Opportunity_Line__c t:tOpps) {
                t.Serial_Number__c = String.valueOf(i*t.Quantity__c);
                t.Start_Date__c = system.today().addYears(2);
                oppLineTotal=oppLineTotal+(Integer)t.Quantity__c;
                i++;
            }
            update tOpps;
        }

        system.runAs(sDir) {
            for (Opportunity_Line__c ol:tOpps) {
                ol.Date_Booked__c = system.today();
            }
            update tOpps;
            createSO.insertSO(tOpps);
        }
    }

    public static void createProductionOrder() {
        List<Sales_Order__c> salesOrders = [select Id, Name, Start_Date__c from Sales_Order__c];

        createProductionOrder.insertProductionOrder(salesOrders);
    }
    public static void manualShareRead(Id recordId, Id userOrGroupId){
        AccountShare accShr  = new AccountShare();
        accShr.AccountId = recordId;
        accShr.UserOrGroupId = userOrGroupId;
        accShr.AccountAccessLevel = 'Read';
        accShr.OpportunityAccessLevel = 'Read';
        accShr.RowCause = Schema.AccountShare.RowCause.Manual;
        try{             
            insert accShr;             
        }catch(DMLException DMLe){ 
            system.debug('Caught DML Exception: '+DMle.getMessage()); 
        }
    }  
}