force-app/main/default/objects/Account/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <label>Internal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Customer Accounts</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Fleet__c.field-meta.xml
<CustomField>
    <fullName>Fleet__c</fullName>
    <label>Fleet</label>
    <referenceTo>Fleet__c</referenceTo>
    <relationshipLabel>Buses</relationshipLabel>
    <relationshipName>Buses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Sales_Order__r.Account__r.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Staging</fullName>
            </value>
            <value>
                <fullName>WIP</fullName>
            </value>
            <value>
                <fullName>Out Of Factory</fullName>
            </value>
            <value>
                <fullName>Ready Row</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Out for Test</fullName>
            </value>
            <value>
                <fullName>Altoona</fullName>
            </value>
            <value>
                <fullName>Road Test</fullName>
            </value>
            <value>
                <fullName>On Delivery</fullName>
            </value>
            <value>
                <fullName>Repair Shop</fullName>
            </value>
            <value>
                <fullName>PDI</fullName>
            </value>
            <value>
                <fullName>In Service</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <isActive>false</isActive>
                <label>Accepted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Transmission__c.field-meta.xml
<CustomField>
    <fullName>Transmission__c</fullName>
    <formula>text( Sales_Order__r.Transmission__c )</formula>
    <label>Transmission</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fleet__c/Fleet__c.object-meta.xml
<CustomObject>
    <label>Fleet</label>
    <nameField>
        <label>Fleet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Fleet__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fleet</relationshipLabel>
    <relationshipName>Fleet</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operation_Check_Master_Data__c/Operation_Check_Master_Data__c.object-meta.xml
<CustomObject>
    <description>This object captures the operation checks master data information.</description>
    <label>Operation Check Master Data</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Operation_Item_Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operation Check Master Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Operation_Check_Master_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Operation Check Master Data</relationshipLabel>
    <relationshipName>Operation_Check_Master_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Operation_Check_Master_Data__c/fields/Active_Date__c.field-meta.xml
<CustomField>
    <fullName>Active_Date__c</fullName>
    <description>Future date when this record becomes active</description>
    <label>Active Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Operation_Check_Master_Data__c/fields/Build_Station_ID__c.field-meta.xml
<CustomField>
    <fullName>Build_Station_ID__c</fullName>
    <label>Build Station ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operation_Check_Master_Data__c/fields/Bus_Mode__c.field-meta.xml
<CustomField>
    <fullName>Bus_Mode__c</fullName>
    <label>Bus Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mode</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation_Check_Master_Data__c/fields/Department_ID__c.field-meta.xml
<CustomField>
    <fullName>Department_ID__c</fullName>
    <label>Department ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Operation_Check_Master_Data__c/fields/Inactive_Date__c.field-meta.xml
<CustomField>
    <fullName>Inactive_Date__c</fullName>
    <description>Date this record is set to not active</description>
    <label>Inactive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Operation_Check_Master_Data__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field indicates whether the operation check item is still valid</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Operation_Check_Master_Data__c/fields/Operation_Description__c.field-meta.xml
<CustomField>
    <fullName>Operation_Description__c</fullName>
    <description>Converted text to rich text</description>
    <label>Operation Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Operation_Check_Master_Data__c/fields/Operation_Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Operation_Sequence_Number__c</fullName>
    <label>Operation Sequence Number</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Operation_Check_Master_Data__c/fields/Transmission__c.field-meta.xml
<CustomField>
    <fullName>Transmission__c</fullName>
    <label>Transmission</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transmission</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation_Check_Master_Data__c/fields/Value_Description__c.field-meta.xml
<CustomField>
    <fullName>Value_Description__c</fullName>
    <label>Value Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Operation_Check_Master_Data__c/fields/Value_Required_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Value_Required_Indicator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Value Required Indicator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Mode.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Diesel</fullName>
    </customValue>
    <customValue>
        <fullName>CNG</fullName>
    </customValue>
    <customValue>
        <fullName>Allison Hybrid</fullName>
    </customValue>
    <customValue>
        <fullName>BAE Hybrid</fullName>
    </customValue>
    <customValue>
        <fullName>Electric</fullName>
    </customValue>
    <customValue>
        <fullName>Fuel Cell</fullName>
    </customValue>
    <masterLabel>Mode</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpCkMasterDataController.cls
public with sharing class OpCkMasterDataController {
    @AuraEnabled
    public static List<Operation_Check_Master_Data__c> getOperationCheckList() {
        List<Operation_Check_Master_Data__c> opcklist = [SELECT Id, Name, Department_ID__c,RecordTypeId, Build_Station_ID__c, isActive__c, Operation_Description__c, Customer_Name__c, Value_Required_Indicator__c, Value_Description__c, Bus_Mode__c, Operation_Sequence_Number__c, Transmission__c, Account__r.Internal_Name__c,Account__c,Inactive_Date__c,Active_Date__c FROM Operation_Check_Master_Data__c ORDER BY Name asc];
        return opcklist;
    }
    
    // Getting record types from Operation check master data record Object
    @AuraEnabled(cacheable=true)
    public static List<RecordType> getRecordTypes() {
        return [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Operation_Check_Master_Data__c' ORDER BY Id ASC];
    }

    @AuraEnabled
    public static List<Account> getAllAccounts(){
        List<Account> accountlist = [SELECT Id, Name, Internal_Name__c from Account WHERE RecordType.Name = 'Customer'];
        return accountlist;
    }
    
    @AuraEnabled
    public static List<Bus__c> getAllBuslists(){
        List<Bus__c> buslist = [SELECT Id, Name, fleet__r.Name, fleet__r.Account__c, Fleet__r.Account__r.Name, Fleet__r.Account__r.Id,
                                Fleet__r.Account__r.Internal_Name__c FROM Bus__c WHERE Status__c in ('Staging','WIP','Out of Factory')];
        return buslist;
    }
    
    @AuraEnabled
    public static List<Bus__c> getBuslistbyAccount(String customer_internal_name){
        List<Bus__c> buslist = [SELECT Id, Name, fleet__r.Name, fleet__r.Account__c, Fleet__r.Account__r.Name , Fleet__r.Account__r.Id,
                                Fleet__r.Account__r.Internal_Name__c,Status__c FROM Bus__c where Fleet__r.Account__r.Internal_Name__c = :customer_internal_name and Status__c in ('Staging','WIP','Out of Factory')];
        return buslist;
    }
    
    // Newly added for the Serial number update for the SOld buses.
    @AuraEnabled(cacheable=true) 
    public static Bus__c gePageRecordId(String recordId) 
    { 
        return [SELECT Id, Name FROM Bus__c WHERE Id = :recordId]; 
    }
    
    // Getting Customer Name, Ecard Id, chassis NO from the APi 
    @AuraEnabled
    public static BusDetailsToupdateSerialNumber getBusDetails(String chassis_no){
        AuthorisationData.Token tokendata = userAuthentication.getAccesstoken();
        string endpoint = System.Label.EcardAppendpoint+'api/ecardbychassisno/';
        userAuthentication.ResponseWrapper statusresponse = userAuthentication.getData(endpoint+chassis_no, 'GET', tokendata.access_token, tokendata.refresh_token);
        System.debug('statusresponse :'+endpoint+chassis_no);
        BusDetailsToupdateSerialNumber log = new BusDetailsToupdateSerialNumber();
        if(statusresponse.isError){
            log.statusCode = statusresponse.statusCode;
            log.responsebody = statusresponse.responseBody;
            if(statusresponse.statusCode == '404'){
                log.isError = false;
            }
            else{
                log.isError = statusresponse.isError;
            }
        }
        else{
            log.isError = statusresponse.isError;
            log.statusCode = statusresponse.statusCode;
            log.responsebody = statusresponse.responseBody;
        }
        return log;
    }
    
    public class BusDetailsToupdateSerialNumber{
        @auraEnabled
        public boolean isError{get;set;}
        @auraEnabled
        public string responsebody{get;set;}
        @auraEnabled
        public string statusCode{get;set;}
    }
    
}