force-app/main/default/objects/Reason_Code__c/Reason_Code__c.object-meta.xml
<CustomObject>
    <label>Reason Code</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Reason Code Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reason Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reason_Code__c/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <label>Reason Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Not fitting</fullName>
            </value>
            <value>
                <fullName>Unknow</fullName>
            </value>
            <value>
                <fullName>Misplacement</fullName>
            </value>
            <value>
                <fullName>Leakage</fullName>
            </value>
            <value>
                <fullName>Mismatch Alignment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reason_Code__c/recordTypes/Reject.recordType-meta.xml
<RecordType>
    <fullName>Reject</fullName>
    <active>true</active>
    <label>Reject</label>
</RecordType>

force-app/main/default/objects/Reason_Code__c/recordTypes/Rework.recordType-meta.xml
<RecordType>
    <fullName>Rework</fullName>
    <active>true</active>
    <label>Rework</label>
</RecordType>

force-app/main/default/objects/Reject__c/Reject__c.object-meta.xml
<CustomObject>
    <label>Reject</label>
    <nameField>
        <label>Bus</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rejects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reject__c/fields/Ecard_Id__c.field-meta.xml
<CustomField>
    <fullName>Ecard_Id__c</fullName>
    <label>Ecard Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reject__c/fields/LastModifiedByEmployeeId__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedByEmployeeId__c</fullName>
    <label>LastModifiedByEmployeeId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reject__c/fields/Quantity_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Rejected__c</fullName>
    <label>Quantity Rejected</label>
    <precision>12</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reject__c/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <label>Reason Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reject__c/fields/Reject_Description__c.field-meta.xml
<CustomField>
    <fullName>Reject_Description__c</fullName>
    <label>Reject Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Rework__c/Rework__c.object-meta.xml
<CustomObject>
    <label>Rework</label>
    <nameField>
        <label>Bus</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reworks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rework__c/fields/Buildstation__c.field-meta.xml
<CustomField>
    <fullName>Buildstation__c</fullName>
    <label>Buildstation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rework__c/fields/Bus_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Bus_Part_Number__c</fullName>
    <label>Bus Part Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rework__c/fields/LastModifiedByEmployeeId__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedByEmployeeId__c</fullName>
    <label>LastModifiedByEmployeeId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rework__c/fields/Quantity_Reworked__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Reworked__c</fullName>
    <label>Quantity Reworked</label>
    <precision>12</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rework__c/fields/Rework_description__c.field-meta.xml
<CustomField>
    <fullName>Rework_description__c</fullName>
    <label>Rework description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Rework__c/fields/Reworked_to_part_number__c.field-meta.xml
<CustomField>
    <fullName>Reworked_to_part_number__c</fullName>
    <label>Reworked to part number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetRejectListTest.cls
@isTest
public class GetRejectListTest {
    @TestSetup 
    private static void createTestRejects() {
        List<Reject__c> testRejects = new List<Reject__c>();
        
        Reject__c reject1 = new Reject__c(
            Ecard_Id__c = '12345',
            Name = 'Reject 1',
            Buildstation__c = 'Station 1',
            Department__c = 'Department 2',
            Reject_Description__c = 'Description',
            Reason_Code__c = 'R_123',
            Quantity_Rejected__c = 5,
            Bus_Part_Number__c = 'P123',
            LastModifiedByEmployeeId__c = 'Emp123',
            Remarks__c = 'Testing purpose'
        );
        testRejects.add(reject1);
        
        Reject__c reject2 = new Reject__c(
            Ecard_Id__c = '12345',
            Name = 'Reject 2',
            Buildstation__c = 'Station 2',
            Department__c = 'Test Department',
            Reject_Description__c = 'Description',
            Reason_Code__c = 'R_367',
            Quantity_Rejected__c = 3.00,
            Bus_Part_Number__c = 'P0012'
        );
        testRejects.add(reject2);
        
        Reject__c reject3 = new Reject__c(
			Ecard_Id__c = '12511',
            Name = 'Reject 3',
            Buildstation__c = 'Station 2',
            Department__c = 'Test Department',
            Reject_Description__c = 'Description',
            Reason_Code__c = 'R_367',
            Quantity_Rejected__c = 3.00,
            Bus_Part_Number__c = 'P0012'
        );
        testRejects.add(reject3);
         List<Rework__c> testReworks = new List<Rework__c>();
        
        Rework__c rework1 = new Rework__c(
            Ecard_Id__c = '12345',
            Name = 'Rework 1',
            Buildstation__c = 'Station 1',
            Department__c = 'Department 1',
            Rework_description__c = 'Description',
            Reason_Code__c = 'R_123',
            Quantity_Reworked__c  = 5.00,
            Bus_Part_Number__c = 'P123',
            Reworked_to_part_number__c = 'P011',
            LastModifiedByEmployeeId__c = 'Emp_123'
        );
        testReworks.add(rework1);
        
         Rework__c rework2 = new Rework__c(
            Ecard_Id__c = '12345',
            Name = 'Rework 2',
            Buildstation__c = 'Station 1',
            Department__c = 'Department 2',
            Rework_description__c = 'Description',
            Reason_Code__c = 'R_123',
            Quantity_Reworked__c  = 5,
            Bus_Part_Number__c = 'P123',
            Reworked_to_part_number__c = 'P011'
        );
        testReworks.add(rework2);
         Rework__c rework3 = new Rework__c(
            Ecard_Id__c = '12345',
            Name = 'Rework 3',
            Buildstation__c = 'Station 1',
            Department__c = 'Department 2',
            Rework_description__c = 'Description',
            Reason_Code__c = 'R_123',
            Quantity_Reworked__c  = 5.00,
            Bus_Part_Number__c = 'P123',
            Reworked_to_part_number__c = 'P011'
        );
        testReworks.add(rework3);
      
        insert testRejects;
        insert testReworks;
         
    }
  
    
    @isTest
    static void testGetRejectData() {
        Test.startTest();
        List<GetRejectList.getDataWrapper> resultAllDepartments = GetRejectList.getRejectData('12345', 'ALL DEPARTMENTS');
        System.assertEquals(2, resultAllDepartments.size());        
        List<GetRejectList.getDataWrapper> resultDepartment = GetRejectList.getRejectData('12345', 'Test Department');        
        System.assertEquals(1, resultDepartment.size());
        Test.stopTest();
        }
      
    @isTest
    static void testGetReworkDataEcard() {
        Test.startTest();
        List<GetRejectList.getDataWrapper> resultAllDepartments = GetRejectList.getReworkDataEcard('12345', 'ALL DEPARTMENTS');
        System.assertEquals(3, resultAllDepartments.size());        
        List<GetRejectList.getDataWrapper> resultDepartment = GetRejectList.getReworkDataEcard('12345', 'Department 1');        
        System.assertEquals(1, resultDepartment.size());
        Test.stopTest();
        }
    @isTest
    static void testGetRejectCount() {
        Test.startTest();
        Integer rejectCount = GetRejectList.getRejectCount('12345');
        Test.stopTest();
        System.assertEquals(2, rejectCount);
    }
     @isTest
    static void testGetReworkCount() {
        Test.startTest();
        Integer reworkCount = GetRejectList.getReworkCount('12345');
        Test.stopTest();
        System.assertEquals(3, reworkCount);
    }
    
   @isTest
    static void testGetUpdateRecord() {
       Reject__c rejectToUpdate = [SELECT Id FROM Reject__c WHERE Name = 'Reject 1' LIMIT 1];

        Test.startTest();
        List<GetRejectList.getDataWrapper> resultUpdateRecords = GetRejectList.getUpdateRecord(rejectToUpdate.Id);
        Test.stopTest();
    //    System.assertEquals(3, resultRejectList.size());
        
    }
     @isTest
    static void testGetUpdateReworkRecord() {
       Rework__c reworkToUpdate = [SELECT Id FROM Rework__c WHERE Name = 'Rework 1' LIMIT 1];

        Test.startTest();
        List<GetRejectList.getDataWrapper> resultUpdateRecords = GetRejectList.getUpdateReworkRecord(reworkToUpdate.Id);
        Test.stopTest();
      System.assertEquals(1, resultUpdateRecords.size());
        
    }
    @isTest
    static void testUpdateReject() {
       Reject__c rejectToUpdate = [SELECT Id,Remarks__c,LastModifiedByEmployeeId__c,Quantity_Rejected__c
                                   FROM Reject__c WHERE Name = 'Reject 1' LIMIT 1];

        Test.startTest();
        String resultUpdateRejects = GetRejectList.updateReject(rejectToUpdate.Id,rejectToUpdate.Remarks__c,
                                                                                     (Integer)rejectToUpdate.Quantity_Rejected__c,rejectToUpdate.LastModifiedByEmployeeId__c);
        Test.stopTest();
    }
     @isTest
    static void testUpdateRework() {
       Rework__c reworkToUpdate = [SELECT Id,Quantity_Reworked__c,LastModifiedByEmployeeId__c 
                                   FROM Rework__c WHERE Name = 'Rework 1' LIMIT 1];

        Test.startTest();
        String resultUpdateRejects = GetRejectList.updateRework(reworkToUpdate.Id,(Integer)reworkToUpdate.Quantity_Reworked__c,reworkToUpdate.LastModifiedByEmployeeId__c,'','' );
        Test.stopTest();
    }
    @isTest
    static void testGetData() {
        Test.startTest();
        List<GetRejectList.getDataWrapper> resultRejectList = GetRejectList.getData();
        Test.stopTest();
        System.assertEquals(3, resultRejectList.size());
        
    }
     @isTest
    static void testGetReworkData() {
        Test.startTest();
        List<GetRejectList.getDataWrapper> resultRejectList = GetRejectList.getReworkData();
        Test.stopTest();
        System.assertEquals(3, resultRejectList.size());
        
    }
}