force-app/main/default/objects/Reason_Code__c/Reason_Code__c.object-meta.xml
<CustomObject>
    <label>Reason Code</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Reason Code Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reason Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reason_Code__c/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <label>Reason Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Not fitting</fullName>
            </value>
            <value>
                <fullName>Unknow</fullName>
            </value>
            <value>
                <fullName>Misplacement</fullName>
            </value>
            <value>
                <fullName>Leakage</fullName>
            </value>
            <value>
                <fullName>Mismatch Alignment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reason_Code__c/recordTypes/Reject.recordType-meta.xml
<RecordType>
    <fullName>Reject</fullName>
    <active>true</active>
    <label>Reject</label>
</RecordType>

force-app/main/default/objects/Reason_Code__c/recordTypes/Rework.recordType-meta.xml
<RecordType>
    <fullName>Rework</fullName>
    <active>true</active>
    <label>Rework</label>
</RecordType>

force-app/main/default/objects/Reject__c/Reject__c.object-meta.xml
<CustomObject>
    <label>Reject</label>
    <nameField>
        <label>Bus</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rejects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reject__c/fields/Buildstation_Id__c.field-meta.xml
<CustomField>
    <fullName>Buildstation_Id__c</fullName>
    <label>Buildstation Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reject__c/fields/Bus_Part_Id__c.field-meta.xml
<CustomField>
    <fullName>Bus_Part_Id__c</fullName>
    <label>Bus Part Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reject__c/fields/BuschasisNumber__c.field-meta.xml
<CustomField>
    <fullName>BuschasisNumber__c</fullName>
    <label>BuschasisNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reject__c/fields/Department_Id__c.field-meta.xml
<CustomField>
    <fullName>Department_Id__c</fullName>
    <label>Department Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reject__c/fields/Ecard_Id__c.field-meta.xml
<CustomField>
    <fullName>Ecard_Id__c</fullName>
    <label>Ecard Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reject__c/fields/LastModifiedByEmployeeId__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedByEmployeeId__c</fullName>
    <label>LastModifiedByEmployeeId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reject__c/fields/Quantity_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Rejected__c</fullName>
    <label>Quantity Rejected</label>
    <precision>12</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reject__c/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <label>Reason Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reject__c/fields/Reject_Description__c.field-meta.xml
<CustomField>
    <fullName>Reject_Description__c</fullName>
    <label>Reject Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Reject__c/fields/Rejected_by__c.field-meta.xml
<CustomField>
    <fullName>Rejected_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rejected by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Rejects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reject__c/fields/Rejected_By_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Rejected_By_Employee_Id__c</fullName>
    <label>Rejected By Employee Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reject__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Rework__c/Rework__c.object-meta.xml
<CustomObject>
    <label>Rework</label>
    <nameField>
        <label>Bus</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reworks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rework__c/fields/Buildstation__c.field-meta.xml
<CustomField>
    <fullName>Buildstation__c</fullName>
    <label>Buildstation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rework__c/fields/Buildstation_Id__c.field-meta.xml
<CustomField>
    <fullName>Buildstation_Id__c</fullName>
    <label>Buildstation Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rework__c/fields/Bus_Part_Id__c.field-meta.xml
<CustomField>
    <fullName>Bus_Part_Id__c</fullName>
    <label>Bus Part Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rework__c/fields/Bus_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Bus_Part_Number__c</fullName>
    <label>Bus Part Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rework__c/fields/Department_Id__c.field-meta.xml
<CustomField>
    <fullName>Department_Id__c</fullName>
    <label>Department Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rework__c/fields/LastModifiedByEmployeeId__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedByEmployeeId__c</fullName>
    <label>LastModifiedByEmployeeId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rework__c/fields/Quantity_Reworked__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Reworked__c</fullName>
    <label>Quantity Reworked</label>
    <precision>12</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rework__c/fields/Rework_description__c.field-meta.xml
<CustomField>
    <fullName>Rework_description__c</fullName>
    <label>Rework description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Rework__c/fields/Reworked_by__c.field-meta.xml
<CustomField>
    <fullName>Reworked_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reworked by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Reworks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rework__c/fields/Reworked_by_employee_id__c.field-meta.xml
<CustomField>
    <fullName>Reworked_by_employee_id__c</fullName>
    <label>Reworked by employee id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rework__c/fields/Reworked_to_part_number__c.field-meta.xml
<CustomField>
    <fullName>Reworked_to_part_number__c</fullName>
    <label>Reworked to part number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetRejectList.cls
public with sharing class GetRejectList {
    //Fetch records from Reject Object
     @AuraEnabled(cacheable=false)
   public static List<getDataWrapper> getRejectData(String ecardId, String dept) {
     List<User> usr = [select Id, Name,IsActive,EmployeeNumber from User where IsActive = true];
        List<Reject__c> rej = new List<Reject__c>();
            if(dept == 'ALL DEPARTMENTS'){
           rej = [SELECT Id,Ecard_Id__c,Name, Buildstation__c, Department__c, Reject_Description__c, Rejected_by__r.Name, 
                Reason_Code__c, Quantity_Rejected__c, Bus_Part_Number__c,CreatedDate,Rejected_By_Employee_Id__c FROM Reject__c WHERE Ecard_Id__c = :ecardId];
    }
        else{
        rej = [SELECT Id,Ecard_Id__c,Name, Buildstation__c, Department__c, Reject_Description__c, Rejected_by__r.Name, 
                Reason_Code__c, Quantity_Rejected__c, Bus_Part_Number__c,CreatedDate,Rejected_By_Employee_Id__c FROM Reject__c WHERE Ecard_Id__c = :ecardId AND Department__c =: dept];
    }
         
        List<getDataWrapper> gts = new List<getDataWrapper>();
        Map<String,String> emp = new Map<String,String>();
        for(User us : usr){
            emp.put(us.EmployeeNumber , us.Name);
        }
        for(Reject__c re : rej){
             getDataWrapper gt = new getDataWrapper();
            gt.Id = re.Id;
            gt.Ecard_Id = re.Ecard_Id__c;
            gt.Name = re.Name;
            gt.Buildstation = re.Buildstation__c;
            gt.Department = re.Department__c;
            gt.Reject_Description= re.Reject_Description__c;
            gt.Reason_Code = re.Reason_Code__c;
            gt.Quantity_Rejected = re.Quantity_Rejected__c;
            gt.Bus_Part_Number = re.Bus_Part_Number__c;
            gt.CreatedDate = re.CreatedDate;
            gt.UserName = emp.get(re.Rejected_By_Employee_Id__c);
             gt.Rejected_By_Employee_Id = re.Rejected_By_Employee_Id__c;
            gts.add(gt);
        }
        return gts;
    }
    
        
          //For rework records
   @AuraEnabled(cacheable=false)
   public static List<getDataWrapper> getReworkDataEcard(String ecardId, String dept) {
     List<User> usr = [select Id, Name,IsActive,EmployeeNumber from User where IsActive = true];
        List<Rework__c> rej = new List<Rework__c>();
            if(dept == 'ALL DEPARTMENTS'){
           		rej = [SELECT Id, Reworked_by__c,Name, Ecard_Id__c,CreatedDate,Department__c, Buildstation__c, Bus_Part_Number__c, 
                       Bus_Part_Id__c, Reworked_to_part_number__c, UUID__c, Rework_description__c, Reason_Code__c, 
                       Reworked_by_employee_id__c, Quantity_Reworked__c FROM Rework__c WHERE Ecard_Id__c = :ecardId];
            }
      		else{
       				rej = [SELECT Id, Reworked_by__c,Name, Ecard_Id__c,CreatedDate,Department__c, Buildstation__c, Bus_Part_Number__c, 
                           Bus_Part_Id__c, Reworked_to_part_number__c, UUID__c, Rework_description__c, Reason_Code__c,Quantity_Reworked__c, 
                           Reworked_by_employee_id__c  FROM Rework__c WHERE Ecard_Id__c = :ecardId AND Department__c =: dept];
   }
         
        List<getDataWrapper> gts = new List<getDataWrapper>();
        Map<String,String> emp = new Map<String,String>();
        for(User us : usr){
            emp.put(us.EmployeeNumber , us.Name);
        }
        for(Rework__c re : rej){
             getDataWrapper gt = new getDataWrapper();
            gt.Id = re.Id;
            gt.Ecard_Id = re.Ecard_Id__c;
            gt.Name = re.Name;
            gt.Buildstation = re.Buildstation__c;
            gt.Department = re.Department__c;
            gt.Reject_Description= re.Rework_description__c;
            gt.Reason_Code = re.Reason_Code__c;
            gt.Quantity_Rejected = re.Quantity_Reworked__c;
            gt.Bus_Part_Number = re.Bus_Part_Number__c;
            gt.CreatedDate = re.CreatedDate;
            gt.UserName = emp.get(re.Reworked_by_employee_id__c);
             gt.Rejected_By_Employee_Id = re.Reworked_by_employee_id__c;
            gt.Rework_Bus_Part_No = re.Reworked_to_part_number__c;
            system.debug(gt.Rework_Bus_Part_No);
            gts.add(gt);
        }
       system.debug(gts);
        return gts;
    }
     @AuraEnabled(cacheable=false)
    public static Integer getRejectCount(String ecardId) {
        return [SELECT COUNT() FROM Reject__c WHERE Ecard_Id__c = :ecardId];
    }
     @AuraEnabled(cacheable=true)
    public static List<getDataWrapper> getData() {
                List<User> usr = [select Id, Name,IsActive,EmployeeNumber from User where IsActive = true];
        List<Reject__c> rej = [SELECT Id,Ecard_Id__c,Name, Buildstation__c, Department__c, Reject_Description__c,BuschasisNumber__c, 
                                Reason_Code__c, Quantity_Rejected__c, Bus_Part_Number__c,Rejected_By_Employee_Id__c ,CreatedDate FROM Reject__c];
        
        List<getDataWrapper> gts = new List<getDataWrapper>();
        Map<String,String> emp = new Map<String,String>();
        for(User us : usr){
            emp.put(us.EmployeeNumber , us.Name);
        }
        for(Reject__c re : rej){
            getDataWrapper gt = new getDataWrapper();
            gt.Id = re.Id;
            gt.Ecard_Id = re.Ecard_Id__c;
            gt.Name = re.Name;
            gt.Buildstation = re.Buildstation__c;
            gt.Department = re.Department__c;
            gt.Reject_Description= re.Reject_Description__c;
            gt.BuschasisNumber = re.BuschasisNumber__c;
            gt.Reason_Code = re.Reason_Code__c;
            gt.Quantity_Rejected = re.Quantity_Rejected__c;
            gt.Bus_Part_Number = re.Bus_Part_Number__c;
            gt.CreatedDate = re.CreatedDate;
            gt.UserName = emp.get(re.Rejected_By_Employee_Id__c);
            gt.Rejected_By_Employee_Id = re.Rejected_By_Employee_Id__c;
            gts.add(gt);
        }
        return gts;
    }
    public class getDataWrapper{
        @AuraEnabled
        public String Id{get;set;}
                @AuraEnabled
        public String Ecard_Id{get;set;}
                @AuraEnabled
        public String Name{get;set;}
                @AuraEnabled
        public String Buildstation{get;set;}
                @AuraEnabled
        public String Department{get;set;}
                @AuraEnabled
        public String Reject_Description{get;set;}
                @AuraEnabled
        public String BuschasisNumber{get;set;}
                @AuraEnabled
        public String Reason_Code{get;set;}
                 @AuraEnabled
        public Decimal Quantity_Rejected{get;set;}
                 @AuraEnabled
        public String Bus_Part_Number{get;set;}
                 @AuraEnabled
        public Datetime CreatedDate{get;set;}
          @AuraEnabled
    public String Rework_Bus_Part_No{set;get;}
        
                 @AuraEnabled
        public String UserName{get;set;}
                @AuraEnabled
        public String Remark{get;set;}
                 @AuraEnabled
        public String Rejected_By_Employee_Id{get;set;}
      
    }
    @AuraEnabled(cacheable=false)
    public static Integer getReworkCount(String ecardId) {
        return [SELECT COUNT() FROM Rework__c WHERE Ecard_Id__c = :ecardId];
    }
@AuraEnabled
    public static List<getDataWrapper> getUpdateRecord(Id ids){
          List<User> usr = [select Id, Name,IsActive,EmployeeNumber from User where IsActive = true];
        List<Reject__c> rej = [SELECT Id,Ecard_Id__c,Name, Buildstation__c, Department__c, Reject_Description__c,BuschasisNumber__c, 
                                Reason_Code__c, Quantity_Rejected__c, Bus_Part_Number__c,Remarks__c,Rejected_By_Employee_Id__c ,CreatedDate FROM Reject__c where Id =: ids];
        
        List<getDataWrapper> gts = new List<getDataWrapper>();
        Map<String,String> emp = new Map<String,String>();
        for(User us : usr){
            emp.put(us.EmployeeNumber , us.Name);
        }
        for(Reject__c re : rej){
            getDataWrapper gt = new getDataWrapper();
            gt.Id = re.Id;
            gt.Ecard_Id = re.Ecard_Id__c;
            gt.Name = re.Name;
            gt.Buildstation = re.Buildstation__c;
            gt.Department = re.Department__c;
            gt.Reject_Description= re.Reject_Description__c;
            gt.BuschasisNumber = re.BuschasisNumber__c;
            gt.Reason_Code = re.Reason_Code__c;
            gt.Quantity_Rejected = re.Quantity_Rejected__c;
            gt.Bus_Part_Number = re.Bus_Part_Number__c;
            gt.CreatedDate = re.CreatedDate;
            gt.UserName = emp.get(re.Rejected_By_Employee_Id__c);
            gt.Remark = re.Remarks__c;
            gt.Rejected_By_Employee_Id = re.Rejected_By_Employee_Id__c;
            gts.add(gt);
        }
        return gts;
    }
   
@AuraEnabled
    public static string updateReject(Id recid,String remarks,Decimal quantity,String empId){
        try{
        Reject__c reje = new Reject__c();
        reje.Id = recid;
        reje.Remarks__c = remarks;
        reje.Quantity_Rejected__c = quantity;
        reje.LastModifiedByEmployeeId__c = empId;
        update reje;
        return 'Success';
        }catch(Exception e){
            return 'Failed';
        }
    }   
 @AuraEnabled(cacheable=true)
    public static List<getDataWrapper> getReworkData() {
                List<User> usr = [select Id, Name,IsActive,EmployeeNumber from User where IsActive = true];
        List<Rework__c> rej = [SELECT Id, Name, CreatedDate, Ecard_Id__c, Department__c, Department_Id__c, Buildstation__c, Buildstation_Id__c,
                               Reworked_by__c, Bus_Part_Number__c, Reworked_to_part_number__c, Rework_description__c, Reason_Code__c, Reworked_by_employee_id__c, Quantity_Reworked__c FROM Rework__c];
        
        List<getDataWrapper> gts = new List<getDataWrapper>();
        Map<String,String> emp = new Map<String,String>();
        for(User us : usr){
            emp.put(us.EmployeeNumber , us.Name);
        }
        for(Rework__c re : rej){
            getDataWrapper gt = new getDataWrapper();
            gt.Id = re.Id;
            gt.Ecard_Id = re.Ecard_Id__c;
            gt.Name = re.Name;
            gt.Buildstation = re.Buildstation__c;
            gt.Department = re.Department__c;
            gt.Reject_Description= re.Rework_description__c;
            gt.Reason_Code = re.Reason_Code__c;
            gt.Quantity_Rejected = re.Quantity_Reworked__c;
            gt.Bus_Part_Number = re.Bus_Part_Number__c;
            gt.CreatedDate = re.CreatedDate;
            gt.UserName = emp.get(re.Reworked_by_employee_id__c);
            gt.Rejected_By_Employee_Id = re.Reworked_by_employee_id__c;
            gt.Rework_Bus_Part_No = re.Reworked_to_part_number__c;
            gts.add(gt);
        }
        return gts;
    }
    @AuraEnabled
    public static List<getDataWrapper> getUpdateReworkRecord(Id ids){
          List<User> usr = [select Id, Name,IsActive,EmployeeNumber from User where IsActive = true];
        List<Rework__c> rej = [SELECT Id, Name, CreatedDate, Ecard_Id__c, Department__c, Department_Id__c, Buildstation__c, Buildstation_Id__c,
                               Reworked_by__c, Bus_Part_Number__c,Remarks__c, Reworked_to_part_number__c, Rework_description__c, Reason_Code__c, Reworked_by_employee_id__c, Quantity_Reworked__c FROM Rework__c where Id=:ids];
        
        List<getDataWrapper> gts = new List<getDataWrapper>();
        Map<String,String> emp = new Map<String,String>();
        for(User us : usr){
            emp.put(us.EmployeeNumber , us.Name);
        }
        for(Rework__c re : rej){
            getDataWrapper gt = new getDataWrapper();
            gt.Id = re.Id;
            gt.Ecard_Id = re.Ecard_Id__c;
            gt.Name = re.Name;
            gt.Buildstation = re.Buildstation__c;
            gt.Department = re.Department__c;
            gt.Reject_Description= re.Rework_description__c;
            gt.Reason_Code = re.Reason_Code__c;
            gt.Quantity_Rejected = re.Quantity_Reworked__c;
            gt.Bus_Part_Number = re.Bus_Part_Number__c;
            gt.CreatedDate = re.CreatedDate;
            gt.UserName = emp.get(re.Reworked_by_employee_id__c);
            gt.Rejected_By_Employee_Id = re.Reworked_by_employee_id__c;
            gt.Rework_Bus_Part_No = re.Reworked_to_part_number__c;
            gt.Remark = re.Remarks__c;
            gts.add(gt);
        }
        return gts;
    }
    @AuraEnabled
    public static string updateRework(String remark,Id recid,Decimal quantity,String empId,String reworkpart){
        try{
        Rework__c rewrk = new Rework__c();
        rewrk.Id = recid;
        rewrk.Quantity_Reworked__c = quantity;
        rewrk.Reworked_to_part_number__c = reworkpart; 
        rewrk.Remarks__c = remark;    
        rewrk.LastModifiedByEmployeeId__c = empId;
        update rewrk;
        return 'Success';
        }catch(Exception e){
            return 'Failed';
        }
    }   


}