force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Fleet__c.field-meta.xml
<CustomField>
    <fullName>Fleet__c</fullName>
    <label>Fleet</label>
    <referenceTo>Fleet__c</referenceTo>
    <relationshipLabel>Buses</relationshipLabel>
    <relationshipName>Buses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Sales_Order__r.Account__r.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <formula>if( or(RecordType.Name =&quot;Delivered&quot;,RecordType.Name =&quot;Firm&quot;,RecordType.Name =&quot;In Service&quot;), text(Sales_Order__r.Mode__c) , 

IF(INCLUDES( Opportunity_Line__r.Mode__c , &quot;Diesel&quot;), &quot;Diesel&quot;, NULL)+ 
IF(INCLUDES( Opportunity_Line__r.Mode__c , &quot;CNG&quot;), &quot;CNG&quot;, NULL)  + 
IF(INCLUDES( Opportunity_Line__r.Mode__c , &quot;Allison Hybrid&quot;), &quot;Allison Hybrid&quot;, NULL)+ 
IF(INCLUDES( Opportunity_Line__r.Mode__c , &quot;BAE Hybrid&quot;), &quot;BAE Hybrid&quot;, NULL) + 
IF(INCLUDES( Opportunity_Line__r.Mode__c , &quot;Electric&quot;), &quot;Electric&quot;, NULL))</formula>
    <label>Mode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Opportunity_Line__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Line</label>
    <referenceTo>Opportunity_Line__c</referenceTo>
    <relationshipLabel>Buses</relationshipLabel>
    <relationshipName>Buses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Retired__c.field-meta.xml
<CustomField>
    <fullName>Retired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <description>Holds Serial Number will be populated by the sales process</description>
    <label>Serial Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Style__c.field-meta.xml
<CustomField>
    <fullName>Style__c</fullName>
    <formula>if( or(RecordType.Name =&quot;Delivered&quot;,RecordType.Name =&quot;Firm&quot;,RecordType.Name =&quot;In Service&quot;), text(Sales_Order__r.Style__c) ,

IF(INCLUDES( Opportunity_Line__r.Style__c , &quot;Low Floor&quot;), &quot;Low Floor&quot;, NULL) +
IF(INCLUDES( Opportunity_Line__r.Style__c , &quot;Low Floor BRT&quot;), &quot;Low Floor BRT&quot;, NULL) +
IF(INCLUDES( Opportunity_Line__r.Style__c , &quot;Low Floor Plus&quot;), &quot;Low Floor Plus&quot;, NULL) +
IF(INCLUDES( Opportunity_Line__r.Style__c , &quot;BRT Plus&quot;), &quot;BRT Plus&quot;, NULL) +
IF(INCLUDES( Opportunity_Line__r.Style__c , &quot;Suburban&quot;), &quot;Suburban&quot;, NULL) +
IF(INCLUDES( Opportunity_Line__r.Style__c , &quot;Trolley&quot;), &quot;Trolley&quot;, NULL)
)</formula>
    <label>Style</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/recordTypes/Competitor.recordType-meta.xml
<RecordType>
    <fullName>Competitor</fullName>
    <active>true</active>
    <description>Competitor Bus</description>
    <label>Competitor</label>
</RecordType>

force-app/main/default/objects/Bus__c/recordTypes/Firm.recordType-meta.xml
<RecordType>
    <fullName>Firm</fullName>
    <active>true</active>
    <description>Sales order had been created</description>
    <label>Firm</label>
</RecordType>

force-app/main/default/objects/Bus__c/recordTypes/Reserved.recordType-meta.xml
<RecordType>
    <fullName>Reserved</fullName>
    <active>true</active>
    <description>Opportunity Line has a start date</description>
    <label>Reserved</label>
</RecordType>

force-app/main/default/objects/Bus__c/recordTypes/Scheduled.recordType-meta.xml
<RecordType>
    <fullName>Scheduled</fullName>
    <active>true</active>
    <description>Opportunity line has serial number and start date</description>
    <label>Scheduled</label>
</RecordType>

force-app/main/default/objects/Fleet__c/Fleet__c.object-meta.xml
<CustomObject>
    <label>Fleet</label>
    <nameField>
        <label>Fleet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Fleet__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fleet</relationshipLabel>
    <relationshipName>Fleet</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fleet__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <formula>if( RecordType.Name =&quot;Competitor&quot;, Length_Competitor__c, if(isblank( Sales_Order__c ), &quot;TBD&quot;,text( Sales_Order__r.Length__c )))</formula>
    <label>Length</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fleet__c/fields/Length_GILLIG__c.field-meta.xml
<CustomField>
    <fullName>Length_GILLIG__c</fullName>
    <label>Length (GILLIG)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fleet__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>DIESEL</fullName>
            </value>
            <value>
                <fullName>ELECTRIC</fullName>
            </value>
            <value>
                <fullName>HYBRID ALLISON</fullName>
            </value>
            <value>
                <fullName>HYBRID BAE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fleet__c/fields/Opportunity_Line__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Line</label>
    <referenceTo>Opportunity_Line__c</referenceTo>
    <relationshipLabel>Fleet</relationshipLabel>
    <relationshipName>Fleet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fleet__c/fields/Retired__c.field-meta.xml
<CustomField>
    <fullName>Retired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fleet__c/fields/Style__c.field-meta.xml
<CustomField>
    <fullName>Style__c</fullName>
    <formula>if( RecordType.Name =&quot;Competitor&quot;,Style_Competitor__c,if(isblank( Sales_Order__c ),&quot;TBD&quot;,text( Sales_Order__r.Style__c )))</formula>
    <label>Style</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fleet__c/fields/Style_GILLIG__c.field-meta.xml
<CustomField>
    <fullName>Style_GILLIG__c</fullName>
    <label>Style (GILLIG)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low Floor</fullName>
            </value>
            <value>
                <fullName>Low Floor BRT</fullName>
            </value>
            <value>
                <fullName>BRTPLUS</fullName>
            </value>
            <value>
                <fullName>Trolley</fullName>
            </value>
            <value>
                <fullName>Low Floor Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fleet__c/recordTypes/Competitor.recordType-meta.xml
<RecordType>
    <fullName>Competitor</fullName>
    <active>true</active>
    <description>Fleet information for Competitor Fleets</description>
    <label>Competitor</label>
</RecordType>

force-app/main/default/objects/Fleet__c/recordTypes/GILLIG.recordType-meta.xml
<RecordType>
    <fullName>GILLIG</fullName>
    <active>true</active>
    <description>Gillig Fleet Data</description>
    <label>GILLIG</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Account.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Options_Used__c.field-meta.xml
<CustomField>
    <fullName>Options_Used__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Options Used</label>
    <referenceTo>Contract_Option__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reference_Contract__c.field-meta.xml
<CustomField>
    <fullName>Reference_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Contract</label>
    <referenceTo>Customer_Contract__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Lines__c.field-meta.xml
<CustomField>
    <fullName>Total_Lines__c</fullName>
    <label>Total Lines</label>
    <summaryForeignKey>Opportunity_Line__c.Opportunity_Line__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Competitor.recordType-meta.xml
<RecordType>
    <fullName>Competitor</fullName>
    <active>true</active>
    <businessProcess>Competitor</businessProcess>
    <description>Competitor business we will not bid on</description>
    <label>Competitor</label>
</RecordType>

force-app/main/default/objects/Opportunity_Line__c/Opportunity_Line__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line</label>
    <nameField>
        <label>Opportunity Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Opportunity_Line__r.Account.Id</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Fleet__c.field-meta.xml
<CustomField>
    <fullName>Fleet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fleet</label>
    <referenceTo>Fleet__c</referenceTo>
    <relationshipLabel>Opportunity Lines</relationshipLabel>
    <relationshipName>Opportunity_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Internal_Name__c.field-meta.xml
<CustomField>
    <fullName>Internal_Name__c</fullName>
    <formula>Opportunity_Line__r.Account.Internal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>Allison Hybrid</fullName>
            </value>
            <value>
                <fullName>BAE Hybrid</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Trolley (Overhead)</fullName>
            </value>
            <value>
                <fullName>Glider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Opportunity_Line__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Lines</relationshipLabel>
    <relationshipName>Opportunity_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Reference_Contract__c.field-meta.xml
<CustomField>
    <fullName>Reference_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Contract</label>
    <referenceTo>Customer_Contract__c</referenceTo>
    <relationshipLabel>Opportunity Lines</relationshipLabel>
    <relationshipName>Opportunity_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <description>Serial Number for First Bus</description>
    <label>Serial Number</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date for First Bus</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/recordTypes/Serialized.recordType-meta.xml
<RecordType>
    <fullName>Serialized</fullName>
    <active>true</active>
    <description>Serial Number assigned</description>
    <label>Serialized</label>
</RecordType>

force-app/main/default/classes/Fleet.cls
public with sharing class Fleet {

	public static void deleteFleet(List<Fleet__c> delFleet) {
		delete delFleet;
		return;
	}

	public static Fleet__c create(Opportunity_Line__c opportunityline, Id oppAcct) {

		// Opportunity for this Line
//    	Opportunity allAccts = [select ID, Accountid, RecordTypeID, Reference_Contract__c, Name, Total_Lines__c, Options_Used__c from Opportunity where ID =:opportunityline.Opportunity_Line__c];

		Schema.DescribeSObjectResult fleetSchema = Schema.SObjectType.Fleet__c;
		Map<String,Schema.RecordTypeInfo> fleetMap = fleetSchema.getRecordTypeInfosByName();
		Schema.RecordTypeInfo fleetRecordType;

		fleetRecordType = fleetMap.get('Planned Build');
		Id plannedRecType = fleetRecordType.getRecordTypeId();

/*		Schema.DescribeSObjectResult opplSchema = Schema.SObjectType.Opportunity_Line__c;
		Map<String,Schema.RecordTypeInfo> opplMap = opplSchema.getRecordTypeInfosByName();
		Schema.RecordTypeInfo opplRecordType;
		opplRecordType = opplMap.get('Serialized');
		Id serializedRecType = opplRecordType.getRecordTypeId();
*/
		Schema.DescribeSObjectResult oppSchema = Schema.SObjectType.Opportunity;
		Map<String,Schema.RecordTypeInfo> oppMap = oppSchema.getRecordTypeInfosByName();
		Schema.RecordTypeInfo oppRecordType;

		oppRecordType = oppMap.get('Competitor');
		Id compRecType = oppRecordType.getRecordTypeId();

		Schema.DescribeSObjectResult busSchema = Schema.SObjectType.Bus__c;
		Map<String,Schema.RecordTypeInfo> busMap = busSchema.getRecordTypeInfosByName();
		Schema.RecordTypeInfo busRecordType;
		busRecordType = busMap.get('Firm');
		Id firmRecType = busRecordType.getRecordTypeId();
		busRecordType = busMap.get('To Be Scheduled');
    	Id tobescheduledRecType = busRecordType.getRecordTypeId();
		busRecordType = busMap.get('Scheduled');
    	Id scheduledRecType = busRecordType.getRecordTypeId();
    	busRecordType = busMap.get('Reserved');
    	Id reservedRecType = busRecordType.getRecordTypeId();

      	Fleet__c newFleet = new Fleet__c();

		if (opportunityline.RecordTypeID!=compRecType) {

      		boolean isFirm = bus.determineRecordType(opportunityline)==firmRecType;
      		boolean isScheduled = bus.determineRecordType(opportunityline)==scheduledRecType;
      		boolean isToBeScheduled = bus.determineRecordType(opportunityline)==tobescheduledRecType;
      		boolean isReserved = bus.determineRecordType(opportunityline)==reservedRecType;

      		String fName;


			if (isFirm || isReserved || isScheduled || isToBeScheduled) {
					newFleet.RecordTypeID=plannedRecType;
     				if (isFirm) {
     					newFleet.Name = 'GILLIG - ' + String.valueOf(opportunityline.Start_Date__c.year()) + ' ' + opportunityline.Length__c 
                                + ' ' + opportunityline.Mode__c;
  					} else if (isScheduled || isToBeScheduled) {
      					newFleet.Name = opportunityline.Serial_Number__c;
      				} else {
        				newFleet.Name = opportunityline.Internal_Name__c;
      				}
                    newFleet.Account__c=oppAcct;
                    newFleet.Length_GILLIG__c = opportunityline.Length__c;
                    newFleet.Mode__c= opportunityline.Mode__c;
                    newFleet.Retired__c = false;
                    newFleet.Style_GILLIG__c = opportunityline.Style__c;
                    newFleet.Start_Date__c=opportunityline.Start_Date__c;
                    newFleet.Opportunity_Line__c=opportunityline.Id;
    			}
      		}
  		
		return newFleet;
	}
}