force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Brakes__c.field-meta.xml
<CustomField>
    <fullName>Brakes__c</fullName>
    <formula>text( Sales_Order__r.Brakes__c )</formula>
    <label>Brakes</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Bus_Length__c.field-meta.xml
<CustomField>
    <fullName>Bus_Length__c</fullName>
    <formula>if( or(RecordType.Name =&quot;Delivered&quot;,RecordType.Name =&quot;Firm&quot;,RecordType.Name =&quot;In Service&quot;), text(Sales_Order__r.Length__c) , 

IF(INCLUDES( Opportunity_Line__r.Length__c , &quot;29&quot;), &quot;29&quot;, NULL) + 
IF(INCLUDES( Opportunity_Line__r.Length__c , &quot;35&quot;), &quot;35&quot;, NULL) + 
IF(INCLUDES( Opportunity_Line__r.Length__c , &quot;40&quot;), &quot;40&quot;, NULL)+ 
IF(INCLUDES( Opportunity_Line__r.Length__c , &quot;60&quot;), &quot;60&quot;, NULL))</formula>
    <label>Bus Length</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Engine__c.field-meta.xml
<CustomField>
    <fullName>Engine__c</fullName>
    <formula>text(Sales_Order__r.Engine__c)</formula>
    <label>Engine</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Green_Sheet_Date__c.field-meta.xml
<CustomField>
    <fullName>Green_Sheet_Date__c</fullName>
    <label>Green Sheet Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Buses</relationshipLabel>
    <relationshipName>Buses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/VIN__c.field-meta.xml
<CustomField>
    <fullName>VIN__c</fullName>
    <label>VIN</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Brakes__c.field-meta.xml
<CustomField>
    <fullName>Brakes__c</fullName>
    <label>Brakes</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Disc</fullName>
            </value>
            <value>
                <fullName>Drum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Engine__c.field-meta.xml
<CustomField>
    <fullName>Engine__c</fullName>
    <label>Engine</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mode__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Cummins L9 8.9 Liter</fullName>
            </value>
            <value>
                <fullName>Cummins L9N 8.9 Liter</fullName>
            </value>
            <value>
                <fullName>Cummins B6.7 6.7 Liter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>29</fullName>
                <color>#0B6FCE</color>
                <label>29</label>
            </value>
            <value>
                <fullName>35</fullName>
                <color>#78C953</color>
                <label>35</label>
            </value>
            <value>
                <fullName>40</fullName>
                <color>#E27001</color>
                <label>40</label>
            </value>
            <value>
                <fullName>60</fullName>
                <color>#A845DC</color>
                <label>60</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Letter_Code__c.field-meta.xml
<CustomField>
    <fullName>Letter_Code__c</fullName>
    <description>The Model or Line letter code used in the VIN</description>
    <inlineHelpText>E = Incomplete Vehicle
G = Low Floor Bus</inlineHelpText>
    <label>Letter Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <default>true</default>
                <label>G</label>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BusVinNumberTest.cls
@isTest
private class BusVinNumberTest {
    
    @testSetup static void init () {
        test.startTest();
        TestData.init();
        TestData.createAcct();
        TestData.createOpp();
        TestData.createContract();
        TestData.createOppLine(10, 10);
        TestData.createSO();
        test.stopTest();
    }

    @isTest
    static void itShouldNotGenerateVinforBusses() {
        
        test.startTest();        
        List<Sales_order__c> so = [select id,name from Sales_Order__c];     
        List<Bus__c> b = [select Id, Name, Sales_Order__c,Bus_Length__c, Engine__c,Sales_Order__r.Letter_Code__c,VIN__c,Brakes__c, Green_Sheet_Date__c from Bus__c];
        system.assertEquals(null, b[0].VIN__c);        
        test.stopTest();
        
    }
    
    @isTest
    static void itShouldUpdateVinNumofBusses1() {
        
        test.startTest();            
        List<Sales_order__c> so = [select id,name,Length__c,Engine__c,Brakes__c from Sales_Order__c order by id asc];
        List<Bus__c> b = [select Id, Name, Sales_Order__c,Bus_Length__c, Engine__c,Sales_Order__r.Letter_Code__c,VIN__c,Brakes__c, Green_Sheet_Date__c from Bus__c order by id asc];
        b[0].sales_order__c = so[0].Id;
        Date greenSheetDate = Date.newInstance(2022,07,21);
        b[0].Green_Sheet_Date__c = greenSheetDate.addYears(2);
        update b;
        
        so[0].Name = '197273';   
        so[0].Length__c = '29';
        so[0].Engine__c = 'Cummins L9N 8.9 Liter';
        so[0].Brakes__c = 'Disc';
        update so;
        
        List<Bus__c> ubus = [select Id, Name, Sales_Order__c,Bus_Length__c, Engine__c,Sales_Order__r.Letter_Code__c,VIN__c,Brakes__c, Green_Sheet_Date__c from Bus__c where sales_order__c =:so[0].Id ];
        system.assertEquals('15GGD3118R3197273', ubus[0].VIN__c);   
        
        ubus[0].Name = '96020';
        update ubus;
        
        List<Bus__c> upbus = [select Id, Name, Sales_Order__c,Bus_Length__c, Engine__c,Sales_Order__r.Letter_Code__c,VIN__c,Brakes__c, Green_Sheet_Date__c from Bus__c where sales_order__c =:so[0].Id ];
        system.assertEquals('15GGD3110R3096020', upbus[0].VIN__c); 
        
        test.stopTest();
        
    }
    
    @isTest
    static void itShouldUpdateVinNumofBusToNull1() {
        
        test.startTest();           
        List<Sales_order__c> so = [select id,name,Length__c,Engine__c,Brakes__c from Sales_Order__c order by id asc];
        List<Bus__c> b = [select Id, Name, Sales_Order__c,Bus_Length__c, Engine__c,Sales_Order__r.Letter_Code__c,VIN__c,Brakes__c, Green_Sheet_Date__c from Bus__c order by id asc];
        b[0].sales_order__c = so[0].Id;
        Date greenSheetDate = Date.newInstance(2022,07,21);
        b[0].Green_Sheet_Date__c = greenSheetDate.addYears(2);
        update b;
        
        so[0].Name = '197273';   
        so[0].Length__c = '29';
        so[0].Engine__c = 'Cummins L9N 8.9 Liter';
        so[0].Brakes__c = 'Disc';
        update so;
        
        List<Bus__c> ubus = [select Id, Name, Sales_Order__c,Bus_Length__c, Engine__c,Sales_Order__r.Letter_Code__c,VIN__c,Brakes__c, Green_Sheet_Date__c from Bus__c where sales_order__c =:so[0].Id ];
        system.assertEquals('15GGD3118R3197273', ubus[0].VIN__c);   
        
        ubus[0].Green_Sheet_Date__c = null;
        update ubus;
        
        List<Bus__c> upbus = [select Id, Name, Sales_Order__c,Bus_Length__c, Engine__c,Sales_Order__r.Letter_Code__c,VIN__c,Brakes__c, Green_Sheet_Date__c from Bus__c where sales_order__c =:so[0].Id ];
        system.assertEquals(null, upbus[0].VIN__c); 
        
        test.stopTest();
        
    }
    
    @isTest
    static void itShouldUpdateVinNumofBusses2() {
        
        test.startTest();            
        List<Sales_order__c> so = [select id,name,Length__c,Engine__c,Brakes__c from Sales_Order__c order by id asc];
        List<Bus__c> b = [select Id, Name, Sales_Order__c,Bus_Length__c, Engine__c,Sales_Order__r.Letter_Code__c,VIN__c,Brakes__c, Green_Sheet_Date__c from Bus__c order by id asc];
        b[0].sales_order__c = so[0].Id;
        Date greenSheetDate = Date.newInstance(2022,07,21);
        b[0].Green_Sheet_Date__c = greenSheetDate.addYears(2);
        update b;
        
        so[0].Name = '197273';
        so[0].Engine__c = 'Cummins L9N 8.9 Liter';
        so[0].Brakes__c = 'Disc';
        update so;
        
        List<Bus__c> ubus = [select Id, Name, Sales_Order__c,Bus_Length__c, Engine__c,Sales_Order__r.Letter_Code__c,VIN__c,Brakes__c, Green_Sheet_Date__c from Bus__c where sales_order__c =:so[0].Id ];
        system.assertEquals('15GGD3118R3197273', ubus[0].VIN__c);   
        
        Sales_Order__c uSo = [select id,name,Length__c,Engine__c,Brakes__c from Sales_Order__c where id=:so[0].Id];
        uSo.Name = '096854';
        uSo.Engine__c = 'Cummins B6.7 6.7 Liter';
        uSo.Brakes__c = 'Hydraulic';
        update uSo;
        
        List<Bus__c> upbus = [select Id, Name, Sales_Order__c,Bus_Length__c, Engine__c,Sales_Order__r.Letter_Code__c,VIN__c,Brakes__c, Green_Sheet_Date__c from Bus__c where sales_order__c =:so[0].Id ];
        system.assertEquals('15GGD3013R3096854', upbus[0].VIN__c);
        
        test.stopTest();
        
    }
    
    @isTest
    static void itShouldUpdateVinNumofBusToNull2() {
        
        test.startTest();           
        List<Sales_order__c> so = [select id,name,Length__c,Engine__c,Brakes__c from Sales_Order__c order by id asc];
        List<Bus__c> b = [select Id, Name, Sales_Order__c,Bus_Length__c, Engine__c,Sales_Order__r.Letter_Code__c,VIN__c,Brakes__c, Green_Sheet_Date__c from Bus__c order by id asc];
        b[0].sales_order__c = so[0].Id;
        Date greenSheetDate = Date.newInstance(2022,07,21);
        b[0].Green_Sheet_Date__c = greenSheetDate.addYears(2);
        update b;
        
        so[0].Name = '197273';   
        so[0].Length__c = '29';
        so[0].Engine__c = 'Cummins L9N 8.9 Liter';
        so[0].Brakes__c = 'Disc';
        update so;
        
        List<Bus__c> ubus = [select Id, Name, Sales_Order__c,Bus_Length__c, Engine__c,Sales_Order__r.Letter_Code__c,VIN__c,Brakes__c, Green_Sheet_Date__c from Bus__c where sales_order__c =:so[0].Id ];
        system.assertEquals('15GGD3118R3197273', ubus[0].VIN__c);   
        
        Sales_Order__c uSo = [select id,name,Length__c,Engine__c,Brakes__c from Sales_Order__c where id=:so[0].Id];
        uSo.Engine__c = null;
        update uSo;
        
        List<Bus__c> upbus = [select Id, Name, Sales_Order__c,Bus_Length__c, Engine__c,Sales_Order__r.Letter_Code__c,VIN__c,Brakes__c, Green_Sheet_Date__c from Bus__c where sales_order__c =:uSo.Id ];
        system.assertEquals(null, upbus[0].VIN__c); 
        
        test.stopTest();
        
    } 
}