force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Production_Order__c.field-meta.xml
<CustomField>
    <fullName>Production_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Order</label>
    <referenceTo>Production_Order__c</referenceTo>
    <relationshipLabel>Buses</relationshipLabel>
    <relationshipName>Buses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Production_Order_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Production_Order_Sequence__c</fullName>
    <label>Production Order Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>if( or(RecordType.Name =&quot;Delivered&quot;,RecordType.Name =&quot;Firm&quot;,RecordType.Name =&quot;In Service&quot;),  Sales_Order__r.Quantity__c , Opportunity_Line__r.Quantity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Buses</relationshipLabel>
    <relationshipName>Buses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sales Order Sequence</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Production_Order__c/Production_Order__c.object-meta.xml
<CustomObject>
    <label>Production Order</label>
    <nameField>
        <label>Production Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Production_Order__c/fields/Bus__c.field-meta.xml
<CustomField>
    <fullName>Bus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden Bus Lookup field to get the start date of the first bus in the current schedule date field</description>
    <label>Bus</label>
    <referenceTo>Bus__c</referenceTo>
    <relationshipLabel>Production Orders</relationshipLabel>
    <relationshipName>Production_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Production_Order__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Production_Order__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Production Orders</relationshipLabel>
    <relationshipName>Production_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <summarizedField>Opportunity_Sales_Order__c.Quantity__c</summarizedField>
    <summaryForeignKey>Opportunity_Sales_Order__c.Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Release_Order__c.field-meta.xml
<CustomField>
    <fullName>Release_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox that when clicked sends notification email, logs date and then un-checks checkbox</description>
    <label>Release Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date for initial bus</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/createProductionOrderTest.cls
@isTest
private class createProductionOrderTest
{
   	@testSetup static void init () {
        TestData.init();
        TestData.createAcct();
        TestData.createOpp();
        TestData.createContract();
        TestData.createOppLine(5, 5); //(10,10)
        TestData.createSO();
    }

	@isTest
	static void itShouldcreateProductionOrder()
	{
		// Given a sales order

		List<Sales_Order__c> sorders = new List<Sales_Order__c>([select Id, Name, Release_Order__c from Sales_Order__c]);

		// When the release date is set
		for (Sales_Order__c thisSO:sorders) {
			thisSO.Release_Order__c = true;
		}
		update sorders;
		TestData.createProductionOrder();

		// Then a production order should be created

		List<Production_Order__c> pOrders = new List<Production_Order__c>([select Id, Name, Sales_Order__c, Start_Date__c, Quantity__c from Production_Order__c]);
		system.assertNotEquals(0, pOrders.size());

		List<Bus__c> busses = new List<Bus__c>([select Id, Name, Sales_Order__c, Production_Order__c, Production_Order_Sequence__c, Start_Date__c, Sequence__c from Bus__c order by Name]);
		system.assertNotEquals(0, busses.size());

		Integer prodOrderSeq=1;
		Id prodOrder;


		for (Bus__c thisbus:busses) {
			if (thisbus.Production_Order__c!=prodOrder) {
				prodOrderSeq=1;
				prodOrder=thisbus.Production_Order__c;
			} else {
				prodOrderSeq++;
			}

			// Production order sequence should be set

			system.assertEquals(prodOrderSeq, thisbus.Production_Order_Sequence__c);
			for (Production_Order__c thisProdO:pOrders) {
				if (thisbus.Sales_Order__c == thisProdO.Sales_Order__c) {
					// Each of the busses for the Sales Order should have a matching Production Order
					system.assertEquals(thisbus.Production_Order__c, thisProdO.Id);
					system.assertNotEquals(Null, thisProdO.Start_Date__c);
					break;
				}
			}
		}

		Integer busQty=0;
		date sDate = Null;
		for (Production_Order__c thisProdO:pOrders) {
			for (Bus__c thisbus:busses) {
				if (thisbus.Production_Order__c==thisProdO.Id) {
					busQty++;
					if (thisbus.Sequence__c==1) {
						sDate=thisbus.Start_Date__c;
					}
				}
			}
//			system.assertEquals(sDate,thisProdO.Start_Date__c);
			system.assertEquals(busQty,thisProdO.Quantity__c);
			sDate=Null;
			busQty=0;
		}
	}
}