force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Engine__c.field-meta.xml
<CustomField>
    <fullName>Engine__c</fullName>
    <formula>text(Sales_Order__r.Engine__c)</formula>
    <label>Engine</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <formula>if( or(RecordType.Name =&quot;Delivered&quot;,RecordType.Name =&quot;Firm&quot;,RecordType.Name =&quot;In Service&quot;), text(Sales_Order__r.Mode__c) , 

IF(INCLUDES( Opportunity_Line__r.Mode__c , &quot;Diesel&quot;), &quot;Diesel&quot;, NULL)+ 
IF(INCLUDES( Opportunity_Line__r.Mode__c , &quot;CNG&quot;), &quot;CNG&quot;, NULL)  + 
IF(INCLUDES( Opportunity_Line__r.Mode__c , &quot;Allison Hybrid&quot;), &quot;Allison Hybrid&quot;, NULL)+ 
IF(INCLUDES( Opportunity_Line__r.Mode__c , &quot;BAE Hybrid&quot;), &quot;BAE Hybrid&quot;, NULL) + 
IF(INCLUDES( Opportunity_Line__r.Mode__c , &quot;Electric&quot;), &quot;Electric&quot;, NULL))</formula>
    <label>Mode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Opportunity_Line__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Line</label>
    <referenceTo>Opportunity_Line__c</referenceTo>
    <relationshipLabel>Buses</relationshipLabel>
    <relationshipName>Buses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>if( or(RecordType.Name =&quot;Delivered&quot;,RecordType.Name =&quot;Firm&quot;,RecordType.Name =&quot;In Service&quot;),  Sales_Order__r.Quantity__c , Opportunity_Line__r.Quantity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Buses</relationshipLabel>
    <relationshipName>Buses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/Opportunity_Line__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line</label>
    <nameField>
        <label>Opportunity Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>Allison Hybrid</fullName>
            </value>
            <value>
                <fullName>BAE Hybrid</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Trolley (Overhead)</fullName>
            </value>
            <value>
                <fullName>Glider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Opportunity_Line__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Lines</relationshipLabel>
    <relationshipName>Opportunity_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Sales_Order__c/Opportunity_Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Opportunity Sales Order</label>
    <nameField>
        <label>Opportunity Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Sales Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Sales_Order__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <formula>TEXT(Sales_Order__r.Length__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Length</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Sales_Order__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <formula>TEXT( Sales_Order__r.Mode__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Sales_Order__c/fields/Opportunity_Line__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line__c</fullName>
    <label>Opportunity Line</label>
    <referenceTo>Opportunity_Line__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Order</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Sales_Order__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Opportunity Lines</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Engine__c.field-meta.xml
<CustomField>
    <fullName>Engine__c</fullName>
    <label>Engine</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mode__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Cummins L9 8.9 Liter</fullName>
            </value>
            <value>
                <fullName>Cummins L9N 8.9 Liter</fullName>
            </value>
            <value>
                <fullName>Cummins B6.7 6.7 Liter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>29</fullName>
                <color>#0B6FCE</color>
                <label>29</label>
            </value>
            <value>
                <fullName>35</fullName>
                <color>#78C953</color>
                <label>35</label>
            </value>
            <value>
                <fullName>40</fullName>
                <color>#E27001</color>
                <label>40</label>
            </value>
            <value>
                <fullName>60</fullName>
                <color>#A845DC</color>
                <label>60</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Letter_Code__c.field-meta.xml
<CustomField>
    <fullName>Letter_Code__c</fullName>
    <description>The Model or Line letter code used in the VIN</description>
    <inlineHelpText>E = Incomplete Vehicle
G = Low Floor Bus</inlineHelpText>
    <label>Letter Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <default>true</default>
                <label>G</label>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CNG</fullName>
                <color>#CC6600</color>
                <label>CNG</label>
            </value>
            <value>
                <fullName>Diesel</fullName>
                <color>#3333FF</color>
                <label>Diesel</label>
            </value>
            <value>
                <fullName>Electric</fullName>
                <color>#6600CC</color>
                <label>Electric</label>
            </value>
            <value>
                <fullName>Allison Hybrid</fullName>
                <color>#CC9933</color>
                <label>Allison Hybrid</label>
            </value>
            <value>
                <fullName>BAE Hybrid</fullName>
                <color>#009900</color>
                <label>BAE Hybrid</label>
            </value>
            <value>
                <fullName>Trolley (Overhead)</fullName>
                <color>#FF0000</color>
                <label>Trolley (Overhead)</label>
            </value>
            <value>
                <fullName>Glider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Model_Id__c.field-meta.xml
<CustomField>
    <fullName>Model_Id__c</fullName>
    <description>Model Id calculated by using Metadata.</description>
    <label>Model_Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <summarizedField>Opportunity_Sales_Order__c.Quantity__c</summarizedField>
    <summaryForeignKey>Opportunity_Sales_Order__c.Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Rear_Suspension__c.field-meta.xml
<CustomField>
    <fullName>Rear_Suspension__c</fullName>
    <label>Rear Suspension</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>H2</fullName>
            </value>
            <value>
                <fullName>H4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>102</fullName>
                <default>true</default>
                <label>102</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/recordTypes/Merged.recordType-meta.xml
<RecordType>
    <fullName>Merged</fullName>
    <active>true</active>
    <description>Sales Orders that have merged into another Order</description>
    <label>Merged</label>
</RecordType>

force-app/main/default/classes/Sales_OrderTest.cls
@isTest
private class Sales_OrderTest
{
    @testSetup static void init () {
        TestData.init();
        TestData.createAcct();
        TestData.createOpp();
        TestData.createContract();
        TestData.createOppLine(5, 5); //(10,10)
        TestData.createSO();
    }
    
    @isTest
    static void itShouldMergeOrder()
    {
        test.startTest();
        Schema.DescribeSObjectResult soSchema = Schema.SObjectType.Sales_Order__c;
        Map<String,Schema.RecordTypeInfo> soMap = soSchema.getRecordTypeInfosByName();
        Schema.RecordTypeInfo soMergedRecordType = soMap.get('Merged');
        
        // Given 2 Sales Orders
        List<Sales_Order__c> soList = [select id, name from Sales_Order__c];
        
        Sales_Order__c fromSalesOrder = [select id, name from Sales_Order__c where Id =:soList[0].Id];
        Sales_Order__c toSalesOrder = [select id, name from Sales_Order__c where Id =:soList[1].Id];
        List<Bus__c> fromSObusses = [select Id, Name, Sales_Order__c from Bus__c where Sales_Order__c=:fromSalesOrder.Id];
        List<Bus__c> toSObusses = [select Id, Name, Sales_Order__c from Bus__c where Sales_Order__c=:toSalesOrder.Id];
        integer totalBusses = fromSObusses.size()+toSObusses.size();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(fromSalesOrder);
        Sales_Order testSOMerge = new Sales_Order(sc);
        testSOMerge.toSaleOrder = toSalesOrder.name;
        
        // When the merge button is envoked
        
        testSOMerge.mergeTo();
        
        // Then the original Sales Order should be of record type merged
        
        Sales_Order__c originalSo = [select Id, Name, RecordTypeId from Sales_Order__c where Id=:fromSalesOrder.Id];
        system.assertEquals(soMergedRecordType.getRecordTypeId(), originalSo.RecordTypeId);
        
        // and there should be no busses on the original order
        
        List<Bus__c> noBusses = [select Id, Name from Bus__c where Sales_Order__c=:originalSo.Id];
        system.assertEquals(0, noBusses.size());
        
        // and the merged Sales Order has the combined quanity
        List<Bus__c> combinedBusses = [select Id, Name from Bus__c where Sales_Order__c=:toSalesOrder.Id];
        system.assertEquals(totalBusses, combinedBusses.size());
        test.stopTest(); 
    }
    
    @isTest
    static void itShouldSplitOrder()
    {
        // Given a sales order
        test.startTest();    
        List<Sales_Order__c> soList = [select id, name from Sales_Order__c LIMIT 1];
        if(soList.size()>0){
        ApexPages.StandardController sc = new ApexPages.StandardController(soList[0]);
        
        Sales_Order scext = new Sales_Order(sc);
        scext.toSaleOrder = '121212';
        scext.toSalesOrderQty = 2;
        
        
        // When the Split button is invoked
        
        scext.splitTo();
        
        // Then the second sales order should exist and the original should reduce qty
        
        Sales_Order__c splitToSalesOrder = [select Id, Name from Sales_Order__c where Name=:scext.toSaleOrder];
        system.assertEquals(scext.toSaleOrder, splitToSalesOrder.Name);
        
       // Opportunity_Sales_Order__c toSplitOSO = [select Id, Name, Opportunity_Line__c, Sales_Order__c, Quantity__c from Opportunity_Sales_Order__c where Sales_Order__c =:splitToSalesOrder.Id];
       // system.assertEquals(scext.toSalesOrderQty, toSplitOSO.Quantity__c);
            }else{
            System.assert(false, 'No Sales Orders to run the test');
        }
        test.stopTest(); 
        
    }
    
    // Model ID test class
    @isTest
    static void testUpdateModelFieldWithFieldsChanged() {
        test.startTest();          
        List<Sales_order__c> so = new List<Sales_order__c>();        
        for(Sales_order__c s: [select id,name,Length__c,Engine__c,Width__c, Rear_Suspension__c,Letter_Code__c, 
                               Mode__C from Sales_Order__c LIMIT 1]){
                                   s.Engine__c = 'Cummins L9 8.9 Liter'; 
                                   s.Length__c = '40';
                                   s.Width__c = '102';
                                   s.Rear_Suspension__c = 'H4';
                                   s.Letter_Code__c = 'G';
                                   s.Mode__C = 'Diesel';
                                   so.add(s);
                               }         
        update so;
        
        Sales_Order__c updatedSo = [SELECT Id, Model_Id__c FROM Sales_Order__c WHERE Id IN :so LIMIT 1];
        System.debug('updatedSo' +updatedSo.Model_Id__c);
        System.assertEquals('G27D102H4', updatedSo.Model_Id__c);
        test.stopTest();  
    }
    
    @isTest
    static void testUpdateModelFieldWithElectricMode() {
        test.startTest();          
        List<Sales_order__c> so = new List<Sales_order__c>(); 
        for(Sales_order__c s: [select id,Length__c,Engine__c,Width__c, Rear_Suspension__c,Letter_Code__c, 
                               Mode__C from Sales_Order__c LIMIT 1]){
                                   s.Engine__c = 'Electric'; 
                                   s.Length__c = '35';
                                   s.Width__c = '102';
                                   s.Rear_Suspension__c = 'H2';
                                   s.Letter_Code__c = 'G';
                                   s.Mode__C = 'Electric';
                                   so.add(s);
                               }
        update so;
        
        Sales_Order__c updatedSo = [SELECT Id, Model_Id__c FROM Sales_Order__c WHERE Id IN :so LIMIT 1];
        System.debug('updatedSo' +updatedSo.Model_Id__c);
        System.assertEquals('G28B102H2', updatedSo.Model_Id__c);
        test.stopTest();  
    }
    
}