force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Production_Order__c.field-meta.xml
<CustomField>
    <fullName>Production_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Order</label>
    <referenceTo>Production_Order__c</referenceTo>
    <relationshipLabel>Buses</relationshipLabel>
    <relationshipName>Buses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Production_Order_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Production_Order_Sequence__c</fullName>
    <label>Production Order Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>if( or(RecordType.Name =&quot;Delivered&quot;,RecordType.Name =&quot;Firm&quot;,RecordType.Name =&quot;In Service&quot;),  Sales_Order__r.Quantity__c , Opportunity_Line__r.Quantity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Buses</relationshipLabel>
    <relationshipName>Buses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Production_Order__c/Production_Order__c.object-meta.xml
<CustomObject>
    <label>Production Order</label>
    <nameField>
        <label>Production Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Production_Order__c/fields/Bus__c.field-meta.xml
<CustomField>
    <fullName>Bus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden Bus Lookup field to get the start date of the first bus in the current schedule date field</description>
    <label>Bus</label>
    <referenceTo>Bus__c</referenceTo>
    <relationshipLabel>Production Orders</relationshipLabel>
    <relationshipName>Production_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Production_Order__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Production_Order__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Production Orders</relationshipLabel>
    <relationshipName>Production_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <summarizedField>Opportunity_Sales_Order__c.Quantity__c</summarizedField>
    <summaryForeignKey>Opportunity_Sales_Order__c.Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date for initial bus</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/createProductionOrder.cls
public with sharing class createProductionOrder {

	@InvocableMethod(label='Create Production Order' description='Create a Production Order when Sales Order is released')
	public static void insertProductionOrder (List<Sales_Order__c> salesOrders) {

		set<id> soset = new set<id>();
		for (Sales_Order__c soID:salesOrders) {
			soset.add(soID.Id);
		}
		List<Bus__c> busses = [select Id, Sales_Order__c, Production_Order__c, Production_Order_Sequence__c, Start_Date__c from Bus__c where Sales_Order__c in:soset Order By Name];

		List<Production_Order__c> newProdOrder = new List<Production_Order__c>();
		Integer bCount = 0;
		for (Sales_Order__c thisSO:salesOrders) {
			for (Bus__c cBus:busses) {
				if (cBus.Sales_Order__c==thisSO.Id) {
					bCount++;
				}
			}
			newProdOrder.add(new Production_Order__c(Sales_Order__c=thisSO.Id,
														name='B'+thisSO.name.leftPad(6,'0'),
														Start_Date__c=thisSO.Start_Date__c,
														Quantity__c=bCount));
			bCount=0;
		}
		insert newProdOrder;

		Integer prodOrderSeq=1;
		Id lastSO;
		for (Bus__c thisBus:busses) {
			for (Production_Order__c thisProdO:newProdOrder) {
				if (thisBus.Sales_Order__c==thisProdO.Sales_Order__c) {
					thisBus.Production_Order__c=thisProdO.Id;
					break;
				} 
			}
			if (thisBus.Sales_Order__c!=lastSO) {
				prodOrderSeq=1;
				lastSO=thisBus.Sales_Order__c;
			}
			thisBus.Production_Order_Sequence__c=prodOrderSeq;
			prodOrderSeq++;
		}
		update busses;

		return ;
	}
}