force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Production_Order__c.field-meta.xml
<CustomField>
    <fullName>Production_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Production Order</label>
    <referenceTo>Production_Order__c</referenceTo>
    <relationshipLabel>Buses</relationshipLabel>
    <relationshipName>Buses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Production_Order_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Production_Order_Sequence__c</fullName>
    <label>Production Order Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>if( or(RecordType.Name =&quot;Delivered&quot;,RecordType.Name =&quot;Firm&quot;,RecordType.Name =&quot;In Service&quot;),  Sales_Order__r.Quantity__c , Opportunity_Line__r.Quantity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Buses</relationshipLabel>
    <relationshipName>Buses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Production_Order__c/Production_Order__c.object-meta.xml
<CustomObject>
    <label>Production Order</label>
    <nameField>
        <label>Production Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Production_Order__c/fields/Bus__c.field-meta.xml
<CustomField>
    <fullName>Bus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hidden Bus Lookup field to get the start date of the first bus in the current schedule date field</description>
    <label>Bus</label>
    <referenceTo>Bus__c</referenceTo>
    <relationshipLabel>Production Orders</relationshipLabel>
    <relationshipName>Production_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Production_Order__c/fields/Order_Processing_Notes__c.field-meta.xml
<CustomField>
    <fullName>Order_Processing_Notes__c</fullName>
    <label>Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Production_Order__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Production_Order__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Production Orders</relationshipLabel>
    <relationshipName>Production_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Order_Processing_Notes__c.field-meta.xml
<CustomField>
    <fullName>Order_Processing_Notes__c</fullName>
    <label>Order Processing Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <summarizedField>Opportunity_Sales_Order__c.Quantity__c</summarizedField>
    <summaryForeignKey>Opportunity_Sales_Order__c.Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date for initial bus</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Production_Order.cls
public with sharing class Production_Order {

    private final Production_Order__c originProdOrder;
    transient public String toProdOrder {get; set;}
    private List<Bus__c> busList;
    public String fieldValue {get; set;}
    public String selectedbus {get; set;}

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public Production_Order(ApexPages.StandardController stdController) {
        originProdOrder = (Production_Order__c)stdController.getRecord();
        busList = [select Id, Name, Production_Order__c, Start_Date__c from Bus__c where Production_Order__c=:originProdOrder.Id Order by Name];
    }

    public List<SelectOption> prodBusses{
        get{
            List<SelectOption> theseBusses = new List<SelectOption>();
            for(Bus__c busOnProdOrder : busList)
            {
                theseBusses.add(new SelectOption(busOnProdOrder.Name,busOnProdOrder.Name)) ;
            }
            return theseBusses ;
        }
        set;
    }

    public void splitatthisbus(){
        fieldValue = selectedbus;
    }

    public PageReference splitTo() {

//        if () {
//           ApexPages.Message(ApexPages.Severity.ERROR, <exception message here>);
//        }


        Production_Order__c prodOrder = [select Name, Quantity__c,
                                            Sales_Order__c, Order_Processing_Notes__c
                                            from Production_Order__c where Id=:originProdOrder.Id];

        Production_Order__c toProductionOrder = prodOrder.clone(false, true, false, false);
        toProductionOrder.Order_Processing_Notes__c = UserInfo.getName()+' split from Production Order '+toProductionOrder.name;
        toProductionOrder.name = 'B'+selectedbus.leftPad(6,'0');
        insert toProductionOrder;

        Boolean splithere=false;
        Integer fromProdOrderCount=0;
        Integer toProdOrderCount=0;
        Date toProductionOrderStart;
        for (Bus__c thisBus:busList) {
            if (thisBus.Name==selectedbus) {
                splithere=true;
                toProductionOrderStart=thisBus.Start_Date__c;
            } else if (!splithere) {
                fromProdOrderCount++;
            }
            if (splithere) {
                thisBus.Production_Order__c=toProductionOrder.id;
                thisBus.Production_Order_Sequence__c = toProdOrderCount+1;
                toProdOrderCount++;
            }
        }
        update busList;

        prodOrder.Quantity__c=fromProdOrderCount;
        update prodOrder;
        toProductionOrder.Quantity__c=toProdOrderCount;
        toProductionOrder.Start_Date__c=toProductionOrderStart;
        update toProductionOrder;

        PageReference prodOrderPage = new ApexPages.StandardController(toProductionOrder).view();
        prodOrderPage.setRedirect(true);

        return prodOrderPage;
    }
}