force-app/main/default/objects/Contract_Option__c/Contract_Option__c.object-meta.xml
<CustomObject>
    <label>Contract Option</label>
    <nameField>
        <label>Options</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Option__c/fields/Customer_Contract__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contract__c</fullName>
    <label>Customer Contract</label>
    <referenceTo>Customer_Contract__c</referenceTo>
    <relationshipLabel>Member Agencies</relationshipLabel>
    <relationshipName>OptionContract</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Option__c/fields/Expiration__c.field-meta.xml
<CustomField>
    <fullName>Expiration__c</fullName>
    <formula>Customer_Contract__r.Expiration__c</formula>
    <label>Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Option__c/fields/Initial_Qty__c.field-meta.xml
<CustomField>
    <fullName>Initial_Qty__c</fullName>
    <formula>Customer_Contract__r.Initial_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Initial Qty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Option__c/fields/Member_Agency__c.field-meta.xml
<CustomField>
    <fullName>Member_Agency__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Joint Procurements</relationshipLabel>
    <relationshipName>OptionAccount</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Option__c/fields/Optional_Qty__c.field-meta.xml
<CustomField>
    <fullName>Optional_Qty__c</fullName>
    <formula>Customer_Contract__r.Optional_Quantities__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Optional Qty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Option__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Option__c/fields/ReferenceContract__c.field-meta.xml
<CustomField>
    <fullName>ReferenceContract__c</fullName>
    <formula>Customer_Contract__r.Name</formula>
    <label>Reference Contract</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Option__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <formula>Customer_Contract__r.Term_Years__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Contract__c/Customer_Contract__c.object-meta.xml
<CustomObject>
    <label>Customer Contract</label>
    <nameField>
        <label>Customer Contract Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Contract__c/fields/Expiration__c.field-meta.xml
<CustomField>
    <fullName>Expiration__c</fullName>
    <label>Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/listJointProcurements.cls
public class listJointProcurements {
	
    public ID objId {get; set;}

	public Contract_Option__c[] getlistJointProcurements () {
		return [SELECT ID, ReferenceContract__c, Member_Agency__c, Customer_Contract__c, 
                Quantity__c, Initial_Qty__c, Optional_Qty__c, Expiration__c, Term__c 
                from Contract_Option__c where Member_Agency__c = :objId 
                    and Expiration__c >= :system.today()];
	}
}