force-app/main/default/objects/Contract_Option__c/Contract_Option__c.object-meta.xml
<CustomObject>
    <label>Contract Option</label>
    <nameField>
        <label>Options</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Option__c/fields/Customer_Contract__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contract__c</fullName>
    <label>Customer Contract</label>
    <referenceTo>Customer_Contract__c</referenceTo>
    <relationshipLabel>Member Agencies</relationshipLabel>
    <relationshipName>OptionContract</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Option__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet__c/Fleet__c.object-meta.xml
<CustomObject>
    <label>Fleet</label>
    <nameField>
        <label>Fleet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Fleet__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>DIESEL</fullName>
            </value>
            <value>
                <fullName>ELECTRIC</fullName>
            </value>
            <value>
                <fullName>HYBRID ALLISON</fullName>
            </value>
            <value>
                <fullName>HYBRID BAE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fleet__c/fields/Opportunity_Line__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Line</label>
    <referenceTo>Opportunity_Line__c</referenceTo>
    <relationshipLabel>Fleet</relationshipLabel>
    <relationshipName>Fleet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fleet__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>Active_Quantity_Competitor__c + Active_Quantity_GILLIG__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fleet__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Fleet</relationshipLabel>
    <relationshipName>Fleet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fleet__c/fields/Style__c.field-meta.xml
<CustomField>
    <fullName>Style__c</fullName>
    <formula>if( RecordType.Name =&quot;Competitor&quot;,Style_Competitor__c,if(isblank( Sales_Order__c ),&quot;TBD&quot;,text( Sales_Order__r.Style__c )))</formula>
    <label>Style</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/Opportunity_Line__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line</label>
    <nameField>
        <label>Opportunity Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>Allison Hybrid</fullName>
            </value>
            <value>
                <fullName>BAE Hybrid</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Trolley (Overhead)</fullName>
            </value>
            <value>
                <fullName>Glider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Opportunity_Line__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Lines</relationshipLabel>
    <relationshipName>Opportunity_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/PO_Amount__c.field-meta.xml
<CustomField>
    <fullName>PO_Amount__c</fullName>
    <label>PO Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/PO_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Date__c</fullName>
    <label>PO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/PO_Reference__c.field-meta.xml
<CustomField>
    <fullName>PO_Reference__c</fullName>
    <label>PO Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Quoted_Price__c.field-meta.xml
<CustomField>
    <fullName>Quoted_Price__c</fullName>
    <description>Price per most recent quote</description>
    <label>Quoted Price</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <description>Serial Number for First Bus</description>
    <label>Serial Number</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date for First Bus</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Style__c.field-meta.xml
<CustomField>
    <fullName>Style__c</fullName>
    <label>Style</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low Floor</fullName>
            </value>
            <value>
                <fullName>Low Floor BRT</fullName>
            </value>
            <value>
                <fullName>Low Floor Plus</fullName>
            </value>
            <value>
                <fullName>BRT PLUS</fullName>
            </value>
            <value>
                <fullName>Trolley</fullName>
            </value>
            <value>
                <fullName>Double Decker</fullName>
            </value>
            <value>
                <fullName>Suburban</fullName>
                <label>SUBURBAN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/recordTypes/Booked.recordType-meta.xml
<RecordType>
    <fullName>Booked</fullName>
    <active>false</active>
    <label>Booked</label>
</RecordType>

force-app/main/default/objects/Opportunity_Sales_Order__c/Opportunity_Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Opportunity Sales Order</label>
    <nameField>
        <label>Opportunity Sales Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Sales Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Sales_Order__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <formula>TEXT( Sales_Order__r.Mode__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Sales_Order__c/fields/Opportunity_Line__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line__c</fullName>
    <label>Opportunity Line</label>
    <referenceTo>Opportunity_Line__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Order</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Sales_Order__c/fields/PO_Amount__c.field-meta.xml
<CustomField>
    <fullName>PO_Amount__c</fullName>
    <formula>Opportunity_Line__r.PO_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PO Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Sales_Order__c/fields/PO_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Date__c</fullName>
    <formula>Opportunity_Line__r.PO_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_Sales_Order__c/fields/PO_Reference__c.field-meta.xml
<CustomField>
    <fullName>PO_Reference__c</fullName>
    <formula>Opportunity_Line__r.PO_Reference__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PO Reference</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Sales_Order__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Opportunity Lines</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Sales_Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <formula>Opportunity_Line__r.Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_Sales_Order__c/fields/Style__c.field-meta.xml
<CustomField>
    <fullName>Style__c</fullName>
    <formula>TEXT(Sales_Order__r.Style__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Style</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CNG</fullName>
                <color>#CC6600</color>
                <label>CNG</label>
            </value>
            <value>
                <fullName>Diesel</fullName>
                <color>#3333FF</color>
                <label>Diesel</label>
            </value>
            <value>
                <fullName>Electric</fullName>
                <color>#6600CC</color>
                <label>Electric</label>
            </value>
            <value>
                <fullName>Allison Hybrid</fullName>
                <color>#CC9933</color>
                <label>Allison Hybrid</label>
            </value>
            <value>
                <fullName>BAE Hybrid</fullName>
                <color>#009900</color>
                <label>BAE Hybrid</label>
            </value>
            <value>
                <fullName>Trolley (Overhead)</fullName>
                <color>#FF0000</color>
                <label>Trolley (Overhead)</label>
            </value>
            <value>
                <fullName>Glider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/PO_Amount__c.field-meta.xml
<CustomField>
    <fullName>PO_Amount__c</fullName>
    <label>PO Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/PO_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Date__c</fullName>
    <label>PO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <summarizedField>Opportunity_Sales_Order__c.Quantity__c</summarizedField>
    <summaryForeignKey>Opportunity_Sales_Order__c.Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Quoted_Price__c.field-meta.xml
<CustomField>
    <fullName>Quoted_Price__c</fullName>
    <label>Quoted Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date for initial bus</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/compareOppLinetoSalesOrderTest.cls
@isTest
private class compareOppLinetoSalesOrderTest
{
    static Opportunity tOpportunity;
    static List<Opportunity_Line__c> tOppLine;
    static List<Opportunity_Line__c> bwOppLine;
    static Customer_Contract__c cContract;
    static User rRep;
    static User pRep;
    static Opportunity_Sales_Order__c resultingOSO;
    static Sales_Order__c resultingSO;

    @testSetup static void init() {

        TestData.init();
        TestData.createAcct();
        TestData.createOpp();
        TestData.createContract();
        TestData.createOppLine(10, 10);

    }

	@isTest
	static void itShouldNotMatch()
	{
		// Given an existing Sales Order
        List<Opportunity_Line__c> tOpps = [select Id, Quantity__c, Start_Date__c, Serial_Number__c, Opportunity_Line__c, Mode__c, PO_Amount__c, PO_Date__c, PO_Reference__c, Quoted_Price__c, Style__c, Length__c, Contract_Option__c, Book_with_Sales_Order__c, Fleet__c, Date_Booked__c
                        from Opportunity_Line__c];
        tOpps[0].Serial_Number__c = '123456';
        tOpps[0].Length__c = '35';
        tOpps[0].Start_Date__c = system.today().addYears(2);
        tOpps[0].Date_Booked__c = system.today();
        update tOpps;
        createSO.insertSO(tOpps);
        list<Sales_Order__c> resultingSO = [select Id, Name, Length__c, Mode__c, Style__c from Sales_Order__c];

        // Given another Opportunity Line that doesn't match the Sales Order

		test.startTest();

		// When the Opportunity Line is booked with the exisitng Sales Order

		tOpps[1].Book_with_Sales_Order__c = resultingSO[0].Id;
        tOpps[1].Date_Booked__c = system.today();

		// Then there should be an error that indicates the Opportunity Line doesn't match

		system.assertEquals(false, compareOppLinetoSalesOrder.match(tOpps[1], resultingSO[0]));

		test.stopTest();
	}

	@isTest
	static void itShouldMatch() {

		// Given an existing Sales Order
        List<Opportunity_Line__c> tOpps = [select Id, Quantity__c, Start_Date__c, Serial_Number__c, Opportunity_Line__c, Mode__c, PO_Amount__c, PO_Date__c, PO_Reference__c, Quoted_Price__c, Style__c, Length__c, Contract_Option__c, Book_with_Sales_Order__c, Fleet__c, Date_Booked__c
                        from Opportunity_Line__c];
        tOpps[0].Serial_Number__c = '123456';
        tOpps[0].Start_Date__c = system.today().addYears(2);
        tOpps[0].Date_Booked__c = system.today();
        update tOpps;
        createSO.insertSO(tOpps);
        list<Sales_Order__c> resultingSO = [select Id, Name, Length__c, Mode__c, Style__c from Sales_Order__c];

        // Given another Opportunity Line that matches the Sales Order

 		test.startTest();

		// When the Opportunity Line is booked with the exisitng Sales Order

		tOpps[1].Book_with_Sales_Order__c = resultingSO[0].Id;
        tOpps[1].Date_Booked__c = system.today();
        
		// Then there should be an error that indicates the Opportunity Line doesn't match

		system.assertEquals(true, compareOppLinetoSalesOrder.match(tOpps[1], resultingSO[0]));

		test.stopTest();	
	}
}