force-app/main/default/objects/Knowledge__kav/fields/Diagnostic_Steps__c.field-meta.xml
<CustomField>
    <fullName>Diagnostic_Steps__c</fullName>
    <label>Diagnostic Steps</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Issue_Description1__c.field-meta.xml
<CustomField>
    <fullName>Issue_Description1__c</fullName>
    <label>Issue Description (Rich Text)</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Labor_Information__c.field-meta.xml
<CustomField>
    <fullName>Labor_Information__c</fullName>
    <label>Labor Information</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Parts_Required__c.field-meta.xml
<CustomField>
    <fullName>Parts_Required__c</fullName>
    <label>Parts Required:</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Parts_Return_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Parts_Return_Disposition__c</fullName>
    <label>Parts Return Disposition</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Repair_Steps__c.field-meta.xml
<CustomField>
    <fullName>Repair_Steps__c</fullName>
    <label>Repair Steps</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Symptoms1__c.field-meta.xml
<CustomField>
    <fullName>Symptoms1__c</fullName>
    <label>Symptoms (Rich Text)</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Tools_Required1__c.field-meta.xml
<CustomField>
    <fullName>Tools_Required1__c</fullName>
    <label>Tools Required (Rich Text)</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Vendor_Article__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Article__c</fullName>
    <description>A URL Link to the Vendor Article</description>
    <label>Vendor Article</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Warranty_Claims__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Claims__c</fullName>
    <label>Warranty Claims</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/KnowledgeArticleController.cls
public class KnowledgeArticleController {
    public Knowledge__kav account;
    public KnowledgeArticleController() {
        account = [SELECT Id, Title,Issue_Description1__c,Symptoms1__c,Tools_Required1__c,Parts_Required__c,Diagnostic_Steps__c,Repair_Steps__c,Labor_Information__c,Warranty_Claims__c,
                   Parts_Return_Disposition__c, Vendor_Article__c,VersionNumber,PublishStatus FROM Knowledge__kav 
                   WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
        system.debug('Id=====>' +ApexPages.currentPage().getParameters().get('id'));
    }
    public Knowledge__kav getAccount() {
        return account;
        
    }
}