force-app/main/default/objects/Opportunity/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/Opportunity_Line__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line</label>
    <nameField>
        <label>Opportunity Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Opportunity_Line__r.Account.Id</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>35</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>Allison Hybrid</fullName>
            </value>
            <value>
                <fullName>BAE Hybrid</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Trolley (Overhead)</fullName>
            </value>
            <value>
                <fullName>Glider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Opportunity_Line__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Lines</relationshipLabel>
    <relationshipName>Opportunity_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/fields/Style__c.field-meta.xml
<CustomField>
    <fullName>Style__c</fullName>
    <label>Style</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low Floor</fullName>
            </value>
            <value>
                <fullName>Low Floor BRT</fullName>
            </value>
            <value>
                <fullName>Low Floor Plus</fullName>
            </value>
            <value>
                <fullName>BRT PLUS</fullName>
            </value>
            <value>
                <fullName>Trolley</fullName>
            </value>
            <value>
                <fullName>Double Decker</fullName>
            </value>
            <value>
                <fullName>Suburban</fullName>
                <label>SUBURBAN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line__c/recordTypes/Forecasted.recordType-meta.xml
<RecordType>
    <fullName>Forecasted</fullName>
    <active>true</active>
    <description>Active Opportunity</description>
    <label>Forecasted</label>
</RecordType>

force-app/main/default/objects/Trip_Report__c/Trip_Report__c.object-meta.xml
<CustomObject>
    <label>Trip Report</label>
    <nameField>
        <label>Trip Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Report__c/fields/Account_Visited__c.field-meta.xml
<CustomField>
    <fullName>Account_Visited__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Visited</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trip Reports</relationshipLabel>
    <relationshipName>Trip_Reports2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityLineRelatedList.cls
/***********************************************************************************************************************************
     Developer :Suyati
     Name      : OpportunityLineRelatedList
     Usage     : Apex Controller to display and update OpportunityLines
     Associated Component:OpportunityLineRelatedListComponent
     Date      : October 2019   
************************************************************************************************************************************/   

public class OpportunityLineRelatedList {   
    /***********************************************************************************************************************************
     Method Name  : getOpportunityLines
     Parameters   : String 
     Return Type  : List<Opportunity_Line__c>    
     Method call  : getOpportunityLines(recordId)
     Description  : Queries Forecasted opportunity lines
   ************************************************************************************************************************************/   
    @auraEnabled
    public static List<Opportunity_Line__c> getOpportunityLines(String recordId)
    {
        Id RecordTypeId = Schema.SObjectType.Opportunity_Line__c.getRecordTypeInfosByName().get('Forecasted').getRecordTypeId();
         List<Opportunity_Line__c> opportunityLineList=new  List<Opportunity_Line__c>();
        try{
        String AccountId=[SELECT Account_Visited__c  FROM Trip_Report__c where Id=:recordId].Account_Visited__c;
        String AccountIdTruncated=AccountId.substring(0, 15);
            opportunityLineList=[SELECT Id,Name, Mode__c,Length__c,Style__c,Quantity__c,Account__c,RecordtypeId,Recordtype.name FROM Opportunity_Line__c where RecordtypeId=:RecordTypeId  and Account__c=:AccountIdTruncated and Opportunity_Line__r.IsClosed = False and Opportunity_Line__r.IsWon=False]; 
            
        }
        catch(Exception e){
               System.debug('The following exception has occurred: ' + e.getMessage());
        }
        return opportunityLineList;
    }

}