force-app/main/default/objects/Opportunity/fields/Order_Probability__c.field-meta.xml
<CustomField>
    <fullName>Order_Probability__c</fullName>
    <label>Order Probability</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. High Probability</fullName>
            </value>
            <value>
                <fullName>2. Medium Probability</fullName>
            </value>
            <value>
                <fullName>3. Low Probability</fullName>
            </value>
            <value>
                <fullName>4. Unlikely</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip_Report__c/Trip_Report__c.object-meta.xml
<CustomObject>
    <label>Trip Report</label>
    <nameField>
        <label>Trip Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Report__c/fields/Account_Visited__c.field-meta.xml
<CustomField>
    <fullName>Account_Visited__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Visited</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trip Reports</relationshipLabel>
    <relationshipName>Trip_Reports2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Date_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Visit__c</fullName>
    <label>Date of Visit</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/listOppDiscussedTest.cls
@isTest (seeAllData=false)
public class listOppDiscussedTest {

    public static account tAccount;
    public static opportunity tOpportunity;
    public static Trip_Report__c tTrip;
    
    public static ID objId;
    
    public static void init() {
        tAccount = new account (Name='Test Account');
        insert tAccount;
        system.debug(tAccount);
        tOpportunity = new opportunity (AccountID=tAccount.ID,Name='Test Opp',StageName='Forecast', 
                                                    Type = 'Existing Business', Order_Probability__c = '1. High Probability',
                                                    CloseDate=system.today());
		insert tOpportunity;
        system.debug(tOpportunity);
        tTrip = new Trip_Report__c(Account_Visited__c=tAccount.ID, Date_of_Visit__c=system.today());
        insert tTrip;
		system.debug(tTrip);
        objId = tTrip.ID;
        system.debug(objId);
    }

    public static testmethod void testOppDiscussed() {
        init();
        Test.startTest();
        
        listOppDiscussed cOppD = new listOppDiscussed();
        cOppD.objId = objId;
        cOppD.getlistOppDiscussed();
        
        system.debug(cOppD);
        
        system.assertEquals(tOpportunity.ID, cOppD.op.ID);
        system.assertEquals(Null, cOppd.ODList);
        system.assertEquals(Null, cOppd.tOpp);
        
        Test.stopTest();

    }
}