force-app/main/default/objects/Opportunity/fields/Order_Probability__c.field-meta.xml
<CustomField>
    <fullName>Order_Probability__c</fullName>
    <label>Order Probability</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1. High Probability</fullName>
            </value>
            <value>
                <fullName>2. Medium Probability</fullName>
            </value>
            <value>
                <fullName>3. Low Probability</fullName>
            </value>
            <value>
                <fullName>4. Unlikely</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip_Report__c/Trip_Report__c.object-meta.xml
<CustomObject>
    <label>Trip Report</label>
    <nameField>
        <label>Trip Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Report__c/fields/Account_Visited__c.field-meta.xml
<CustomField>
    <fullName>Account_Visited__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Visited</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trip Reports</relationshipLabel>
    <relationshipName>Trip_Reports2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip_Report__c/fields/Date_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Visit__c</fullName>
    <label>Date of Visit</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TripContact__c/TripContact__c.object-meta.xml
<CustomObject>
    <label>Contact Visited</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>TripContact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts Visited</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TripContact__c/fields/TripContact__c.field-meta.xml
<CustomField>
    <fullName>TripContact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trip Reports</relationshipLabel>
    <relationshipName>Trip_Visit</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TripContact__c/fields/TripReport__c.field-meta.xml
<CustomField>
    <fullName>TripReport__c</fullName>
    <label>Trip Report</label>
    <referenceTo>Trip_Report__c</referenceTo>
    <relationshipLabel>Contacts Visited</relationshipLabel>
    <relationshipName>Contacts_Visited</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TripOpportunity__c/TripOpportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity Discussed</label>
    <nameField>
        <displayFormat>TO-{00000}</displayFormat>
        <label>tripopportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities Discussed</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TripOpportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Trip Reports</relationshipLabel>
    <relationshipName>Trip_Report</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TripOpportunity__c/fields/TripReport__c.field-meta.xml
<CustomField>
    <fullName>TripReport__c</fullName>
    <label>Trip Report</label>
    <referenceTo>Trip_Report__c</referenceTo>
    <relationshipLabel>Opportunities Discussed</relationshipLabel>
    <relationshipName>Opportunities_Discussed</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/addTripDetailTest.cls
@isTest (seeAllData=false)
Private class addTripDetailTest {

    static Account tAccount;
    static Trip_Report__c tripReport;
    static List<Contact> tconts;
    static List<Opportunity> tOpportunity;
    
    static void init(){
        tAccount = new Account(Name='Test Account');
        insert tAccount;
        tconts = new List<Contact>();

        for (Integer i = 0; i < 101; i++) {
            tconts.add(new contact (AccountID=tAccount.ID,FirstName='Test - '+i.format(),
                                    LastName='Contact'+i.format()));
        }
        insert tconts;
        
        tOpportunity = new List<Opportunity>();
        for (Integer j = 0; j < 101; j++) {
            tOpportunity.add(new Opportunity(AccountID=tAccount.ID,Name='TestOpportunity - '+j.format(),StageName='Forecast', 
                                                    Type = 'Existing Business',Order_Probability__c = '1. High Probability', 
                                                    CloseDate=system.today()));
        }
        insert tOpportunity;

        tripReport = new Trip_Report__c(Account_Visited__c=tAccount.Id, Date_of_Visit__c=system.today());
        insert tripReport;
    }
    
    static testMethod void testContactDetailTrigger () {
        init();

        set<id> cidset = new set<id>();
        for (contact chkContact:[select id from contact where AccountID=:tAccount.id]) {
            cidset.add(chkContact.id);
        }

        Test.startTest();
        
        List<TripContact__c> tripContact = new List<TripContact__c>([
            SELECT Id, TripContact__c
            FROM TripContact__c
            WHERE TripReport__c  = :tripReport.Id
        ]);

        for (Integer i = 0; i < 101; i++) {
//        	system.assertEquals(tconts[i].ID, tripContact[i].TripContact__c);
            system.assert(cidset.contains(tconts[i].ID));
        }

        Test.stopTest();
                
    }
    static testMethod void testOppDetailTrigger () {
        init();

        set<id> oidset = new set<id>();
        for (Opportunity chkOpp:[select id from Opportunity where AccountID=:tAccount.id]) {
            oidset.add(chkOpp.id);
        }

        Test.startTest();

        List<TripOpportunity__c> tripOpp = new List<TripOpportunity__c>([
            SELECT Id, Opportunity__c
            FROM TripOpportunity__c
            WHERE TripReport__c  = :tripReport.Id
        ]);

        for (Integer i = 0; i < 101; i++) {
//        	system.assertEquals(tripOpp[i].Opportunity__c, tOpportunity[i].Id);
            system.assert(oidset.contains(tripOpp[i].Opportunity__c));
        }        
        
        Test.stopTest();
                
    }    
}