force-app/main/default/objects/Opportunity/fields/Total_Qty__c.field-meta.xml
<CustomField>
    <fullName>Total_Qty__c</fullName>
    <label>Total Qty</label>
    <summarizedField>Opportunity_Line__c.Quantity__c</summarizedField>
    <summaryForeignKey>Opportunity_Line__c.Opportunity_Line__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TripOpportunity__c/TripOpportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity Discussed</label>
    <nameField>
        <displayFormat>TO-{00000}</displayFormat>
        <label>tripopportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities Discussed</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TripOpportunity__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/TripOpportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Trip Reports</relationshipLabel>
    <relationshipName>Trip_Report</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TripOpportunity__c/fields/TripReport__c.field-meta.xml
<CustomField>
    <fullName>TripReport__c</fullName>
    <label>Trip Report</label>
    <referenceTo>Trip_Report__c</referenceTo>
    <relationshipLabel>Opportunities Discussed</relationshipLabel>
    <relationshipName>Opportunities_Discussed</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/listOppDiscussed.cls
public class listOppDiscussed {

    public ID objId {get; set;}
    public Opportunity op {get; set;}
    public List<TripOpportunity__c> tOpp {get; set;}
    public List<TripOppDiscussed> ODList{get; set;}
    
    public List<TripOppDiscussed> getlistOppDiscussed() {
        List<TripOppDiscussed> ODList = new List<TripOppDiscussed>();
        for (TripOpportunity__c a : [Select ID, Comments__c, Opportunity__c, Opportunity__r.CloseDate
                                     from TripOpportunity__c where TripReport__c = :objId
                                     order by Opportunity__r.CloseDate]){
            op = [Select CloseDate, Name, StageName, Discovery_Completed__c, ROI_Analysis_Completed__c, Total_Qty__c from Opportunity where ID = :a.Opportunity__c];
            ODList.add(new TripOppDiscussed(op, a));
        }
//        ODList.sort();
        return ODList;
    }
    
    public class TripOppDiscussed {
    	public Opportunity opp {get; set;}
    	public TripOpportunity__c oppD {get; set;}
    	public TripOppDiscussed(Opportunity o, TripOpportunity__c t) {
        opp = o;
        oppD = t;
        }
    }
}